### ISSUE TITLE
Plugin config through global config

### ISSUE THREAD

**Issue by Birne94** [taverntesting/tavern#113]
When using a plugin that requires additional configuration (e.g. `tavern-flask`), the config needs to be provided in every test file at least once. Multiple tests within one file may reference it through anchors.

Example:

```yaml
flask:
  app:
    location: tests.integration.server:app
```

Since most likely the whole test suite will use the same plugins, it would be a good QoL change to be able to configure plugins through the global config, specified through `tavern-global-cfg` in either the `pytest.ini` or per command line.

In order to keep this as flexible as possible, I would suggest adding a global configuration option whose values are inserted into all test-specs.

Example global-config.yaml
```yaml
inject:
  flask:
    app:
      location: tests.integration.server:app
```

Example test.tavern.yaml

```yaml
test_name: test_api_auth

stages:
 - ...
```

Which results in a test spec equal to

```yaml
test_name: test_api_auth
flask:
  app:
    location: tests.integration.server:app
stages:
 - ...
```

The implementation should be relatively trivial since test spec and global config are both available in `YamlItem::runtest` and we can simply update the spec dictionary here with the additional values. I guess the implementation for `tavern-ci` would be similar.

@michaelboulton would this be a desirable approach? If so I can submit a PR.
