### ISSUE TITLE
Add support for before/after test stage actions

### ISSUE THREAD

**Issue by Birne94** [taverntesting/tavern#114]
follow up to this comment: https://github.com/taverntesting/tavern/issues/41#issuecomment-370462578

Currently, the support for pre- and post-stage actions is rather limited. The only ones we support right now are delays and clearing cookies. I suggest adding the possibility to call arbitrary functions here. The format could be similar to the `$ext` function calls currently allowed for validation.

One use case we have for this would be to use [freezegun](https://github.com/spulec/freezegun) to simulate changes in time for a single request (e.g. for testing session expiry).

```yaml
stages:
  - name: test-datetime-endpoint

    before:
      - function: my.package.utils.freeze
        extra_kwargs:
          time: "2018-05-31 12:00:00"

    after:
      - function: my.package.utils.unfreeze

    request:
      url: "{host}/get-time"
      method: GET

    response:
      status_code: 200
      body:
        current_time: "2018-05-31 12:00:00"
```

```python
# my.package.utils

def freeze(time, context):
    t = context['freezegun'] = freezegun.freeze_time(time)
    t.start()


def unfreeze(context):
    t = context.pop('freezegun')
    t.stop()

```

Note the `context` parameter I have added here which allows passing a context object (might just be a dictionary) to the function. This allows a pair of setup- and teardown methods to keep track of created objects. The context may also contain additional info, for example the session is required for clearing the cookies.

The context variable should be injected dynamically, which is controlled either through an attribute in the spec or through a decorator:

```yaml
      - function: my.package.utils.freeze
        with_context: true
        extra_kwargs:
          time: "2018-05-31 12:00:00"
```

```python
# sets freeze._context = True
@tavern.utils.inject_context
def freeze(time, context):
    t = context['freezegun'] = freezegun.freeze_time(time)
    t.start()
```

This allows us to still use functions without context which is useful when using builtins (e.g. `time.sleep` as a replacement for `delay_after` and `delay_before`).

What are your thoughts on this?
