### ISSUE TITLE
Formatting curly braces in json string

### ISSUE THREAD

**Issue by dizzy** [taverntesting/tavern#117]
Hi All,

I have following test declaration

```
test_name: test name
stages:
  - name: test
    request:
      url: http://localhost
      method: POST
      json: {"query": "{ val1 { val2 { val3 { val4, val5 } } } }"}
      headers:
        content-type: application/json
    response:
      status_code: 200
```
where I have to send query key value in a proprietary syntax (dict python like), e.g.
```
{
  "query": "{ val1 { val2 { val3 { val4, val5 } } } }"
}
```

This fails with error below

```
tester            |     def format_keys(val, variables):
tester            |         """recursively format a dictionary with the given values
tester            |     
tester            |         Args:
tester            |             val (dict): Input dictionary to format
tester            |             variables (dict): Dictionary of keys to format it with
tester            |     
tester            |         Returns:
tester            |             dict: recursively formatted dictionary
tester            |         """
tester            |         formatted = val
tester            |         box_vars = Box(variables)
tester            |     
tester            |         if isinstance(val, dict):
tester            |             formatted = {}
tester            |             #formatted = {key: format_keys(val[key], box_vars) for key in val}
tester            |             for key in val:
tester            |                 formatted[key] = format_keys(val[key], box_vars)
tester            |         elif isinstance(val, (list, tuple)):
tester            |             formatted = [format_keys(item, box_vars) for item in val]
tester            |         elif isinstance(val, str):
tester            |             try:
tester            | >               formatted = val.format(**box_vars)
tester            | E               ValueError: unexpected '{' in field name
tester            | 
tester            | /usr/local/lib/python3.6/site-packages/tavern/util/dict_util.py:38: ValueError
```
Workaround for this is to escape `{` by doubling them so it  won't be interpret it as a dict, e.g.:
```
{
  "query": "{{ val1 {{ val2 {{ val3 {{ val4, val5 }} }} }} }}"
}
```
I can live with this workaround but I can look it in and issue a PR if you think it worth and you see no other side effects. At the minimum it should be documented IMO

Thanks!
