### ISSUE TITLE
Q: Is it possible to validate plain string in the response body? 

### ISSUE THREAD

**Issue by againagainst** [taverntesting/tavern#120]
I have just a plain string in response body, let's say "pong", which is valid JSON.
However, I had no luck with the following schema:
```
test_name: basic test

stages:
  - name: test get ping

    request:
      url: http://localhost:8888/ping
      method: GET

    response:
      status_code: 200
      body:
        pong
```
The error is `E           tavern.util.exceptions.BadSchemaError: Error at /stages/0/response/body - expected a list or dict`. Is there a solution for such cases?
