### ISSUE TITLE
Ability to load extern schema file for kwalify?

### ISSUE THREAD

**Issue by shaleh** [taverntesting/tavern#142]
I would like to have a test like this:

```
  - name: Get category list
    request:
      url: "{host}/api/v1/category"
      method: GET
    response:
      status_code: 200
      headers:
        content-type: application/json
      body:
        $ext:
          function: tavern.testutils.helpers:validate_pykwalify
          extra_kwargs:
            schema: !include category.schema.yaml
```

This way we can use the schema directly with kwalify and here in the test. Is there are way to do this? If not, what would be involved in adding it?
