### ISSUE TITLE
!bool casts all string values to True

### ISSUE THREAD

**Issue by tommilligan** [taverntesting/tavern#149]
Tavern provides a `!bool` constructor that is used during configuration for [type conversion](https://taverntesting.github.io/documentation#type-conversions).

Unfortunately, it uses Python's underlying [`bool` constructor](https://docs.python.org/3.7/library/functions.html#bool) which casts all non-empty strings to `True`.

```yaml
value: !!bool "True"
# True
value: !bool "{v_true}"
# True

value: !!bool "False"
# False
value: !bool "{v_false}"
# True
```

[This integration test](https://github.com/taverntesting/tavern/blob/61065bd294b03a33caa0d2ef15fc2908181b5964/tests/integration/test_typetokens.tavern.yaml#L201) would fail if the value was checked.

**Comment by tommilligan** [comment]
Fixed by #150

**Comment by tommilligan** [comment]
PR #150 submitted and passed CI

**Comment by tommilligan** [comment]
For reference, my specific use case was trying to disable request SSL checking with a variable (to use in my local development environment):
```yaml
variables:
  verify-ssl: False

---

test_name: Test health
stages:
- name: health
  request:
    url: ...
    method: POST
    json:
      ...
    verify:
      value: !bool "{verify-ssl}"
```
