### ISSUE TITLE
Not Seeing Headers On Form-Url-Encoded Request

### ISSUE THREAD

**Issue by dagrooms52** [taverntesting/tavern#152]
I set up a test to send `form-urlencoded` data to a SAML endpoint that I need to log in with to access my server. The SAML IDP responds that the request was not a valid SAML request. I replicated the request in Postman and compared it side-by-side to the Tavern HTTP request using Charles proxy, and saw the following difference:

*Postman Request Headers:*
```
CONNECT jsonplaceholder.typicode.com:443 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
cache-control: no-cache
User-Agent: PostmanRuntime/7.1.1
Accept: */*
host: jsonplaceholder.typicode.com:443
Connection: close
```

*Tavern Request Headers:*
```
CONNECT jsonplaceholder.typicode.com:443 HTTP/1.0
```

Why do I not see any request headers coming from Tavern? It looks like this could be the reason that my SAML IDP is rejecting the sign-in request.

Here is the jsonplaceholder test I used to show that no headers can be seen on the request:
```
test_name: Test Form POST Headers

stages:

  - name: POST With Headers

    request:
      url: "https://jsonplaceholder.typicode.com/posts"
      method: POST
      headers:
        Accept: "*/*"
        Content-Type: "application/x-www-form-urlencoded"
      data:
        title: "billy"
        body: "bob"
        userId: 20

    response:
      status_code: 201
```

And a screenshot of the Postman request setup
<img width="504" alt="screen shot 2018-07-11 at 9 29 09 am" src="https://user-images.githubusercontent.com/8743446/42579004-f4565464-84ec-11e8-8072-d39f06e01c48.png">
