### ISSUE TITLE
Fix travis deployment

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#169]
This has been a long standing issue, I just want travis to run the 'deploy' stage on a tag but it doesn't seem to work. Example from documentation https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#conditional-jobs:

```yaml
jobs:
  include:
    - # require the branch name to be master (note for PRs this is the base branch name)
      if: branch = master
```
From the current .travis.yml https://github.com/taverntesting/tavern/blob/753105f99ba9221f8b0954955a5e16e213bc3ec4/.travis.yml#L94

Actual result from travis https://travis-ci.org/taverntesting/tavern/jobs/412148793 : 
```
/home/travis/.travis/job_stages: line 759: expected `)'
/home/travis/.travis/job_stages: line 759: syntax error near `='
/home/travis/.travis/job_stages: line 759: `  if [[ ($TRAVIS_BRANCH = branch = master AND tag IS present) ]]; then'
```
so I don't know if the documentation is wrong or if I'm using it wrong
