### ISSUE TITLE
Only test specific parameters

### ISSUE THREAD

**Issue by lpodl** [taverntesting/tavern#17]
We are testing on JSON files like so: https://jsonplaceholder.typicode.com/users/1 . However, we don't want to test on every given parameter, but only on some of them in every stage.

Is there a way to ignore parameters, that I don't want to test?
In the given example I'd like to test for the street and for the Street only.
Therefor I tried:
```
test_name: Street
stages:
    - name: Test address-street = "Kulas Light"
      request:
        url: https://jsonplaceholder.typicode.com/users/1
        method: GET
      response:
        body:
          address:
            street: Kulas Light
```
This doesn't pass, since tavern expects me to list "suite","city", etc.

Any suggestions?

**Comment by michaelboulton** [comment]
If you know that suite/city/zipcode/etc. are always going to be there then you can just do something like

```yaml
      response:
        body:
          address:
            street: Kulas Light
            zipcode: null
            city: null
            ...
```

Other than that, for the time being you'd have to write a validation function to check it instead.

I thought about this a while ago when first writing the program - I think the 'response' block needs some key like 'only_check_expected' which only ensures that the expected values are there, not that the returned values exactly match the expected values
