### ISSUE TITLE
Saved integer returning dict when using in request/response

### ISSUE THREAD

**Issue by DenBeke** [taverntesting/tavern#174]
When I save an integer from a response, I can successfully use it in the url to another request.
But it doesn't seem to work when I use it in a request or response data:

```yml
stages:
  - name: Add something 

    request:
      url: http://localhost:5000/foo
      method: POST
      json:
        some_data: 7878271

    response:
      status_code: 200
      save:
        body:
          some_saved_param: some_data
  
  - name: Get something

    request:
      url: http://localhost:5000/foo/{some_saved_param}
      method: GET

    response:
      status_code: 200
      body:
        id: {some_saved_param}
```

This is the error I get:

`Value mismatch in body: Type of returned data was different than expected (expected["some_data"] = '{'some_saved_param': None}', actual["some_data"] = '724')`
