### ISSUE TITLE
File upload content-type problem

### ISSUE THREAD

**Issue by zalew** [taverntesting/tavern#180]
Hello, 
Looks like the file content type gets lost during upload. Fount only this issues about content-type problems https://github.com/taverntesting/tavern/issues/93 marked as fixed.

```
tavern==0.17.2
pytest==3.7.2
requests==2.19.1
```

Tavern:
```
  - name: upload
    request:
      url: "{tavern.env_vars.SERVER_URL}/my-django-app/"
      method: POST
      headers:
        Authorization: "Token {authtoken:s}"
      files:
        video_file: files/files/SampleVideo_640x360_1mb.mp4
```
Django fragment:
```
video_file = request.FILES.get('video_file')
extension # mp4
video_file.content_type # None
```
API works, only Tavern upload doesn't pass. 

What could be the problem?
Thank you in advance for you help.
