### ISSUE TITLE
Content-Type header is not passed

### ISSUE THREAD

**Issue by talonx** [taverntesting/tavern#185]
--snipped--
```
stages:
- name: Request
  request:
    url: ....snipped....
    method: PUT
    files:
      data: "post-data.txt"
    auth:
    - "{tavern.env_vars.username}"
    - "{tavern.env_vars.password}"
    headers:
      content-type: "application/json"
  response:
    status_code: 200
```
The server complains that it's getting the content-type as "multipart/form-data" even though I have explicitly set it to application/json. The txt file being passed has json.

I would expect this to work the way it works in curl, when I can set the content-type as well as pass a file as the request body.

Tavern 0.18.1 with Python 2.7.15rc1
