### ISSUE TITLE
BadSchemaError: Error at /stages/2/request/json - expected a list or dict

### ISSUE THREAD

**Issue by bcarpio** [taverntesting/tavern#189]
So I have a simple workflow in-which I perform a GET, save the json response from the get and send it to a function in utils.py to update a few fields and then I want to send it back to another endpoint with a POST but I get this error "expected a list or dict", but I'm sending a dict. 

```
  - name: Get SNOW Ticket Number
    request:
      url: "http://www.example-api.com/"
      method: GET
      headers:
        content-type: application/json
    response:
      status_code: 200
      body:
        success: True
      save:
        $ext:
          function: utils:update_change_ticket`
```

All my update_change_ticket function does is remove and update a few fields:

```
def update_change_ticket(response):
    ticket_json = response.json()['data']['change_ticket'][0]
    ticket_json['state'] = "-2"
    ticket_json['cmdb_ci'] = "REP"
    del ticket_json['sys_id']
    with open('data.json', 'w') as outfile:
        json.dump(ticket_json, outfile)

    return {"ticket_json": ticket_json}
```

My understanding from the docs is that {ticket_json} is now available as a variable:

So I try and pass it back in the next step:

```
 - name: Update SNOW Ticket State To Scheduled
    request:
      url: http://www.example-api.com/
      json: "{ticket_json}"
      method: POST
```

And this generates my error, can a variable like this not be passed to the body of the POST? I'm probably doing something wrong but this is how I gather it works from the docs.

**Comment by michaelboulton** [comment]
At the moment, format variables can only be a single value, eg if your JSON is 
```json
{"a": 2, "b": 3}
```
Your second test would need to contain
```yaml
request:
  json:
    a: "{ticket_json.a}"
    b: "{ticket_json.b}"
```
It would be useful if entire blocks could be swapped in and out , especially generalising it more so that lists could be used as well, or just preserving variable types more easily between stages (eg, avoid having to use `!int`). This was sort of raised in https://github.com/taverntesting/tavern/issues/184 and https://github.com/taverntesting/tavern/issues/84#issuecomment-398709340 , essentially we want to be able to save a whole block of json into a value and be able to refere to it by name again later.

I'm not sure how it would be implemented though, would probably require some extra magic yaml tags which wouldn't be nice - I'll makea ticket anyway so at least it can be kept in mind
