### ISSUE TITLE
Check if a field in the response is None

### ISSUE THREAD

**Issue by StefanUPB** [taverntesting/tavern#193]
In my json response I have a field "error_msg" which should be set to `None` (`None` type, not string). How can I check that it's set correctly?

**Comment by michaelboulton** [comment]
If you set the response to `null` (the YAML equivalent of `None`) it should work, ie:

```yaml
response:
  json:
    error_msg: null
```
