### ISSUE TITLE
Calling external function to generate signature to the request header.

### ISSUE THREAD

**Issue by zurek11** [taverntesting/tavern#194]
Hello. I would like to call some function which will collect request url and body and generate signature (some hash from that two parameters) and will save it to the header. Is something like this possible? I am trying to accomplish this issue for three days. Thank you.

**Comment by KPilnacek** [comment]
Hello,

from what you write I guess you are trying to invoke a custom save function on a response. And then use its result in next request.

I'd try this:
```yaml
- name: Get body
  request:
    url: http://www.example.com/get_body
  response:
    save:
      $ext:
        function: utils:the_hash_function
        extra_kwargs:
          url: http://www.example.com/get_body

- name: Use header
  request:
    url: http://www.example.com/use_header
    headers:
      hash_header: "{result_of_the_hash_function}"
```

and in `utils.py`
```python
def the_hash_function(response: requests.Response, url: str) -> Dict[str, str]:
    body = response.json()
    return {"result_of_the_hash_function": custom_hash(body, url)}
```

If this is not your case, please provide some more information (and a code snippet if possible).

With regards
Krystof

**Comment by zurek11** [comment]
Also I found out that `hash_header: "{result_of_the_hash_function}"` is not working because of this error:  `Failed to resolve string [{result_of_the_hash_function}] with variables [and here are listed all variables]`

**Comment by michaelboulton** [comment]
There isn't really a nice way to do this at the moment because after the stage has been generated the only thing that can affect values is using a fixture or formatting a value. You can use this (very hacky) way to do it if you really need it but then you need to ship the python file along with your tests, you can't read from the global configuration, etc.

```python
# conftest.py
import pytest

@pytest.fixture
def first_thing():
  return "abc"

@pytest.fixture
def second_thing():
  return "123"

@pytest.fixture
def hash_values(first_thing, second_thing):
  return hash(first_thing, second_thing)
```
```yaml
# test_hash.tavern.yaml
---
...
request:
  json:
    a: "{first_thing}"
    b: "{second_thing}"
    hash: "{hash_values}"
```
