### ISSUE TITLE
mark [skipif] does not work if tavern-global-cfg is set in init file

### ISSUE THREAD

**Issue by zurek11** [taverntesting/tavern#195]
**I am trying to run test (pytest command):**

```
test_name: GET /s

marks:
  - skipif: "'bowa' not in '{fiskal}'"

stages:
  - name: Make sure, that server status is working without any error code text.

    request:
      url: "{protocol:s}://{host:s}:{port:d}/s"
      method: GET

    response:
      status_code: 200
      body:
        code: 0
```

**config.yaml [global configuration file]:**

```
name: Global variables for testing server

description: Server specific information

variables:
  protocol: http
  host: 192.168.1.140
  port: 8888
  fiskal: bowa
```

**tox.ini:**
```
[pytest]
addopts =
    -p no:warnings
tavern-global-cfg =
    test/config.yaml

[tox]
envlist = py{36}
minversion = 3.4.0

[testenv]
deps =
    pytest
    tavern
commands = pytest

```

ERROR:
`Failed to resolve string ['bowa' not in '{fiskal}'] with variables [{}]`
