### ISSUE TITLE
how can we pass the value at runtime using external functions ?

### ISSUE THREAD

**Issue by gbhangale416** [taverntesting/tavern#209]
###############until.py###############
```python
 def read_mail():
    return verificationCode = 1323213298
```

#####################################

```yaml
 - name: Step_01_07_VerifySetupCodefromMail
    request:
      url: "{host:s}/{service.endPoint:s}/{uid:s}/validate"
      json:
        userName: "{tenatntInfo.setupAdmin:s}"
        verificationCode: 
         $ext:
           function: utils:read_mail
      method: POST
      headers:
        accept: application/json
        Cache-Control: no-cache
    response:
      status_code: 200
```
