### ISSUE TITLE
Parametrize absence of parameter

### ISSUE THREAD

**Issue by elurisoto** [taverntesting/tavern#214]
Hello,
We want to test the absence of a parameter in combination with the rest of parameters, so if we have:
```
marks:
  - parametrize:
      key: p1
      vals:
        - "a"
        - "b"
  - parametrize:
      key: optional_parameter
      vals:
        - "1"
        -
``` 
The tests performed would be: 
```
{"p1":"a", "optional_parameter":"1"}`
{"p1":"b", "optional_parameter":"1"}`
{"p1":"a"}
{"p1":"b"}
```
Is it possible to perform this check in tavern? What I'm seeing happening now is:
```
{"p1":"a", "optional_parameter":"1"}
{"p1":"b", "optional_parameter":"1"}
{"p1":"a", "optional_parameter":None}
{"p1":"b", "optional_parameter":None}
```

Thanks in advance.

**Comment by michaelboulton** [comment]
This isn't possible, you will need to create two separate tests (one with the parameter and one without). If it was possible, then `optional_parameter` being missing would raise a `MissingKeysError` when validating the test, assuming you are doing something like this:

```yaml
request:
  params:
    header_1: "{p1}"
    header_2: "{optional_parameter}"
```
