### ISSUE TITLE
Possibility of print/output the response of external function return objects support in console

### ISSUE THREAD

**Issue by kvenkat88** [taverntesting/tavern#219]
Is there any possibility to include the support of including the print statements in the .yaml test files. It would be good for interpretation. For example,

```yaml
stages:
  - name: Launch /posts API endpoint 
    request:
      url: "{server_url:s}"
      method: GET
    response:
      status_code: 200
      body:
        $ext:
          function: eva_ask_test.test_utilities.helpers:json_validator #Have to print the output of this one
```
