### ISSUE TITLE
Not able to use retry (max_retries) mechanism!

### ISSUE THREAD

**Issue by rohan-kalia** [taverntesting/tavern#222]
We are trying to use max_retries but to no avail. PFB the request we're sending along with max_retries:

```yaml
- name: Post e-number
    max_retries: 4
    request:
      url: https://domain/e-number/request
      json:
        ewbn: "890989887847584768476898002"
        


      method: POST
      headers:
        Authorization: "Bearer {latestjwt}"

    response:
      status_code: 200
      body:
        enum_id: !anything
      save:
        body:
          requestenum: requestId


    delay_after: 25
```

And we are getting error like:

```
core.py                    164 ERROR    [u"Key 'max_retries' was not defined. Path: '/stages/1'", u"Key 'max_retries' was not defined. Path: '/stages/2'"]
files.py                    45 ERROR    Error validating /tmp/tmp4N7SRn.yaml
```
