### ISSUE TITLE
Magic Numbers Do Not Work With MQTT

### ISSUE THREAD

**Issue by KenStorey** [taverntesting/tavern#226]
platform linux2 -- Python 2.7.12, pytest-4.0.2, py-1.7.0, pluggy-0.8.0
rootdir: /home/Shared/Python_Tests, inifile:
plugins: tavern-0.22.1

In the  example below a request is sent to a keyboard controller to activate key 7 which responds by echoing the requested key along with a UTC time. At this point I don't care what that time is, just that it exists.

```
  - name: Step 1 - Key press

    mqtt_publish:
      topic: dcpsim/keypress
      json:
        key_id: 7

    mqtt_response:
      topic: dcp/keypressed
      json:
        key_id: 7
        time: !anyint
      timeout: 5
```

However, the "!anyint" does not work, but produces an error:

```
E   TestFailError: Test 'Step 1 - Key press' failed:
    - Expected '{'key_id': 7, 'time': <tavern.util.loader.IntSentinel object at 0x7f9bb96f2410>}' on topic 'dcp/keypressed' but no such message received
```
