### ISSUE TITLE
How to use external function in Request section

### ISSUE THREAD

**Issue by mahadi087** [taverntesting/tavern#229]
We need to pass TOTP code for login. As a result, we need to generate TOTP by external function before making the POST request. Tried it by both fixtures and external function. But none of them succeeded.

### FIXTURES
1. Fixtures YAML

```
# test_login.tavern.yaml
test_name: Authentication_Test

marks:
  - usefixtures:
      - otp_generator

stages:
  - name: Login
    request:
      method: POST
      url: "{REQUEST_URL}/login"
      json:
        username: "{USER_NAME}"
        password: "{PASSWORD}"
        passcode: "{otp_generator}"
    response:
      status_code: 200
```
2. Fixture Py
```
# utils_fixtures.py
import pytest, pyotp

@pytest.fixture
def otp_generator():
    totp = pyotp.TOTP("ABC...............XYZ")
    passcode = totp.now()
    return passcode
```
3. It failed with:
```
E       fixture 'tavern_testing.utils_fixtures.otp_generator' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_xml_attribute, record_xml_property, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
```

### External function
1. External function YAML
```
# test_login.tavern.yaml
test_name: Authentication_Test

stages:
  - name: Login - Validate
    request:
      method: POST
      url: "{REQUEST_URL}/login"
      json:
        username: "{USER_NAME}"
        password: "{PASSWORD}"
        passcode: 
          $ext:
           function: tavern_testing.utils_external:otp_generator
    response:
      status_code: 200
```
2. External function 
```
#utils_external.py
import pyotp
def otp_generator():
    totp = pyotp.TOTP("ABC.............XYZ")
    passcode = totp.now()
    print('passcode: ', passcode)
    return passcode
```
3.  It failed with:
```
E           tavern.util.exceptions.TestFailError: Test 'Login' failed:
E           - Status code was 400, expected 200:
E               {"errCode": "API_REQUEST_DECODING_ERROR"}
```
