### ISSUE TITLE
[Feature Request] Extend "Skip" at Stage Level to Allow "Skipif" Functionality

### ISSUE THREAD

**Issue by KenStorey** [taverntesting/tavern#231]
It would be useful to selectively execute/ignore a single stage.

Consider the following scenario:

```
---

test_name: Display Line

marks:
  - parametrize:
      key: button
      vals: ["9", "1", "1", "CALL"]

paho-mqtt: *mqtt_spec

stages:

  - name: Step 1 - Enter Digits

    mqtt_publish:
      topic: dialpad/keypress
      json:
        keypress: "{button}"

    mqtt_response:
      topic: dialpad/keypressed
      json:
        keypressed: "{button}"
      timeout: 5

  - name: Step 2 - Dial Number

    mqtt_response:
      topic: dialer/call
      json:
        dialed_number: "911"
      timeout: 5

```
In Step 1 the user presses a number of keys which are echoed back. In step 2 the completed input is sent for processing.

As it stands, Step 2 will be evaluated (and fail) for each keypress. However, if it were possible to add the line _skipif: '"{button}" != "CALL"'_, then Step 2 would only be evaluated at the end and all is good.

Since the 'skip' keyword, as already available at the stage level, has a boolean qualifier the simplest way to achieve this would be to eval() that which would allow valid expressions to be used without breaking any legacy scripts.

**Comment by michaelboulton** [comment]
I don't know about putting an eval() anywhere in there because it opens some security holes. For example if your test is like this
```yaml
...
skipif: "{my_test_var}"
```
where `my_test_var` is from a previous test response, then somebody could send back `'import os; os.remove("/")'` from the server.

As for the example - the 'parametrize' mark is intended for generating different tests with different data, not repeating a test stage. In your example, it will generate 4 _separate_ tests which are interdependent. If somebody further down the line comes and tries to run the tests in parallel with pytest-xdist, or if the order that those tests are generated internally by Tavern changes, those tests might be run out of order and you will have nondeterministic test failures.

It is a bit messy, but a better way to do it in Tavern would be

```yaml
stages:
  - name: enter first digit
    mqtt_publish: &pubkey
      topic: dialpad/keypress
      json:
        keypress: 9
    mqtt_response: &respkey
      topic: dialpad/keypressed
      json:
        keypressed: 9
      timeout: 5

  - name: enter second digit
    mqtt_publish:
      <<: *pubkey
      json:
        keypress: 1
    mqtt_response:
      <<: *respkey
      json:
        keypressed: 1

  - name: enter third digit
    mqtt_publish:
      <<: *pubkey
      json:
        keypress: 1
    mqtt_response:
      <<: *respkey
      json:
        keypressed: 1


  - name: Step 2 - Dial Number
    mqtt_response:
      topic: dialer/call
      json:
        dialed_number: "911"
      timeout: 5
```
