### ISSUE TITLE
Problem with multipart form data request.

### ISSUE THREAD

**Issue by mahadi087** [taverntesting/tavern#233]
Hello guys,

I am finding it as a blocker just to make a successful multipart form data request. Here it is request and response details from the browser: 
![2019-01-11_1527](https://user-images.githubusercontent.com/747764/51039845-70ab0c80-15b6-11e9-9357-a65b1ed68130.png)

1. I tried by followings but failed:
```
name: File Test
    request:
      url: "{REQUEST_URL}/upload"
      method: POST
      data:
        fileName: 5MB.zip
      headers:
        cookie: "{COOKIE}"
    response:
      status_code: 200
```
It failed with errror:
> the request doesn't contain a multipart/form-data or multipart/mixed stream, content type header is application/json

2. Then tried again by setting the proper content type:
```
name: File Test
    request:
      url: "{REQUEST_URL}/upload"
      method: POST
      data:
        fileName: 5MB.zip
      headers:
        content-type: multipart/form-data
        cookie: "{COOKIE}"
    response:
      status_code: 200
```
It failed with errror:
> the request was rejected because no multipart boundary was found

3. Tried also by adding empty files:
```
name: File Test
    request:
      url: "{REQUEST_URL}/upload"
      method: POST
      data:
        fileName: 5MB.zip
      headers:
        content-type: multipart/form-data
        cookie: "{COOKIE}"
     files:
        file: "data/5MB.zip"
    response:
      status_code: 200
```
It failed with errror:
> E   tavern.util.exceptions.BadSchemaError: Tried to send non-file content alongside a file
