### ISSUE TITLE
Bug with parametrize and typetokens (possibly only with MQTT)

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#235]
This test will cause multiple bad schema errors:

```yaml

---

marks:
  - parametrize:
      key: sqos
      vals:
        - 0
        - 1
        - 2

test_name: Test different subscription qos

includes:
  - !include common.yaml

paho-mqtt: *mqtt_spec

stages:
  - name: step 1 - ping/pong
    mqtt_publish:
      topic: /device/123/ping
    mqtt_response:
      topic: /device/123/pong
      timeout: 5
      qos: !int "{sqos}"
```
