### ISSUE TITLE
possible bug with PASSED percentage value

### ISSUE THREAD

**Issue by zevaverbach** [taverntesting/tavern#237]
I've validated with Postman that this test works, and I'm getting `PASSED` from tavern, but with `[ 50%]` displayed after that.  Is this a bug?

```
test_name: The api.io endpoint returns transcripts.

stages:

  - name: login
    request:
      url: "{tavern.env_vars.TRANSCRIPTS_AUTH_TOKEN_URL}"
      auth:
        - "{tavern.env_vars.TEST_USERNAME}"
        - "{tavern.env_vars.TEST_PASSWORD}"
      method: POST
    response:
      status_code: 200
      headers:
        content-type: application/json
      save:
        body:
          test_login_token: token

  - name: Transcript is returned with ID
    request:
      url: "{tavern.env_vars.TRANSCRIPTS_URL}/XXXX/"
      auth:
        - "{test_login_token}"
        - None
      method: GET
    response:
      status_code: 200
      body:
        name: FSF_Philly_pt2_G2.doc

  - name: Forbidden returned for wrong user.
    request:
      url: "{tavern.env_vars.TRANSCRIPTS_URL}/YYYY/"
      auth:
        - "{test_login_token}"
        - None
      method: GET
    response:
      status_code: 403

  - name: 204 returned for nonexistent transcript ID.
    request:
      url: "{tavern.env_vars.TRANSCRIPTS_URL}/42/"
      auth:
        - "{test_login_token}"
        - None
      method: GET
    response:
      status_code: 204
```

I'm thinking it's a bug because that `50%` is displayed even when I comment out various stages.
