### ISSUE TITLE
Testing value in nested list

### ISSUE THREAD

**Issue by Cattes** [taverntesting/tavern#238]
Hello,
I really enjoy your testing framework. I am relatively new to API writing and was excited to implement tests after only a short time reading your tavern examples.
I got a problem though testing for a specific value in a nested dictionary(list(dictionary))
my API returns a large json object (~5k lines) of the structure

`{"data":[{"key1":1,"key12":"STRING","key13":{"key131":null,..}, ...},{"key2":2, "key22":"STRING", ... }] "metadata":{"mkey1":"val1"...}`

Now I wanted to test if the value of `key12`  contrains the `"STRING"` or not.
so I wrote the test as I already did for other simpler API outputs. I just gave the key structure and exprected it to work as for the simple `key:value` test you described in the introductory examples.

```
response:
  status_code: 200
  body:
    data:
      -
        key12: "STRING"
```
but sadly i get an error as the response with the notification that the returned dict does not match the one specified by me

the error message says
```
expected["data"] = '[{'key12': 'STRING'}]' (type = <class 'list'>), actual["data"] = '[{'key1': 1, 'key12': 'STRING',"key13":{"key131":null, ...
```
So the test does not check only the `key12` value as I expected, but it checked the whole dict described in the `body` of `response` matches the whole dict returned by the api. 

This was quite suprising to me since I already wrote other tests where the api returned a simple dictionary with key:value pairs and I selected a random key and checked for the value and it all worked fine but with the more complex data structure the test is now comparing the literal dictionary setup and not only the value of my key12 ...

If this question is already answered somewehre I'm  sorry for asking it again but I couldn't find it.

I also tried to write an external function that processes the returned dictionary and asseses the value of `key12` but I was not able to get the connection with pytest yet.

**Comment by michaelboulton** [comment]
If you run this test with `strict: false` (see the [documentation](https://taverntesting.github.io/documentation.html#strict-key-checking) ) this test should pass.

Testing nested keys/lists works a bit to matching things on the top level due to some legacy behaviour - see discussion on : https://github.com/taverntesting/tavern/pull/162#issuecomment-414304895

**Comment by Cattes** [comment]
Sadly I already tried that and I get a BadSchemaError when I try 

``` yaml
test_name: Name for the Test

stages:
  - name: Name for the Stage
    request:
      url: http://localhost:
      method: GET
      headers:
        content-type: application/json
  response:
    status_code: 200
    strict: False
    body:
      data:
        -
          key12: "STRING"
```
or 
``` yaml
test_name: Name for the Test

strict: False

stages:
  - name: Name for the Stage
    request:
      url: http://localhost:
      method: GET
      headers:
        content-type: application/json
  response:
    status_code: 200

    body:
      data:
        -
          key12: "STRING"
```
when I run pipenv run pytest -v

**Comment by varayal** [comment]
Did you find any solution on this?

I raised a similar issue.

**Comment by jasonamclean** [comment]
I am also hoping for a solution to get this working as well simply by using `strict: False` currently using it the exact same way but it's not working how desired. In the meantime I implemented with:
```body:
        success: !anything```

**Comment by jasonamclean** [comment]
I am also hoping for a solution to get this working as well simply by using `strict: False` currently using it the exact same way but it's not working how desired. In the meantime I implemented with:

```
body:
  success: !anything
```
but what I'd prefer to be implementing is:

```
response:
  strict: False
  status_code: 200
  headers:
    content-type: application/json; charset=UTF-8
  body:
    success:
      - dsid: "113"
        report_type: "19"
```
There are more values in this list but I don't care about validating on them, only those two values, `dsid` & `report_type`
