### ISSUE TITLE
Getting requests.exceptions.InvalidHeader:

### ISSUE THREAD

**Issue by sridharaiyer** [taverntesting/tavern#24]
In my test.tavern.yaml file

```
  - name: Make sure signature is returned
    request:
      url: "{signature_url:s}"
      method: PUT
      headers:
        content-type: application/json
        content: {"ppddCode": "11","LIN": "123456789","correlationID":"{correlationId:s}","bodyTypeCode":"utv"}
        token: "{sessionToken:s}"
    response:
      status_code: 200
      save:
        body:
          signature: signature
```
I get the following error response:

```
E           requests.exceptions.InvalidHeader: Value for header {content: {'ppddCode': '11', 'LIN': '123456789', 'correlationID': '99019c36-4f49-4be8-815c-9ff5cbcc14ff', 'bodyTypeCode': 'utv'}} must be of type str or bytes, not <class 'dict'>

venv/lib/python3.6/site-packages/requests/utils.py:872: InvalidHeader
```
How to convert my 'content' in my header to a dict? Or any other solution?

**Comment by michaelboulton** [comment]
Are you definitely intending to send the content in a header and not in the body? If you're trying to send it in the body your test should be like this instead

```
  - name: Make sure signature is returned
    request:
      url: "{signature_url:s}"
      method: PUT
      headers:
        content-type: application/json
        token: "{sessionToken:s}"
      json: {"ppddCode": "11","LIN": "123456789","correlationID":"{correlationId:s}","bodyTypeCode":"utv"}
```

If you are trying to send it in the header, that's not currently supported - Tavern will only accept strings in the headers for the time being. It's not a common enough use case that we want to modify the library and possibly introduce other undesirable behaviour at the same time.
