### ISSUE TITLE
Change loading configs to catch multiple documents error

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#245]
Loading global/local config files should only expect one document per file and should raise an error if there is more than one document

eg 

```yaml
# cfg.yaml
---
variables:
  a: 1
---
variables:
  b: 1
```
