### ISSUE TITLE
Selecting session cookie not working OK when multiple cookies are returned

### ISSUE THREAD

**Issue by pschmidtke** [taverntesting/tavern#257]
Hi,

I have a login webservice returning two cookies as a response in the response header called "set-cookie". One is called X and the other SCISID9944 let's say. 

I have the following yaml set up and expected the authentication to work on the following webservice calls, but it doesn't as tavern seems to pass only a single cookie (and the wrong one, X) to the webservice call. 

```yaml
test_name: Login

stages:
  - name: login
    request:
      url: http://localhost:9003/login
      auth:
        - ****
        - ****
      json:
        username: ppuser
      method: POST
    response:
      status_code: 200
      cookies:
        - SCISID9944

  - name: get structure metadata/StructureMetadataByCodeGet
    request:
      method: GET
      url: http://localhost:9003/api/v2/structure/1uyd/metadata
    response:
      status_code: 200
      strict: false
```

The login works OK, the second step I get a 401 unauthorized answer. If however I set the cookie manually in the yaml Cookie: cookiestring -> then the second call works. 
I'm not sure what I'm doing wrong here. 

THanks in advance for your reply.

**Comment by michaelboulton** [comment]
The 'cookies' in the request spec currently just checks that the cookie exists, it doesn't carry it over to the next request or anything at the moment. It passing the wrong cookie to the next request is probably just some internal behaviour from requests.

**Comment by michaelboulton** [comment]
The solution to this would be to allow users to save cookies between requests and use them in the next one, eg:

```yaml
test_name: Login

stages:
  - name: login
    request:
      ...
    response:
      status_code: 200
      cookies:
        - SCISID9944
      save:
        cookies: 
          login_cookie: SCISID9944 

  - name: get structure metadata/StructureMetadataByCodeGet
    request:
      method: GET
      url: http://localhost:9003/api/v2/structure/1uyd/metadata
      cookies: login_cookie
    response:
      status_code: 200
      strict: false
```
