### ISSUE TITLE
How Can I use many functions to validate a json response?

### ISSUE THREAD

**Issue by randalb1991** [taverntesting/tavern#261]
Im trying to validate a json response with 2 external functions, but the test result is  the result of the last validation(The first result is ignored).

Im using the following code:
```yaml
stages:
  - name: stage one
    request:
      url: "endpoint"
      method: GET
      params:
        org: alo
        start_date: 20000101
        end_date: 20000101
    response:
      status_code: 200
      body:
        $ext:
            function: module.checkers.common:response_has_valid_org_name #RESULT FAIL
            extra_kwargs:
              org: "{tavern.request_vars.params.org}"
        $ext:
            function: module.checkers.common:response_has_valid_start_date #RESULT OK
            extra_kwargs:
              start_date: "{tavern.request_vars.params.start_date}"
```
