### ISSUE TITLE
How can I get an item when the json response contains a list?

### ISSUE THREAD

**Issue by randalb1991** [taverntesting/tavern#262]
With the followin json response, How Can I validate the username of the first element?

```json
[
    {
      "username": "peter"
    },
   {
     "username": "mike"  
   }
]
```

I tried using the index of the element, but it didn't work:
```yaml
response:
      status_code: 200
      body:
       0:
         username: peter
```

**Comment by randalb1991** [comment]
@benhowes Can you help me with this issue?

**Comment by Birne94** [comment]
It should work if you supply a list instead of an object for `body`:

```yaml
    response:
      status_code: 200
      body:
        - username: peter
        - username: mike

```
