### ISSUE TITLE
Parametrize (http) method.

### ISSUE THREAD

**Issue by cleder** [taverntesting/tavern#263]
I want to make sure that my API rejects certain http methods:
```
---
marks:
  - parametrize:
      key: http_method
      vals:
        - POST
        - PUT
        - DELETE
        - PATCH

test_name: No writes allowed to user endpoint

stages:
  - name: try  {http_method}
    request:
      url: http://localhost/o/user/
      method: "{http_method}"
      headers:
        content-type: application/json
        authorization: "Bearer xyz1234abcd"
    response:
      status_code: 405
```
it fails with:
```
pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:
 - Enum '{http_method}' does not exist. Path: '/stages/0/request/method'.
```

**Comment by cleder** [comment]
I ended up with:
```
---
marks:
  - usefixtures:
      - server_url
      - user

test_name: No writes allowed to user endpoint

stages:
  - name: try POST
    request:
      url: "{server_url}/o/user/"
      method: POST
      headers:
        content-type: application/json
        authorization: "Bearer {user.token}"
    response:
      status_code: 405
  - name: try PUT
    request:
      url: "{server_url}/o/user/"
      method: PUT
      headers:
        content-type: application/json
        authorization: "Bearer {user.token}"
    response:
      status_code: 405
  - name: try DELETE
    request:
      url: "{server_url}/o/user/"
      method: DELETE
      headers:
        content-type: application/json
        authorization: "Bearer {user.token}"
    response:
      status_code: 405
```
which is usable of course not quite as terse as the above
