### ISSUE TITLE
type checking

### ISSUE THREAD

**Issue by njordr** [taverntesting/tavern#264]
Hi.

I fell very ashamed to ask this question, but how I can check if a value in the response body is of a particular type?

And how can I check if a key exists, but do not care about its value?

```
- name: Check login
    request:
      url: "{service.url:s}/login"
      method: POST
      verify: False
      json:
        data:
          username: "{auth.user}"
          password: "{auth.pwd}"
      headers:
        content-type: application/json
    response:
      status_code: 200
      body:
        data:
          api_token: api_token
          valid_until: valid_until
```

for example I want to check if api_token is a string and valid_until is a number, but I cannot know their value before

also I would like to check only if valid_until exists or not

Thanks
