### ISSUE TITLE
[Feature Request] Add alternate response body check that halts and fails a test immediately

### ISSUE THREAD

**Issue by cetanu** [taverntesting/tavern#271]
Hello,

The codebase seems to have grown a lot since I last looked at it, so I'm not terribly familiar with how I'd do this.

If somebody can point me in the right direction, I can write up a PR for this.

My idea
--------
Some option in the response block which, when set, will immediately stop a test (even if there are retries remaining) if the body contains a particular content.

Example
--------
```
  - name: Querying the status returns "success"
    max_retries: 10
    delay_before: 6
    request:
      url: '{host}/status
      method: GET
    response:
      status_code: 200
      body:
        state: succeeded
      halt:
        state: failed
```

In the above example, the endpoint might return `state: in progress` for the first 5 retries, and then change to "failed". Without this theoretical `halt` keyword, tavern will continue retrying even though the result is in a known bad state.

Does that make sense?

Let me know if more details are desired.
