### ISSUE TITLE
How to use the saved variables in different stages/test case which part of  single YAML file

### ISSUE THREAD

**Issue by prasadkkl** [taverntesting/tavern#283]
Example:

My YAML  has 2 Tests as below

(KALI) [root@KALI]# cat test_coms2.tavern.yaml
```yaml
---
stages:
  - name: "inserting data for base class"
    request:
      headers:
        content-type: application/json
      json:
        createdBy: prasad
        createdDate: 14/2/2019
        mode: false
        optLockVersion: 0
        updatedBy: string
        updatedDate: string
      method: POST
      url: "http://10.143.81.192:8080/api/wIRELEsses"
    response:
      body:
        createdDate: 14/2/2019
      save:
        body:
          link_var: _links.wIRELESS.href
      status_code: 201
test_name: POST
---
stages:
  - name: "Get data for base class"
    request:
      method: GET
      url: "{link_var:s}"
    response:
      status_code: 200
test_name: GET
```

====================

ERROR
```
lib/python3.6/site-packages/future/utils/__init__.py:400:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   tavern.util.exceptions.MissingFormatError: ('link_var',)

<string>:1: MissingFormatError
-------------------------------------------------------------------------- Captured log call ---------------------------------------------------------------------------
dict_util.py                41 ERROR    Failed to resolve string [{link_var}] with variables [{'tavern': {'env_vars': {'XDG_SESSION_ID': '8614', 'HOSTNAME': 'mdffun09', 'TERM': 'xterm', 'SHELL': '/bin/bash', 'HISTSIZE': '1000', 'SSH_CLIENT': '10.143.81.192 58375 22', 'OLDPWD': '/home/prasad/taverntesting/UIV-Rest/bin', 'SSH_TTY': '/dev/pts/0', 'USER': 'root', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:', 'VIRTUAL_ENV': '/home/prasad/taverntesting/UIV-Rest', 'MAIL': '/var/spool/mail/root', 'PATH': '/home/prasad/taverntesting/UIV-Rest/bin:/usr/java/jre1.8.0_102/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin', 'PWD': '/home/prasad/taverntesting/UIV-Rest', 'JAVA_HOME': '/usr/java/jre1.8.0_102', 'LANG': 'en_US.UTF-8', 'PS1': '(UIV-Rest) [\\u@\\h \\W]\\$ ', 'HISTCONTROL': 'ignoredups', 'SHLVL': '1', 'HOME': '/root', 'LOGNAME': 'root', 'XDG_DATA_DIRS': '/root/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/', 'SSH_CONNECTION': '10.143.81.192 58375 135.250.139.109 22', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'XDG_RUNTIME_DIR': '/run/user/0', 'HISTTIMEFORMAT': '%F %T ', '_': '/home/prasad/taverntesting/UIV-Rest/bin/py.test', 'PYTEST_CURRENT_TEST': 'test_coms2.tavern.yaml::GET (call)'}}}]
dict_util.py                42 ERROR    Key(s) not found in format: ('link_var',)
------------------------------------------------- generated html file: /home/prasad/taverntesting/UIV-Rest/report.html -------------------------------------------------
================================================================== 1 failed, 1 passed in 3.18 seconds ====================================================
```
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

Query: Even if both tests are in same YAML why above error is observed?
