### ISSUE TITLE
External functions: can't find module index

### ISSUE THREAD

**Issue by francisr8** [taverntesting/tavern#287]
Hi guys, i want to save 1 thing from a json in that is filtered from a function in another python file:

```yaml
test_name:  Create appointment
stages:
  - name: test1
    request:
      url: http://localhost:5000/api/appointments/
      method: POST
      headers:
        content-type: application/json
        api-key: sample
    response:
      status_code: 200
      save:
        $ext:
          function: index:test_function
```

In the other file (in same project named index.py)

```python
def test_function(response):
    data = response
    json_str = json.dumps(data)
    resp = json.loads(json_str)
    return {"appointment": resp['appointmentId']}
```

When I run this test, this comes up
extensions.py               50 ERROR    Error importing module index
