### ISSUE TITLE
Variables not working as keys in response body for assertions

### ISSUE THREAD

**Issue by jasonamclean** [taverntesting/tavern#290]
```
response:
    strict: False
    status_code: 200
    headers:
      content-type: application/json; charset=UTF-8
    body:
      "{var1}":
        something: "{var1}"
```
My response is structured as such above, so I'd like to call the variable really anywhere in the response that I'd like. In this particular case the first call to `var1` as a key is coming back as the literal `var1` variable instead of interpreting the value of `var1` while the 2nd call to `var1` is returning the expected value of `var1`
