### ISSUE TITLE
Type tokens not working in mqtt block

### ISSUE THREAD

**Issue by cpressman** [taverntesting/tavern#293]
I used the example from the documentation (Sidenote: it uses mqtt as a label instead of paho-mqtt so it should be updated). I made the mqtt-publish and mqtt response both look for ping and it worked. If I changed the mqtt-response to !anything I get the error below. I tried the same thing with json and had the same errors.

### Code:
```yaml
# test_mqtt.tavern.yaml
---

test_name: Test mqtt message response
paho-mqtt:
  client:
    transport: tcp
    client_id: tavern-tester
  connect:
    host: 10.1.0.67
    port: 1883
    timeout: 3

stages:
  - name: step 1 - ping/pong
    mqtt_publish:
      topic: test
      payload: ping
    mqtt_response:
      topic: test
      payload: !anything
      timeout: 5
```

### Error Output (edit: removed < from before "Tavern" on top and bottom line. Was causing the line not to show up).
Got unexpected payload on topic 'test': 'ping' (expected 'Tavern YAML sentinel for anything>')
Message not received after 4 seconds
Expected 'Tavern YAML sentinel for anything>' on topic 'test' but no such message received
