### ISSUE TITLE
Passing response as the first paramater for an external function returns "fixture 'response' not found"

### ISSUE THREAD

**Issue by SBelkaid** [taverntesting/tavern#294]
I'm trying to set up an external function in a test to perform some advanced checking of the response. 

This is part of the stage I'm executing:

```
  - name: get project manholes
    request:
      url: "{service.proto:s}://{service.host:s}:{service.port:d}/api/projects/{project_1}/manholes"
      method: GET
      headers:
        content-type: application/json
        Authorization: "bearer {token.val:s}"
    response:
      status_code: 200
      body:
        $ext:
          function: test_utils:test_function
      headers:
        content-type: application/json
```

this is the function which is located in a tests/ folder in the file test_utils.py:

```
def test_function(response):
    return None
```

running the test with: `py.test test_local_server.tavern.yml tests/`

returns: 

```
  def test_function(response):
E       fixture 'response' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

```

running `pytest --fixtures .` does not show `response` as an option. 

but if I change the parameter in the function to `request` then it does pass. Even though it does not show as an option in `pytest --fixtures .`

The response from the url endpoint is a json list of objects. What am I missing here?
