### ISSUE TITLE
How to  monitor the individual name ( sub- test case) in a given test case

### ISSUE THREAD

**Issue by prasadkkl** [taverntesting/tavern#297]
Here  in below example RESTAPI Testing have 3 name/sub-categories i.e POST,GET and GET.
Currently py.test test_test.tavern.yaml -vv says only about RESTAPI Testing  PASS or FAIL.

How to  monitor the individual name ( sub- test case) level scenarios or what is pytest option display
the each "name" in Test case is passed or failed?

For example in below if POST,GET passed and PUT is failed i,e  how can we display only - name: "Update data for base class - PUT" is failed?
============================================
```yaml
test_name: "RESTAPI Testing"

stages:
  - name: "inserting data for base class - POST"
    request:
      headers:
        content-type: application/json
      json:
        createdDate: 14/2/2019
      method: POST
      url: "http://135.250.34.170:8080/api/wIRELEsses"
    response:
      body:
        createdDate: 14/2/2019
      save:
        body:
          link_var: _links.wIRELESS.href
      status_code: 201

  - name: "Get data for base class - GET"
    request:
      method: GET
      url: "{link_var}"
    response:
      status_code: 200

  - name: "Update data for base class - PUT"
    request:
      headers:
        content-type: application/json
      json:
        mode: "true"
      method: PUT
      url: "{link_var}"
    response:
      body:
        mode: "true"
      status_code: 200
```

**Comment by michaelboulton** [comment]
Each 'sub test' is actually a separate **stage** of the test, so the thing you posted is just one test which does 3 things in a row (as mentioned in the documentation https://tavern.readthedocs.io/en/latest/basics.html#anatomy-of-a-test)

What you want is to split your stages into separate tests like this

```yaml
test_name: "test post"

stages:
  - name: "inserting data for base class - POST"
    request:
      headers:
        content-type: application/json
      json:
        createdDate: 14/2/2019
      method: POST
      url: "http://135.250.34.170:8080/api/wIRELEsses"
    response:
      body:
        createdDate: 14/2/2019
      save:
        body:
          link_var: _links.wIRELESS.href
      status_code: 201
---
test_name: "test get"

stages:
  - name: "Get data for base class - GET"
    request:
      method: GET
      url: "{link_var}"
    response:
      status_code: 200
---
test_name: "test put"

stages:
  - name: "Update data for base class - PUT"
    request:
      headers:
        content-type: application/json
      json:
        mode: "true"
      method: PUT
      url: "{link_var}"
    response:
      body:
        mode: "true"
      status_code: 200
```
