### ISSUE TITLE
Can't use response in external function 

### ISSUE THREAD

**Issue by francisr8** [taverntesting/tavern#299]
Hi, I have a problem with my json in the response.

Normally it starts with { id: "1", .... }
but my json file is [{id: "1" ...}]

I need to delete my '[' & ']' but can't do this because I can't do functions on my response,

Do you know how I could do this?

**Comment by michaelboulton** [comment]
You can match lists in a response by defining the expected body as a YAML list, like this:
```yaml
    response:
      status_code: 200
      body:
          - first_item
          - second_item
```
You can match a list of objects using the same technique
```yaml
    response:
      status_code: 200
      body:
          - a: 1
            b: 2
          - a: 3
            b: 4
```
