### ISSUE TITLE
Length of returned list was different than expected - expected 1 items, got 2

### ISSUE THREAD

**Issue by varayal** [taverntesting/tavern#303]
Can anyone indicate me how can I match the first element of the array Categories -> "code: 1"

Actually, I got this error:

```

 failed:
E           - Value mismatch in body: Length of returned list was different than expected - expected 1 items, got 2 (expected["data"]["Categories"] = '[{'code': <tavern.util.loader.AnythingSentinel object at 0x1068f7a90>}]
```

The JSON is 

```
    "data": {
        "title": "hello",
        "Categories": [
            {
                "code": "1",
                "name": "iphone"
            },
            {
                "code": "2",
                "name": "iphone X"
            }
```

the tavern test is

```
    response:
      body:
        data:
          title: "hello"
          Categories:
           -
              code: "1"
```
