### ISSUE TITLE
Response body requires curly braces to be double escaped.

### ISSUE THREAD

**Issue by MichielVanderlee** [taverntesting/tavern#310]
This needs to be either fixed or at least documented

```yaml
response:
  body:
    raw_wont_work: !raw "{escape_me}"
    raw_works: !raw "{{escape_me}}"

    wont_work: "{{escape_me}}"
    works: "{{{{escape_me}}}}"
```
