### ISSUE TITLE
How to pass the arguments to fixtures

### ISSUE THREAD

**Issue by prasadkkl** [taverntesting/tavern#316]
Below are my sample YAML and contest.py files.
But can i pass argument to fixtures? So that based on argument value we can write logic inside 
fixture? if No what is the alternate work-around?

Note: Currently for each new senario i need to write new fixture function in contest.py file.

Used platform:
`'tavern': '0.22.1',Python 3.6.7, pytest-4.2.0, py-1.7.0, pluggy-0.8.1 `

YAML FILE :
```yaml
---
test_name: "REST Association"

marks:
  - usefixtures:
    - uuid_generator

stages:
  - name: "Associating data for base class"
    request:
      headers:
        content-type: application/json
      json:
        state: HI
        serviceHAS:
            - "{protocol:s}://{host}:{port}/api/{endpoint:s}/{uuid_generator}"
      method: POST
      url: "{protocol:s}://{host}:{port}/api/{subsc:s}"
    response:
       ----
       ----
```

(UIV-Rest) [root@mdffun09 UIV-Rest]# cat conftest.py
```python
# conftest.py
import pytest,json,os

@pytest.fixture
def uuid_generator():

       dest=os.getcwd()+"/inputjson/services.json"
       with open(dest, "r") as pfile:
            array=json.load(pfile)
            print(array)
            print(array["id"])
            return array["id"]
```

**Comment by michaelboulton** [comment]
What are you actually trying to achieve by passing an argument into the fixture?

There is no way to pass arguments into fixtures from a Tavern test, but depending on what you want to do then the pytest documentation https://docs.pytest.org/en/latest/example/parametrize.html#apply-indirect-on-particular-arguments but it will almost certainly have to be implemented in Python

**Comment by prasadkkl** [comment]
Actually i am trying to use fixture to read the uuid form json file.
But i have 5 different json for 5 different endpoints. In that case whether can we use single fixture function to find uuid for given endpoint referenced  from tavern yaml ?

**Comment by michaelboulton** [comment]
What you're trying to do is not possible, but there is a way of getting around it:

Define an extra mark on your tests (eg, `endpoint_1`)

```yaml
test_name: endpoint 1 test

pytest:
  marks:
    - endpoint_1
    - usefixtures:
         - read_uuid
...
---
test_name: endpoint 2 test

pytest:
  marks:
    - endpoint_2
    - usefixtures:
         - read_uuid
...
```
Looks for this mark in your fixture
```python
@pytest.fixture
def read_uuid(request):  # 'request' is a built in pytest fixture
  marks = request.node.own_markers
  mark_names = [m.name for m in marks]
  if "endpoint_1" in mark_names:
    return "uuid1"
  elif "endpoint_2" in mark_names:
    return "uuid2"
```
