### ISSUE TITLE
Possibility to trigger `delay_before` / `delay_after` only on failed tests

### ISSUE THREAD

**Issue by dirkschneemann** [taverntesting/tavern#318]
Simple example:

```
---

test_name: Service 1 reachable
stages:
  - name: Check 1
    request:
      url: http://some.service
      method: GET
    response:
      status_code: 200
    max_retries: 5
    delay_after: 10

---

test_name: Service 2 reachable
stages:
  - name: Check 2
    request:
      url: http://some.other.service
      method: GET
    response:
      status_code: 200
    max_retries: 5
    delay_after: 10

---
```
This will run the first test, wait for ten seconds, then run the second test, no matter the outcome of the first test. However, when the first test passes, I actually do not want to wait but continue with the second test right away. The `delay_after` is only in there to wait a little between retries when a test failed in order not to hammer the service when it is not responsive anyway.

Is this possible somehow? If not, I think this would be a nice feature.

**Comment by michaelboulton** [comment]
Unfortunately the only way to do this is to merge the stages of those tests into one test or to use a plugin (see https://github.com/pytest-dev/pytest/issues/2317). Each test in Tavern is just mapped directly to a Pytest test so anything that works with pytest should work with Tavern.

**Comment by ryanovas** [comment]
Jumping in on this issue, it seems incomplete to have a retry feature without the ability to do a backoff. Is there a reason that this isn't/can't be implemented?

As a workaround for people like us in the future that might find this issue here is what we did:

We are using jsonschema to test the shape of responses and have written a little utility class and use a function for each test to validate:

```
stages:
  - name: Make sure tags come back
    max_retries: 3

    # Define the request to be made...
    request:
      url: "{base_url:s}/blog/tags/"
      method: GET

    # ...and the expected response code and body
    response:
      status_code: 200
      verify_response_with:
        function: blog.integ_tests.schemas:verify_tags_shape
```

```
def verify_tags_shape(response):
	"""
	Function to verify the shape of the tags endpoint with tavern
	"""
	print('Verifying tags response with tavern...')

	expected_props = {...}

	schema = gen_obj_schema_definition(expected_props) # another one of our util functions

	check_response(response, schema=schema) # this is the workaround function
```

```
# There is currently no retry backoff param in tavern, so this is a hack to
# cause a backoff manually. The idea is that we check the response status code,
# and if it's a code that merits a retry, we sleep for our backoff time and then
# raise an error that fails the step and triggers an immediate retry from tavern.
# We don't trigger the retry here as there is no mechanism for that, the idea is
# to fail the test so tavern will retry - the trick is to sleep for a period before
# failing the test.
class RetryException(Exception):
	pass


def check_response(response, schema):
	if response.status_code in [502, 503, 504, 408]:
		time.sleep(int(os.environ.get('RETRY_BACKOFF', 5)))  # default to 5 if no env var
		raise RetryException()

	validate(instance=response.json(), schema=schema)
```

Combining this with `max_retries` does effectively create a backoff pattern, but it's kind of hacky and not really as ideal as being able to just set a backoff param next to max_retries.
