### ISSUE TITLE
BadSchemaError: Unknown filetype '/Users/xx/xx/api_test/tavern.testutils.helpers:validate_jwt'

### ISSUE THREAD

**Issue by pmneve** [taverntesting/tavern#320]
Getting that error when running this yaml:

```yaml
test_name: fetch list 
includes:
  - !include tavern.testutils.helpers:validate_jwt   < throws error here
stages:
  - name: login
    request:
      url: https://xxx.xxx.xxx.us/
      json:
        user: xxxxx
        password: xxxxx
      method: POST
      headers:
        content-type: text/html
    response:
      status_code: 200
      body:
        $ext:
          function: tavern.testutils.helpers:validate_jwt
          extra_kwargs:
            jwt_key: "token"
            key: CGQgaG7GYvTcpaQZqosLy4
            options:
              verify_signature: true
              verify_aud: false
      headers:
        content-type: application/json, text/html, */*
      save:
        body:
          test_login_token: token
```
