### ISSUE TITLE
ScannerError: mapping values are not allowed here 

### ISSUE THREAD

**Issue by pmneve** [taverntesting/tavern#326]
This yaml gives 
E ScannerError: mapping values are not allowed here 
E in "/Users/xxx/xxx/xxx/test_poc.tavern.yaml", line 3, column 9
until I remove the test_name:  line and the indents on the rest of the lines.
Yaml has suddenly become very mysterious.

I should mention that I'm stuck using Python 2.7.9

```
test_name: tavern poc

  - name: list
    request:
      url: https://xxx.xxx.xxx.us/api/v3/institutions/
      method: GET
    response:
      status_code: 200
      headers:
        content-type: application/json
      save:
        body:
          content: content
```
