### ISSUE TITLE
How to configure global parameters for utils.py

### ISSUE THREAD

**Issue by prasadkkl** [taverntesting/tavern#327]
Currently my utils.py has many DB operation function.
Here Neo4j is the Database.

Currently i am hard-coding the IP address inside each db util functions.
How can i configure through global configuration?

Example:

def assert_neo4j_read(response):

    graph = Graph("bolt://10.196.135.3:7687")  ==> IP need to be derived from global config

    Path_lists=[]
    uuid=response.json()['id']
    -----
    -----
    -----
    assert len(Path_lists) != 0,"DATA NOT PRESENT IN NEO4J"

**Comment by michaelboulton** [comment]
Can you put the IP into a configuration file (https://tavern.readthedocs.io/en/latest/basics.html#including-global-configuration-files) then pass it to the function via `extra_kwargs`, ie

```yaml

includes:
  - !include ip_config.yaml  # contains ip addresses in 'variables'

...

response:
  body:
    $ext:
      function: utils.check_database
      extra_kwargs:
        server_ip: "{ip_address}"
```
