### ISSUE TITLE
YAML loading of 'set' not behaving properly

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#329]
Noticed in https://github.com/taverntesting/tavern/issues/328#issue-425668747

If you try to send this:

```yaml
stages:
  - name: match top level
    request:
      url: "{host}/fake_dictionary"
      method: GET
      json: {a, b}
```
It will be loaded like this:
```
'request': {'url': '{host}/fake_dictionary', 'method': 'GET', 'json': {'a': None, 'b': None}}, 'response': ...
```
It should raise an error
