### ISSUE TITLE
Is there a way to force allow_redirects to be true?

### ISSUE THREAD

**Issue by pmneve** [taverntesting/tavern#336]
tavern/_plugins/rest/request.py forces allow_redirects to be false in line 247:
        ```
        logger.debug("Request args: %s", request_args)

        **request_args.update(allow_redirects=False)**

        self._request_args = request_args

```
In order to facilitate returning test database to initial state I need to be able to easily delete things that were creating during a test.  Apparently allow_redirects = False is getting in the way.

**Comment by michaelboulton** [comment]
You can get around this for the time being by specifying the status code as 302 and then saving the redirect location to query in the next test. eg:

```yaml
stages:
- name: Step 1 - make query  
  request:
    ...
  response:
    status_code: 302
    save:
      headers:
        next_redirect_location: "location"

- name: Step 2 - redirect to second bit
  request:
    url: "{next_redirect_location:s}"
    method: GET
    ...
```
