### ISSUE TITLE
'Magic' variables

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#34]
We should come up with some naming convention for 'special' variables, eg

- https://github.com/taverntesting/tavern/issues/22
- https://github.com/taverntesting/tavern/issues/4
- https://github.com/taverntesting/tavern/pull/29

Using the Box library you can return what is essentially a dictionary where things can be accessed with dot notation for formatting - this is currently only possible in external (or tavern-internal) functions. We may want more of these in future. Possible options:

- Allow any key to be returned from a response/external function, but log a warning if a key in the current test_block_config is overridden by an external function (and maybe the return value of a 'response')
- set some naming convention, for example that all ext function keys are uppercased (for #29, regex->REGEX)

Would also be useful add a 'meta'/'magic' key which has environment variables (and maybe some other magic data in future), which can be used like
```yaml
request:
  json:
    user: "{username}"
    password: "{meta.environment.password}"
```
and stop anyone from saving to the key 'meta' 

@benhowes

**Comment by WhileLoop** [comment]
When calling external functions, I suggest letting the user assign the variables in the yaml similar to how the Ansible `set_fact` module works. For example 

```# utils.py
def test_function(response):
    return {"test_user_name": response.json()["user"]["name"]}
```

```
save:
  $ext:
    function: utils:test_function
  body:
    test_user_id: user.id
``` 


Would become:
```# utils.py
def test_function(response):
    return response.json()["user"]["name"]
```

```
save:
  test_user_name
    $ext:
      function: utils:test_function
  body:
    test_user_id: user.id
``` 

Otherwise it will never be possible to use the same function multiple times for different values.
