### ISSUE TITLE
Parametrize keys in dictionary in json body

### ISSUE THREAD

**Issue by pmull** [taverntesting/tavern#340]
I want to be able to use "parametrize" with the keys in a dictionary in the json payload I want to send. 

e.g. here is my json payload and parametrize format:

```
marks:
  - parametrize:
      key:
        - key
        - value
      vals:
        - [a, b]
...
  request:
      json:
        "{key}":
          - "{value}"
```

This results in "unable to get formatted stage" error, but other times when I have tried this, the formatted stage for the "key" line looked like this:
      'a': *id001
and the request didn't work.
