### ISSUE TITLE
Recursive string interpolation

### ISSUE THREAD

**Issue by bogdanbranescu** [taverntesting/tavern#341]
I'd like to use recursive string substitution when building the name for a variable. I know this uses the limited Python formatting, but test data that depends on multiple parameters (environment, running instance, etc) is more flexibly picked up from an external file like this.

Example (imagine ENV is something coming from a function):
```
# config.yaml
---
name: Config
description: Common test information

variables:
  stage_host: https://some-stage-host.com
  production_host: https://some-production-host.com
  extra_environment_host: https://extra-environment-host.com  
```
```
test_name: Test for stage or production

includes:
- !include config.yaml

stages:
- name: Call some endpoint

  request:
    url: "{{ENV}_host}/some_endpoint"
    method: GET

  response:
    status_code: 200
```
Are there any plans to allow some form of recursive interpolation in the future (i.e. on `1.0`)? Would contributions in this area be welcome?
