### ISSUE TITLE
Save unnamed values in response

### ISSUE THREAD

**Issue by mandreyel** [taverntesting/tavern#344]
Hi!

How do I save unnamed (json) values with Tavern? E.g. I might have an endpoint returning an (random) UUID string without a known value which I'd like to use later on for other endpoint tests. E.g. (pseudocode):
```yaml
response:
  status_code: 201
  content-type: application/json
  body:
    !anystr
  save:
    my_var: ??? # save whatever is in body in `my_var`
```

Much appreciated!

**Comment by michaelboulton** [comment]
This isn't currently possible but should be possible when https://github.com/taverntesting/tavern/pull/324 is done

**Comment by michaelboulton** [comment]
Using the JMESpath selector, this can be done by using "@" as the 'save' key - for example

```yaml
...
      body: c82bfa63-fd2a-419a-8c06-21cb283fd9f7
      save:
        body:
          saved_with_at: "@"
```

Note that this only works with single values, not lists/dicts/etc
