### ISSUE TITLE
Interpolate string into !include path?

### ISSUE THREAD

**Issue by pmneve** [taverntesting/tavern#356]
Here is common.yaml:
```
---
name: Common test information
description: Information for docker content_service api

variables:
  host: "https://api{tavern.env_vars.API_TEST_SERVICE}/api"
  author_dir: "../../data/authors"
  alias_dir: "../../data/aliases"
```

When I do this:
```
---
test_name: PUT Create author with orcid (BP-5843-024) (BP-5947)
strict: False
includes:
  - !include ../../common.yaml
marks:
  - usefixtures:
      - encode_web_token
      - coyote_primary_expected
      - primary_targets

stages:
  - name: -024A POST Create Author 
    request:
      url: "{host}/v2/authors/"
      method: POST
      json: !include "{author_dir}/coyote_primary.yaml"
     headers:
        Accept: 'application/json, text/plain, */*'
        Accept-Charset: 'utf-8'
        Accept-Encoding: 'gzip, deflate, br'
        Accept-Language: 'en-US,en;q=0.9'
        Authorization: "JWT {encode_web_token}"
        case_name: "BP-5843-024A"
```

instead of this:

```
. . .
      json: !include ../../data/authors/coyote_primary.yaml
. . .
```

the interpolated path fragment is not resolved and the file not found.
I tried this:

```
. . .
      json: !include "{author_dir}"/coyote_primary.yaml
```

which threw a BadSchemaError.
Any suggestions?
