### ISSUE TITLE
question: any way to make the execution of an $ext: function dependent on the result of save comparison?

### ISSUE THREAD

**Issue by pmneve** [taverntesting/tavern#357]
"institution" is saved from the previous stage.

```
  - name: GET new institution 
    request:
      url: "https://api.dev.bdev.us/api/v2/institutions/{institution.id}/"
      method: GET
      headers:
        Accept: 'application/json, text/plain, */*'
        Accept-Encoding: 'gzip, deflate, br'
        Accept-Language: 'en-US,en;q=0.9'
        Authorization: "JWT {encode_web_token}"
        case_name: "BP-5845-002B"
    response:
      status_code: 200
      headers:
        content-type: "application/json"
      body:
        data:
          name: George
          id: "{institution.id}"
        $ext:
          function: api_helpers:db_query
          extra_kwargs:
            target: institutionsapi_institution
            method: delete
            what: ""
            id: "{institution.id}"
```
"George" is not the expected name so this will fail.  However the $ext: function still executes and, in this case, deletes the database row.   
Would rather it not do so.
