### ISSUE TITLE
Key 'variables' was not defined

### ISSUE THREAD

**Issue by SuzanaK** [taverntesting/tavern#358]
I have a very simple test but the schema validator fails on `variables` though I have copy-pasted it from the [examples](https://github.com/taverntesting/tavern/blob/master/example/components/components/auth_stage.yaml). The test fails with: 

```
pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:
 - Key 'variables' was not defined. Path: ''.: Path: '/'>
```

I'm using tavern 0.26.3 and python 3.6.

This is the test: 

```
test_name: test backend API

variables:
  url: http://localhost:5000

stages:
  - name: get a random number
    request:
      url: "{url}/api/random"
      method: GET
    response:
      status_code: 200
      body:
        randomNumber: !anyint
```
