### ISSUE TITLE
String interpolation in yaml fails in terminal but succeeds in Pycharm run configuration

### ISSUE THREAD

**Issue by pmneve** [taverntesting/tavern#363]
Here's a gotcha:

The tavern yaml:
```
---
test_name: POST Replace Primary Alias for existing author (BP-5843-010)

strict: False

includes:
  - !include ../../common.yaml

marks:
  - usefixtures:
      - encode_web_token
      - coyote_primary
      - coyote_primary_expected
      - emerson_primary
      - emerson_primary_expected
      - primary_targets

stages:
  - name: -010A POST Instantiate Author with Primary Alias
    request:
      url: "{host}/v2/authors/"
      method: POST
      json: !include ../../data/authors/coyote_primary.yaml
      headers:
        Accept: 'application/json, text/plain, */*'
        Accept-Charset: 'utf-8'
        Accept-Encoding: 'gzip, deflate, br'
        Accept-Language: 'en-US,en;q=0.9'
        Authorization: "JWT {encode_web_token}"
        case_name: "BP-5843-010A"
  
    response:
      status_code: 200
      headers:
        content-type: "application/json"
      save:
        body:
          post_010A: data
        $ext:
          function: api_helpers:check_author_id_response
          extra_kwargs:
            expected: "{coyote_primary_expected}"
            targets: "{primary_targets}"

  - name: -010B PUT Replace Primary Alias for author
    request:
      url: "{host}/v2/authors/{post_010A.id}/"
      method: PUT
      json: !include ../../data/authors/emerson_primary.yaml
      headers:
        Accept: 'application/json, text/plain, */*'
        Accept-Charset: 'utf-8'
        Accept-Encoding: 'gzip, deflate, br'
        Accept-Language: 'en-US,en;q=0.9'
        Authorization: "JWT {encode_web_token}"
        case_name: "BP-5843-010B"
  
    response:
      status_code: 200
      headers:
        content-type: "application/json"
      save:
        body:
          post_010B: data
      body:
        data:
          primary_name:
            author_id: "{{post_010A.id}}"  #########
        $ext:
          function: api_helpers:check_author_id_response
          extra_kwargs:
            expected: "{emerson_primary_expected}"
            targets: "{primary_targets}"
  ```
The error in the command window:
"Value mismatch in body: Key mismatch: (expected["data"]["primary_name"]["author_id"] = '{post_010A.id}' (type = <type 'str'>), actual["data"]["primary_name"]["author_id"] = '2c6ac21b-2faa-4754-ab37-5f8125847828' (type = <type 'unicode'>))"

The culprit is at the line marked with ########.   Pycharm seems to catch the "{{...}}" and treat them as "{...}".   On the command line it throws the error.

Moral:  be careful to test outside of your IDE before you release... (which is what I was doing)

Feel free to close this. Just wanted to expose the oops.
