### ISSUE TITLE
ERROR: not found, no name {test} in any of [], with proper name syntax

### ISSUE THREAD

**Issue by emptyopen** [taverntesting/tavern#366]
I copied the example test into a directory, and named it `test_basic.tavern.yaml`:

```
---
# Every test file has one or more tests...
test_name: Get some fake data from the JSON placeholder API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: Make sure we have the right ID

    # Define the request to be made...
    request:
      url: https://jsonplaceholder.typicode.com/posts/1
      method: GET

    # ...and the expected response code and body
    response:
      status_code: 200
      body:
        id: 1
``` 

Then on the commandline, running `tavern-ci test_basic.tavern.yaml` results in a successful test: 

![image](https://user-images.githubusercontent.com/18575100/58730019-c9314980-839f-11e9-8eaa-b66e828e0414.png)

But running any of `pytest test_basic.tavern.yaml`, `python3 -m pytest test_basic.tavern.yaml`, etc results in:

![image](https://user-images.githubusercontent.com/18575100/58730053-e2d29100-839f-11e9-8502-6ac972c9397f.png)
