### ISSUE TITLE
File uploads don't work with content-type as application/json

### ISSUE THREAD

**Issue by markcorr9** [taverntesting/tavern#370]
Hello,

I've recently started using Tavern and while trying to make a POST request with a file upload alongside a header with an Authorization token, the "content-type" is ignored. I explicitly set it to "application/json (that is the only kind of files we want to accept)," but I get a warning saying it will be ignored. My API works fine and I can also make cURL calls with that header, but Tavern doesn't allow me to.

```
request:
      url: "{tavern.env_vars.HOST_URL}/my-app/"
      method: POST
      headers:
        Authorization: "Bearer {tavern.env_vars.USER_TOKEN}"
        Content-Type: application/json
      files:
        json_file: "./example.json"
```

If unspecified, I understand that multipart-form-data is chosen by default, but why can't files be uploaded with content-type as application/json? Maybe, I'm missing something, because I'm not really an expert. Thank you, in advance.
