### ISSUE TITLE
list from dictionary passed to run() function is converted to string

### ISSUE THREAD

**Issue by allexpy** [taverntesting/tavern#371]
I am trying to pass some data from python to yaml using run() function:

from tavern.core import run

```python
blocks = ['example_1', 'example_2']
products = ['example_1', 'example_2']

for block in blocks:
    extra_cfg = dict()
    extra_cfg['variables'] = dict()
    extra_cfg['variables']['block'] = int(block.strip('\n'))
    extra_cfg['variables']['date'] = "2019-05-10"
    extra_cfg['variables']['items'] = list()
    for i, product in enumerate(products, start=1):
        data = dict()
        data['product'] = int(product.strip('\n'))
        data["quantity"] = '10'
        data["price"] = "{:.2f}".format(i * 25)
        extra_cfg['variables']['items'].append(data)
        run("test_add_nir_not_working.tavern.yaml", extra_cfg)
```

as you can see extra_cfg['variables']['items'] is a list, yaml file looks like this:

```yaml
test_name: Create 2 blocks

stages:
  - name: blocks
    request:
      url: https://dev.example.ro/companies/27/block/
      json:
        block: !int "{block:d}"
        date: "{date:s}"
        items: "{items}"
      method: POST
      headers:
        content-type: application/json
        Authorization: "Token a46be5344704ea272d8f89552ea39b6e30c648e1"
    response:
      status_code: 201
      body:
        block: !int "{block:d}"
        date: "{date:s}"
        items: "{items}"
```

My problem is that "{items}" comes as a string instead of a list as it is passed trough run() function. The function should pe ran twice since there are 2 blocks in the "blocks" list. How do i know it comes as a string? Because i'm receiving this error from the api: ERROR 

tavern.response.base:base.py:41 Status code was 400, expected 201:
{"items": {"non_field_errors": ["Expected a list of items but got type \"str\"."]}}

'items': "[{'price': '25.00', 'product': 46587, 'quantity': '10'}, {'price': '50.00', 'product': 46588, 'quantity': '10'}]"

i just want the items to look like this:
'items': [{'price': '25.00', 'product': 46587, 'quantity': '10'}, {'price': '50.00', 'product': 46588, 'quantity': '10'}]

So i'm asking how can i convert "{items}" to a list or force the run() function not to convert it to a string?
