### ISSUE TITLE
Prerequest functions 

### ISSUE THREAD

**Issue by ramennoodles20** [taverntesting/tavern#372]
I have a use case where I am loading an external .json file with some standard information, but would like to edit it depending on information I am getting in certain stages of a test. 
Is it already possible to do this or are there any plans to implement such a functionality in the future?

**Comment by ramennoodles20** [comment]
Hi @markcorr9 thank you for your response. I have been trying to find a way to get this functionality to work and have found some success using:

```
test_name: some_test

stages: 
  - name: foo
    request: 
      url: localhost:8082/mockapi
      method: POST
      verify: false
      json: 
        $ext:
          function: utils:test
          extra_kwargs: 
            some_var: "{var_saved_in_another_stage}"
        
    response: 
      status_code: 200
```

As long as the external function that you are calling returns a box python object then the JSON seems to be sending properly so far. I have not seen this in the documentation so I'm not sure how consistent it is. 

Here is me temporary external function 


```
def test(some_var):
    return {"dynamic_var": some_var,
            "foo1": "bar1",
            "foo2": "bar2",
            "foo3": "bar3"
             }
```

My plan is to load the static json file in the python function, append the necessary information and then return the updated JSON. 

Please let me know if this helps
