### ISSUE TITLE
converting variables

### ISSUE THREAD

**Issue by allexpy** [taverntesting/tavern#373]
Is there a way to call a variable without the quotes? like {data} instead of "{data}"? or is there a way to convert a string into a list in yaml? something like !list "{data}"?
I have a case where i use the run() function and i pass a dictionary with key and list values, using quotes turn the lists into strings and i need them as lists.

**Comment by ramennoodles20** [comment]
I don't know if there is any way to do this "out of the box" but you could try to create your array by using an external python function as I mentioned in issue #372.

Here is my attempt at adding an array to a request 

**#In your yaml**

```
test_name: print_test
stages: 
  - name: test_stage
    request: 
      url: http://localhost:8082
      method: POST
      json: 
      ####Here we send our array to a function instead of directly loading it####
        $ext: 
          function: utils:concatArray
          extra_kwargs: 
            arrayString: "{test_array}"
      verify: false
    response: 
      status_code: 200
```

**#In your python module**
```
def concatArray(arrayString):
    print (arrayString)
    jsonArray = json.loads(arrayString)
    elementList = []
    for element in jsonArray:
        elementList.append(element)
    
    ##object that will be sent to your api
    return {"array": elementList}
```

This will result in you sending
```
{
  "array": [
    1,
    2,
    3,
    4
  ]
}
```

The drawback of this method is that you will only be able to send the object returned by the external function. Maybe you could pass other non-list args as **kwargs and have your function add those? 

Let me know if this helps, or if you need any more help
Cheers
