### ISSUE TITLE
Marking tests throws "PytestUnknownMarkWarning" warning

### ISSUE THREAD

**Issue by icanthinkformyself** [taverntesting/tavern#386]
When you mark tests:

```
---
test_name: Get server info from slow endpoint

marks:
  - slow

stages:
  - name: Get info
    request:
      url: "{host}/get-info-slow"
      method: GET
    response:
      status_code: 200
      body:
        n_users: 2048
        n_queries: 10000

---
test_name: Get server info from fast endpoint

marks:
  - fast

stages:
  - name: Get info
    request:
      url: "{host}/get-info"
      method: GET
    response:
      status_code: 200
      body:
        n_items: 2048
        n_queries: 5
```

And run the tests with pytest like:
```
py.test -m "not slow"
```
The tests run fine, but I get a warning message:
``` 
PytestUnknownMarkWarning: Unknown pytest.mark.options - is this a typo? 
You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
```
From what I understand, pytest (from 4.5) displays this warning for undeclared/unregistered markers. More here: https://docs.pytest.org/en/latest/writing_plugins.html#registering-markers
