### ISSUE TITLE
Best practices for flask-testing setup

### ISSUE THREAD

**Issue by Birne94** [taverntesting/tavern#39]
I currently consider using tavern for testing our backend services and would appreciate some of your thoughts.

Is there any recommended way of setting up a (local) testing environment with flask? Flask itself [provides a test client](http://flask.pocoo.org/docs/0.12/testing/) which can be used in unit tests.

Since spinning up a real test server running on localhost brings other issues with it (clean shutdown, port may already be used etc.), I would like to fall back to this test client.

As far as I can tell, tavern currently only supports requests using the `requests` (+ mqtt, which is not relevant to flask) module. I suppose one could _statically_ add flask test-client support in the `taverns.plugins` module, but this seems a little bit hacky.

- Does anybody have experience in using tavern with a local flask setup, preferrably without spinning up a local server?
- Are there any plans and/or development ongoing regarding the plugin system?
- If no, is there any set of requirements or specification regarding a plugin system? If we decide to use tavern ourselves, contributing here might be of interest.

**Comment by michaelboulton** [comment]
Just to clarify about testing flask with the test client - do you basically want to run flask tests that would be something like

```python
test_client = app.test_client()
response = test_client.get("/scan", headers={"authorization": "bearer abc123"})
assert response.status_code == 200
```

but written in YAML

```yaml
request:
  url: www.example.com/scan
  method: GET
  headers:
    authorization: bearer abc123
response:
  status_code: 200
```

Like that?

**Comment by Birne94** [comment]
Yes. I want to be able to omit the `protocol://host:port` part of `request.url` and would like to pass it to the test client instead.

**Comment by Birne94** [comment]
Some more thoughts about how the test schema might look:

```yaml
test_name: test
test_request_class:
  class: tavern.plugins.flask.FlaskTestRequest
  extra_kwargs:
    flask_app: myapp.factory.app

stages:
  - name: test
    request:
      url: /users/1/
      method: GET
    response:
      status_code: 200
```

`FlaskTestRequest` takes a `Flask` app instance or an absolute import path as parameter and instantiates it. All requests are then performed using this class.

`test_request_class.class` would default to the current `RestRequest` class, which of course might need some changes to be compatible. MQTT support could be adapted in a similar way.

One might decide to allow for full urls (including protocol and host) to be performed through `requests`, but this might be an implementation detail.

**Comment by michaelboulton** [comment]
I wrote up a (rough) spec of what the plugin system is likely to look like here: https://github.com/taverntesting/tavern/issues/41 . Not sure when this will get implemented though.

The relevant parts with this is that the 'session' is probably just a context manager that yields the flask test client, the 'request' block calls `test_client.post` etc., and then most of the `RestResponse` can probably be reused for the 'verifier'. a (possible) example:

```python
# flask_tavern_plugin.py
import contextlib

@contextlib.contextmanager
def get_session(app_module):
    from tavern import import_ext_function
    app = import_ext_function(app_module)
    yield app

# etc...
```
```yaml
---
test_name: test local flask server works

plugins:
  flask:
    app_module: mymodule.server:app

stages:
  - name: post something
    flask_request:
      url: www.example.com/scan
      method: GET
      headers:
        authorization: bearer abc123
    response:
      status_code: 200
```
