### ISSUE TITLE
How to skip TCs based on status of main TC using Marking Test

### ISSUE THREAD

**Issue by prasadkkl** [taverntesting/tavern#390]
I have total 4 Test cases as below as per tavern yaml.
if  here below if TC "CREATE SINGLE OR POINT EQUIPMENT" fails i.e if it returns REST RESPONSE code other than 201 or 500 etc.  How to skip the 3 Test Cases below .ie  "GET ON POINT EQUIPMENT", "PUT ON POINT EQUIPMENT" and  "DELETE ON POINT EQUIPMENT".

 Because all these 3 Test case are using the data which created during the "CREATE SINGLE OR POINT EQUIPMENT".    Hence if first TC  fails all  others  cannot execute.
******************************************************
Environment used:
  Packages  {'pytest': '4.2.0', 'py': '1.7.0', 'pluggy': '0.8.1'}
  Platform Linux-3.10.0-693.el7.x86_64-x86_64-with-redhat-7.4-Maipo
  Plugins  {'tavern': '0.26.4', 'metadata': '1.8.0', 'html': '1.20.0'}
 Python  3.6.7
********************************************************************
Mode of Executing TCs:

   Using thje  tavren run() API to run the yaml for executing TCs.
*****************************************************************************************
```yaml
---
test_name: "CREATE SINGLE OR POINT EQUIPMENT"

stages:
  - name: "inserting data for base class"
    request:
      headers:
        content-type: application/json
      json:
        ldn: eq2
        subType: type1
      method: POST
      url: "{protocol:s}://{host}:{port}/api/equipment"
    response:
      body:
        $ext:
          function: utils:assert_neo4j_insert
          extra_kwargs:
            insert_key: "equipment"
        ldn: eq2
        subType: type1
      status_code: 201
    delay_after: 5
---
test_name: "GET ON POINT EQUIPMENT"

marks:
    - equipment
    - usefixtures:
         - uuid_generator
stages:
  - name: "Get data for base class"
    request:
      method: GET
      url: "{protocol:s}://{host}:{port}/api/equipment/{uuid_generator}"
    response:
      body:
        $ext:
          function: utils:assert_neo4j_read
      status_code: 200
    delay_after: 5
---
test_name: "PUT ON POINT EQUIPMENT"
---
test_name: "DELETE ON POINT EQUIPMENT"
```
