### ISSUE TITLE
Read in list variable for parametrize vals

### ISSUE THREAD

**Issue by sovizitiu** [taverntesting/tavern#393]
Is it possible to read in a list variable from common.yaml in order to parametrize on the values in the list? I've tried playing around with this but to no avail. Something like this:

```
marks:
  - parametrize:
      key: my_key
      vals: "{my_vals}"
```

And in common.yaml:
```
variables:
     my_vals: ["val1", "val2"]
```
