### ISSUE TITLE
pytest & tavern: BadschemaError

### ISSUE THREAD

**Issue by SandeepNV** [taverntesting/tavern#394]
Hi,
I am trying to run an yaml file that uses a function from python file. Tried to set PYTHONPATH to pwd still getting the error. Please do let me know what went wrong.

#Yaml file:
```yaml
stages:
  - name: Get preferences status

    # Define the request to be made...
    request:
      url: https://staging-2.ally.ai/api/preferences/
      headers:
        content-type: application/json
        APITOKEN: "%3t@XCzra6zW%FYEjPr2Uy3K@M4o3R2a4yzI6Y4DwlVU1L1R"
        X-CSRFToken: JVQ0uDSfdtDkxJtFJ7qxFpsctoTeEiFB
      method: GET

    # ...and the expected response code and body
    response:
      status_code: 200
      save:
        $ext:
          function: rest_utils:api_assertion
        body:
          test_slots: data.time_preferences.slots
```
```python
#rest_utils
def api_assertion(self, response):
    print(response.json())
    return {"test_slots": response.json()["data"]["time_preferences"]["slots"]}
```

Both files are in same folder and that folder path is there in PYTHONPATH

Got the following error:

E   tavern.util.exceptions.BadSchemaError: Couldn't load rest_utils:api_assertion

<string>:1: BadSchemaError
------------------------------------------------------------------------------------------ Captured log call -------------------------------------------------------------------------------------------
ERROR    tavern.schemas.extensions:extensions.py:84 Error importing module rest_utils
