### ISSUE TITLE
Save request values for validation in responses

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#4]
For example if we want to generate a random uuid from an external function and make sure it's in the response, we might want to access it using format keys like:

```yaml
request:
  body:
    $ext:
      function: uuid:uuid4
response:
  body:
    returned_uuid: "{request_values.body.uuid}"
```

**Comment by michaelboulton** [comment]
For reference, for the time being I'm getting around this particular issue by doing something like

```yaml
request:
  body:
     test_id: &test_id !uuid
response:
  body:
    returned_id: *test_id
```

where !uuid is an (undocumented) feature in Tavern that will generate a uuid4
