### ISSUE TITLE
proper plugin system

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#41]
There isn't going to be some kind of huge api for this in a first run through. This is already implemented (though hardcoded for 2 request types) in plugins.py. Assuming plugins are like pytest where you define a file called something like 'tavern_plugins.py' (loaded via setuptools entry point automatically). We do need to think of a good way for plugins to register themselves (possibly just a global variable in the file), and a particular setuptools entrypoint name (eg `tavernplug = myextension.tavern_plugin`)

file has to define 4 functions (run in this order):

- `get_session(**kwargs)` - takes any generic keyword arguments relevant to initialise the 'session'. For example, mqtt need mqtt host, port, authorization, tls settings, etc. etc. This will basically just be passed through as `get_session(**test_spec[session_name])`, where 'session_name' is a block that isn't one of the predefined ones (stages, test_name, includes). Has to return something that can be used as a context manager which will be used throughout the test.

- `get_request_type(session, request_spec, test_block_variables)` - get object with a `run()` method that actually runs the test and returns some kind of object corresponding to a response. `session`, is the session returned above (now inside context manager), `request_spec` is any of the dictionary sub-items for the request (eg for `request` this is url, headers, params. for `mqtt_publish` this is topic, payload, json.). `test_block_variables` is all the variables for using/formatting for that test.

- `get_expected(response_spec, test_block_variables)` - Get the expected result as a dictionary (in whatever format is required for the verifier). `response_spec` is any of the dictionary sub-items for the response (eg for `response` this is status_code, params, etc. for `mqtt_response` this is topic, payload, json).

- `get_verifier(session, expected_response, test_block_variables)` - get a object with a `verify(response)` method that takes the actual response and verifies it against the expected response. `session`, is the session returned above (now inside context manager). `expected_response` is the returned value from get_expected **for that particular response type** - there can be multiple responses per test, so there has to be one verifier for each response. `test_block_variables` is all the variables for using/formatting for that test.

Other things to do:

- update docs to emphasise that there is only 1 request per test stage, but 0 or more responses (for example, MQTT messages don't always expected a response, but HTTP requests always do - need some way to expose this in the plugins like `require_response_block = True`)
- Move existing request type (Requests/MQTT) into another subfolder (eg `contrib/`) and always have them available by default
- Optionally add another function like `validate_schema` which takes the request/response block and validates it. This can just be done in the `get_request_type` entrypoint so it might be redundant.
- Move 'MQTT' block (and any other plugin blocks) in test into another key like `plugins`, eg:

```yaml
test_name: Do a thing

plugins:
  mqtt:
    connect:
       host: example.com

stages:
  - name: do something
    mqtt_publish:
      ...
```

I think doing this and making it work with requests and mqtt will be fairly short work, just shuffling the files around a bit.

**Comment by michaelboulton** [comment]
Also need to be able to register certain request types/response types to certain session types. eg `mqtt_publish`->`mqtt`, `response`->`requests`, etc.

**Comment by michaelboulton** [comment]
I kind of want to add a generic 'before' and 'after' to each test stage (like is used with `delay` at the moment) but it's a breaking change to the yaml format. Not too much of an issue seeing as how recently it was added, but I think that this feature is going to break the yaml format a bit too.

With this feature we should maybe add some kind of a versioning system to the inputs, and add the generic before and after blocks.

**Comment by michaelboulton** [comment]
When we do 'register' request/response types it might be good if you can register your plugin for arbitrary request/response types. For example, a `request` block is currently handled by requests but maybe you want to write something that generates a flask, django, or falcon test client because you already have a load of utilities to check responses from those particular frameworks (or you just want to be able to test without spinning up a server). This would raise an error if 2 or more plugins tried to register for the same block.

- flask plugin would import the app, create a `app.test_client()` to make the request, parse the request block to make it, and parse the response block to verify the flask testing response
- django plugin would create `django.test.Client()`, and do the same as above
- falcon plugin would import the API object and create a `falcon.testing.TestClient(api)`, then do the same as above

Related to https://github.com/taverntesting/tavern/issues/39

**Comment by senz** [comment]
How about adding "prepare" step for a stage, that would call some external py function, passing parsed yaml to it?
Let me explain a use-case:
* if your service has some integration part, with third-party service, it is not always available to you in demo or test mode. Solution is to use mock-server, like wiremock. But it needs to be configured before it will accept requests.

Schema would look like:
```yaml
test_name: Get some fake data from the JSON placeholder API

stages:
  - name: Make sure we have the right ID
    prepare:
        $ext:
            function: wiremock.stub
            json:
               request: $request -- this should pass request from stage
               response: …
    request:
      url: https://jsonplaceholder.typicode.com/posts/1
      method: GET
    response:
      status_code: 200
      body:
        id: 1
      save:
        body:
          returned_id: id
```
