### ISSUE TITLE
Testing Raw JSON in Response Body

### ISSUE THREAD

**Issue by dgrahn** [taverntesting/tavern#411]
I have the following test, which works.

```
---
test_name: ...

stages:
  - name: ...

    request:
      url: ...
      method: GET
    
    response:
      status_code: 200
      body: { "hello": "world" }
```

I would like to write the test like this.

```
---
test_name: ...

stages:
  - name: ...

    request:
      url: ...
      method: GET
    
    response:
      status_code: 200
      body: >
        {
            "hello": "world"
        }
```

But it gives me the error.

```
2019-08-15 14:20:26,724 [ERROR]: (tavern.util.dict_util:53) Failed to resolve string [{ "hello": "world" }
```

**Comment by dgrahn** [comment]
I'm thinking that this is related to the variable expansion, but I can't find a way to bypass it.

**Comment by p-jaya** [comment]
Is there a reason why you don't just write this:

```
...
response:
  body:
    hello: world
```

?

**Comment by dgrahn** [comment]
@p-jaya Because I want to be able to copy very long responses in in raw JSON without converting them over to YAML.

I was able to make some progress. The following code gives a new error.

```
      body: >
        {
            "hello": "world"
        }
```

The new error.

```
2019-08-15 14:33:34,025 [ERROR]: (tavern.response.base:47) Value mismatch in body: Type of returned data was different than expected (expected = '{                                                                                         "hello": "world"
}
' (type = <class 'tavern.util.dict_util.format_keys.<locals>.InnerFormattedString'>), actual = '{'hello': 'world'}' (type = <class 'dict'>))
```

**Comment by Birne94** [comment]
Have you tried omitting the `>`?

This should work as expected since json is a subset of yaml:

```yaml
---
test_name: ...

stages:
  - name: ...

    request:
      url: ...
      method: GET
    
    response:
      status_code: 200
      body:
        {
            "hello": "world"
        }

```
