### ISSUE TITLE
MissingCookieError: Specifying Cookies in multistages test 

### ISSUE THREAD

**Issue by animesh-sharama** [taverntesting/tavern#418]
I was following the multistage test [document](https://tavern.readthedocs.io/en/latest/examples.html#multi-stage-tests)

I wrote test as below
```
test_name: Test
stages:
  - name: login user before sending request
    request:
      url: http://localhost:8080/api/user/login
      method: POST
      json:
        email: "test@gmail.com"
        password: "test"
      headers:
        content-type: application/json
    response:
      status_code: 200
      headers:
        content-type: application/json
      save:
        headers:
          session: Set-Cookie

  - name: Get all users
    request:
      url: http://localhost:8080/api/user/list
      method: GET
      headers:
        content-type: application/json
      cookies: ["{session:s}"]
    response:
      status_code: 200
```
We get the  MissingCookieError exception
tavern.util.exceptions.MissingCookieError: Tried to use cookies '['{session:s}']' in request but only had '{}' available

Am I incorrectly storing the cookie as ``` session: Set-Cookie ```
or is the problem in the usage ```  cookies: ["{session:s}"] ``` ?
