### ISSUE TITLE
Breaking changes in 0.29.0?

### ISSUE THREAD

**Issue by amuresia** [taverntesting/tavern#430]
I have the following test case:
```
stages:
- name: Service Status Check
  max_retries: 360
  request:
    url: "{myURL:s}"
    method: GET
    timeout: 300
    headers:
      accept: application/json
    auth:
    - "{username:s}"
    - "{password:s}"
  response:
    status_code: 200
    body:
      $ext:
        function: utils.service:availability
  delay_after: 10
```
which used to work perfectly fine until Friday (on version 0.28.0) but since version 0.29.0 and 0.30.0 were released late last week, my test started failing with the following error message:
```
10:59:15  E           tavern.util.exceptions.BadSchemaError: Unexpected keys passed to $ext: {'m', 'a', 's', 'n', '}', 'e', '{', 'u', ':', 'r'}
```
Reverting back to 0.28.0 addresses the problem.
Could you please let me know what is causing this and what is the resolution? Thank you.
