### ISSUE TITLE
Unsupported JMES path for save

### ISSUE THREAD

**Issue by calebreid** [taverntesting/tavern#432]
I have the following test case which Tavern 0.30 give a future warning about how I save data from the request:

> FutureWarning: In a future version of Tavern, selecting for values to save in nested objects will have to be done as a JMES path query 

```
stages:
  - name: Get jobs from workflow
    request:
      url: '{base_url:s}/jobs?startIndex=1&pageSize=3'
      method: GET
    response:
      status_code: 200
      save:
        body:
          workflow_job_id: 0.id
          workflow_job_name: 0.name
```

This is the format of the JSON response

```
[
  {
    "id": 4422782,
    "name": "#000002"
  },
  {
    "id": 4422800,
    "name": "Test data"
  },
  {
    "id": 4422818,
    "name": "Job name"
  }
]
```

So I have tried to follow the JMES documentation to update the save statements. This is what I have come up with, however it gives a BadSchemaError when I run it. Have I made a mistake or does Tavern not support this?

```
stages:
  - name: Get jobs from workflow
    request:
      url: '{base_url:s}/jobs?startIndex=1&pageSize=3'
      method: GET
    response:
      status_code: 200
      save:
        body:
          workflow_job_id: [0].id
          workflow_job_name: [0].name
```

Thanks for your help.

**Comment by michaelboulton** [comment]
You need to wrap the path in a string like this:
```yaml

      save:
        body:
          workflow_job_id: "[0].id"
          workflow_job_name: "[0].name"
```
Just using `[0]` opens a YAML list which is where the bad schema error is coming from.
