### ISSUE TITLE
Add !anylist operator

### ISSUE THREAD

**Issue by calebreid** [taverntesting/tavern#433]
There are cases in my testing where I want to validate that the response contains a list but I don't care what the contents of the list are.

Similar to the !anystr and !anyint operators it would be useful to have a match response that is more specific than !anything for lists.

**Comment by optio** [comment]
Would also be useful to be able to test the content of 1 list item , and indicate that there might be 1 or more similar.

```
    response:
      status_code: 200
      strict: True
      body:
        subject: !anystr
        description: !anystr
        comments:
          - title: !anystr
            content: !anystr
          - !anyitem
```
