### ISSUE TITLE
Cannot parameterize status codes

### ISSUE THREAD

**Issue by CJ-Griffin** [taverntesting/tavern#435]
I want to run a parameterized test with different values which should receive different response codes but am unable to do so:

(for example)
```
test_name: Try to parameterize status codes

marks:
  - parametrize:
      key:
        - cat_id
        - expected_code
      vals:
        - [1, 200]
        - [2, 404]

stages:

  - name: Get cat with id {cat_id} and expected code {expected_code:d}
    request:
      method: GET
      url: "{endpoint:s}/cats/{cat_id}"
      auth:
        - "username"
        - "password"
    response:
      status_code: "{expected_code:d}"

```
However, I receive the error: 
```
E   tavern.util.exceptions.BadSchemaError: status_code has to be an integer or a list of integers (got {expected_code:d})
```

(apologies if this is just a type/formatting error but I have also tried:
```
      status_code: "{expected_code}"
      status_code: {expected_code}
      status_code: {expected_code:d}
```
etc...

**Comment by michaelboulton** [comment]
This in currently unsupported, as with http methods for the reasons in https://github.com/taverntesting/tavern/issues/263#issuecomment-464319391

Just for this particular case - I would say that putting a 'positive' and a 'negative' test result in the same test is bad practice anyway, I would split it out into two separate tests (one being something like "get existing item" and the other being "trying to get nonexistent item fails")

**Comment by DerMolly** [comment]
@CJ-Griffin did you try to use `!int`? That worked for me with 1.0 at least...

```
test_name: Try to parameterize status codes

marks:
  - parametrize:
      key:
        - cat_id
        - expected_code
      vals:
        - [1, 200]
        - [2, 404]

stages:

  - name: Get cat with id {cat_id} and expected code {expected_code:d}
    request:
      method: GET
      url: "{endpoint:s}/cats/{cat_id}"
      auth:
        - "username"
        - "password"
    response:
      status_code: !int "{expected_code}"
```
