### ISSUE TITLE
Integer variable doesn't work for `timeout`

### ISSUE THREAD

**Issue by zhaoyi0113** [taverntesting/tavern#436]
I have a yaml file includes variable definition:

```
name: Common test information
description: Common data used by test cases

variables:
  url: http://localhost:8080/v2
  timeout: 30
```

when I use it I got schema error `tavern.util.exceptions.BadSchemaError: 'timeout' must be either a float/int or a 2-tuple of floats/ints - got '{timeout:d}' (type <class 'str'>)`

```
stages:
  - name: test
    request:
      url: "{url:s}/test"
      method: GET
      timeout: "{timeout:d}"
```

why doesn't integer work for `timeout` in the request?
