### ISSUE TITLE
How to use a variable in a dictionary, inside a list, inside a json?

### ISSUE THREAD

**Issue by rmorillo24** [taverntesting/tavern#45]
I'm trying to access the variable within a json response. The body contains a list of items, each with a collection :
```
response:
     status_code: 200
     body:
          results: 1
          items:
          - "u":
                "name": "CREATE_TEST_USER"
                "user_id": "{user_id}"
```
The output in server:
```
[{'u': {'user_id': '{user_id}'}]
```
The structure works fine without variables.
