### ISSUE TITLE
[Question] Is there possibility to share saved part of response from test with another test (not only stage)?

### ISSUE THREAD

**Issue by zlotedziecie** [taverntesting/tavern#450]

**Comment by JoshRodstein** [comment]
I am wondering the same thing. Assuming an answer could be derived from attempting to use a saved value/variable from one test, in a subsequent test.

**Comment by JoshRodstein** [comment]
UPDATE: achieved use of saved in variable in subsequent test by setting as envar in external function:

### save jwt token returned from auth endpoint
```
    response:
      status_code: 201
      save:
        $ext:
          function: utils:response_token
        body:
          jwt: jwt

```
### set as envar in external function
```
def response_token(response):
    print("DEBUG| " + str(response.json()))
    os.environ["JWT"] = str(response.json())
    return Box(response.json())
```
### use in subsequent test
```
  - name: Get all VPCS
    request:
      url: "{tavern.env_vars.URL}/api/vpcs"
      cookies:
        - jwt: "{tavern.env_vars.JWT}"
      method: GET
    response:
      status_code: 200
```
