### ISSUE TITLE
How to deal with square brackets in JSON payload

### ISSUE THREAD

**Issue by norbertstrzelecki** [taverntesting/tavern#451]
Hi, I try to figure out how to send JSON data that contains square brackets in other way than sending it as pure JSON format. Something like this:

```json
"key": [
          {
            "subkey1": 42.4242,
            "subkey2": "value"
          }     
        ]
```

The below format obviously doesn't work:
```
json:
    key:
        subkey1: !anything
        subkey2: value
```

If it can't be done, so is there any way to put that dynamic value in the pure JSON format above just to check if subkey exists? I mean like using `!anything` in yaml format.

Thanks!

**Comment by benhowes** [comment]
@norbertstrzelecki - just to make it clear - the square brackets represent an array/list in JSON.

In yaml, you can just plonk json in, but you can use the yaml list syntax:

```
json:
    key:
        - subkey1: !anything
          subkey2: value
```
