### ISSUE TITLE
How to test an API which requires Public key id and a pem file for authorization

### ISSUE THREAD

**Issue by anuragc1729** [taverntesting/tavern#452]
I'm trying to test an api using tavern framework. The authorization required to test the api when using python code is an api key id and a pem file (which consists of the private key) . Both of these are used to encrypt the request, and the public api key is sent in the header.

I have tried using the 'cert' tag , along with the 'Auth' tag, but the test always fails as the response from the application is : 
` {"error": {"status_code": 401, "status": "Unauthorized"}} ` , instead of 200 OK.

The yaml file is included below.

Is there a mistake in the yaml file ? And are there any other ways in tavern with which i can authorize the request using the pem file and api key ? 

Edit : Attaching the yaml file for the correct indentation

<img width="557" alt="tavern_file" src="https://user-images.githubusercontent.com/24609616/65417837-a75d4600-de18-11e9-82dc-4adccc74f238.png">

**Comment by theonlyx** [comment]
How's the API called other than tavern?

**Comment by theonlyx** [comment]
Have you tried this? 
```
    request:
      url: "{host}/userinfo"
      method: GET
      cert:
        - "/path/to/certificate"
        - "/path/to/key"
 ```
https://tavern.readthedocs.io/en/latest/http.html
