### ISSUE TITLE
[QUESTION] How can I override variables via command line?

### ISSUE THREAD

**Issue by zhaoyi0113** [taverntesting/tavern#454]
I have `tavern` test which uses a common variable for base url.

common.yaml:
```
name: Common test information
description: Common data used by test cases

variables:
  url: http://localhost:8080
```

In each test suit file, 

```
test_name: Test services API Health check

includes:
  - !include common.yaml

stages:
  - name: Make sure this service is healthy
    request:
      url: "{url:s}/health"
      method: GET
    response:
      status_code: 200
```

it works fine on local but I want to run the same test against different base url `http://localhost:8080` on my CI server. How can I do that? Can I override it via command line?
