### ISSUE TITLE
Nested lists with parametrize causing BadSchemaError

### ISSUE THREAD

**Issue by jsfehler** [taverntesting/tavern#457]
```
marks:
  - parametrize:
      key:
        - foo
        - bar
        - biz

      vals:
        -
         - c93a50-16cf7cad928-44
         - - c93a50-16cf7cad928-4e
           - c93a50-16cf7cad928-4g
         - - c93a50-16cf7cad928-4m
           - c93a50-16cf7cad928-4o

        -
         - c93a50-16cfd24f2f7-76
         - - c93a50-16cfd24f2f7-8d
           - c93a50-16cfd24f2f7-8f
         - - c93a50-16cfd24f2f7-b1
           - c93a50-16cfd24f2f7-b3
```
