### ISSUE TITLE
Having two POST requests in one test

### ISSUE THREAD

**Issue by gJohnson84** [taverntesting/tavern#459]
Hi, I'm having an issue with the following test:
```
---

test_name: it should return the correct response

includes:
  - !include ../helpers/urls.yaml

stages:
  - name: it should respond with a status code of 200
    request:
      url: "{tenants}"
      method: POST
      headers:
        content-type: application/json
      json: 
        sub_domain: ttesterson453
        user:
          email: test4@test.com
          full_name: Test Testerson
          password: test1232e
          username: ttestersonecbcvbcvbbcv

    response:
      status_code: 200
      body:
        id: !anything

  - name: it should return an id
    request:
      url: "{tenants}"
      method: POST
      headers:
        content-type: application/json
      json: 
        sub_domain: ttesterson1234
        user:
          email: test@test.com
          full_name: Test Testerson
          password: test1234
          username: ttesterson

    response:
      body:
        id: !anything
```

The `it should respond with a status code of 200` step passes, but `it should return an id` doesn't.

**BUT** if I combine the tests so the response looks like this:
```
    response:
      status_code: 200
      body:
        id: !anything
```
the test passes.

The test also passes if I add `test_name` twice.

Am I missing something in the initial example?

Thanks in advance for any help offered!

**Comment by michaelboulton** [comment]
Without knowing more about the API you're testing I don't really know why it is failing the second time, but in this case it would be better to just combine the two response checks into one, ie like your example:

```yaml
    response:
      status_code: 200
      body:
        id: !anything
```

In general if you're just trying to write 2 separate tests to make sure that

1. it returns 200
2. it returns an ID

Then it's easier to just combine them into one 'response' block - if any of them fail it will still fail the test, and if more than one condition fails it will report a list of things which caused the test to fail.
