### ISSUE TITLE
YML common stage fragments

### ISSUE THREAD

**Issue by anishmac99** [taverntesting/tavern#461]
I want to reuse a stage yml in multiple files . I am getting an error if I want to add a key in include common.yml and reuse in multiple files.   

Basically I want request and response code in a common.yml file reuse in multiple files.

**Comment by Birne94** [comment]
What kind of error do you get and what does your test case look like?

[This example from the docs](https://tavern.readthedocs.io/en/latest/basics.html#directly-including-test-data) should be what you are looking for. You can save the common parts in separate yaml/json files and include them wherever needed.

**Comment by anishmac99** [comment]
I want to do something like below:
common.yaml
```
request: &request_template
      url: 'http://127.0.0.1:8001/api/test'
      method: GET
    response:
      status_code: 200
      body:
        hello: world

```
mytest.yaml
```
test_name: sample_1
includes:
  - !include common.yaml
stages:
  - name: Make sure we have the right ID
     request:
         <<: *request_template
         response:
              status_code: 400
```
