### ISSUE TITLE
Unable to upload text file with tavern, but curl works fine

### ISSUE THREAD

**Issue by yamlCase** [taverntesting/tavern#465]
I'm attempting to upload a simple text file containing some json.  using curl, the file is uploaded fine and I get my 201 status code:
`curl -uadmin:password -X PUT http://webapp.example.com/api/users/user -T user.json`

When I try what I think is the equivalent command in tavern, I get the following error:
```
Status code was 415, expected 200:
           {"errors": [{"status": 415, "message": "Unsupported Media Type"}]}
```

Here's my tavern-ci yaml block:
```
stage: 
  - name: Create user
    request:
      method: PUT
      url: "http://webapp.example.com/api/users/user"
      auth:
        - "admin"
        - "password"    
      files:
        file: "user.json"
    response:
      status_code: 201
```
