### ISSUE TITLE
Can't compare JSON objects in an !include file to response body

### ISSUE THREAD

**Issue by kenneth-go-lp** [taverntesting/tavern#466]
I'm maintaining a list of expected results in a separate .yaml file I !include globally for all my tests and compare them to the actual response body after all test steps are done. An example is:
```
# In test_sign_in.tavern.yaml
stages:
  - name: Sign in with invalid credentials
    request:
      url: "{environment.host:s}{api_endpoints.auth:s}"
      method: POST
      json:
        email: "{environment.invalid_test_email:s}"
        password: "{environment.invalid_test_password:s}"
    response:
      status_code: 401
      body: "{error_messages.invalid_credentials}"
```

```
# In common.yaml (file I !include globally)
error_messages:
  invalid_credentials: 
    fields: null
    message: "Authentication failed"
```

Using this will give me:
`E           - Value mismatch in body: Type of returned data was different than expected (expected = '{'fields': None, 'message': 'Authentication failed'}' (type = <class 'tavern.util.dict_util.format_keys.<locals>.InnerFormattedString'>), actual = '{'message': 'Authentication failed', 'fields': None}' (type = <class 'dict'>))`

But writing the expected values into the test manually works:
```
# In test_sign_in.tavern.yaml
stages:
  - name: Sign in with invalid credentials
    request:
      url: "{environment.host:s}{api_endpoints.auth:s}"
      method: POST
      json:
        email: "{environment.invalid_test_email:s}"
        password: "{environment.invalid_test_password:s}"
    response:
      status_code: 401
      body:
        fields: null
        message: "Authentication failed" 
```
Is there any way I can take JSON objects from external sources and use them to compare things (like the response of a body) within my test?

**Comment by michaelboulton** [comment]
Using a value in a format string will convert it to a string, so the mapping with `fields`/`message` is being converted to a string in the response `body` block. This is why it is giving the error about the type not matching (string vs dict). You will have to do something like this in the test:

```yaml
body:
  fields: "{error_messages.invalid_credentials.fields}"
  message: "{error_messages.invalid_credentials.message}"
```
Or split out the error_credentials into a separate file and [include it directly](https://tavern.readthedocs.io/en/latest/basics.html#directly-including-test-data)
