### ISSUE TITLE
token as env vars for tavern api testing fails

### ISSUE THREAD

**Issue by hamedminaee** [taverntesting/tavern#474]
I am new to Tavern API Testing and I am trying to pass a token as an env var (my api is written in nodejs). Here is my code
```
test_name: POST /logs
marks:
  - post_logs
stages:
  - name: post a log entry
    request:
      url: "{host:s}:{port:d}{base_path:s}/investigate/api/{version:s}/logs"
      method: POST
      headers:
        Authorization: "Basic {tavern.env_vars.TOKEN}"
        content-type: application/json
      params:
        body:
          log: blahblahblah
    response:
      status_code: 204
```

    
My problem is I do not know where to add my token in tavern.env_vars? is it a special .env tavern file I need to add? 
right now when I run the above I get:

```
 not found in format: ("'Box' object has no attribute 'TOKEN'",)
```
