### ISSUE TITLE
How to use nested list if the list name has a dot in its name

### ISSUE THREAD

**Issue by wizardOutlaw** [taverntesting/tavern#476]
Hello I am trying to save body from my response, however my response contains a "dot" in its list variable name, in that case how do i traverse to my list. 
Example: I am trying to do something like this in my test 
```
response:
      status_code: 200
      save:
        body:
          self_link: v1.Project.self_link.href
          project_id: v1.Project.id
```
My actual response looks something like this 
```
'{'v1.Project': 
       {'datastore_link': {'href': value}, 'branches': {'href': value}, id, 'publish-events':{href:value} ..etc }
}
```
In this case how do i get access to my objects when it starts looking for 'v1' and immediately starts traversing that list?
