### ISSUE TITLE
Can't add keys to json with $ext: function

### ISSUE THREAD

**Issue by ZubAnt** [taverntesting/tavern#477]
I am create next function:

```
# tests/factory.py
import random

from datetime import datetime

from box import Box
from faker import Faker

fake = Faker('ru_RU')

def goal():
    data = {
        'name': fake.name(),
        'description': fake.text(),
        'date_start': datetime.now().isoformat(),
        'date_end': datetime.now().isoformat(),
    }
    return Box(data)

```

And try this test:

```
test_name: CRUD goal

marks:
  - usefixtures:
      - app_base_url

stages:
  - name: create goal
    request:
      url: "{app_base_url}/api/v2/goal/"
      method: POST
      headers:
        x-user-username: divanov
        content-type: application/json
      json:
        author_login: divanov
        $ext:
          function: tests.factory:goal
```
 
The request body comes into the tested application without `author_login`.

How can I additionally add fields to `json` without adding it to a function?
