### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by benhowes** [taverntesting/tavern#48]
A public docker image would be useful for getting tests running faster, as mentioned in #46. 

Let's work out how best to make a docker image which can access the test files, perhaps through a volume?

**Comment by michaelboulton** [comment]
We do this for one of the other project something like this:
```yaml
---
version: '2.1'

services:
  tavern:
    image: tavern:latest
    env_file:
      - required-env-keys.env
    volumes:
      - ./integration_tests:/integration_tests
    command:
      - --tavern-global-cfg
      - /integration_tests/local_urls.yaml
      - -p
      - no:logging
```
```shell
docker-compose build
docker-compose run tavern
```
(assuming I've already built the tavern dockerfile).

I'll make an alpine dockerfile with MQTT stuff included
