### ISSUE TITLE
Passing Environmental Variable to YAML file from command line

### ISSUE THREAD

**Issue by rasihonurolgun** [taverntesting/tavern#490]
Hello and regards to all,
Here is my situation:

First of all i'm just a beginner to test also for tavern testing. I have bunch of API's that use request and get methods. Testing them with tavern is perfectly fine.
However, now I'm testing _**"test_tavern.yaml"**_ files with Github CI and my requests need authorization. Best way to do that using **_"environmental variables"_** to secure them by masking in Github CI. 

My question is that I couldn't find any solution to pass environmental variable to my "yaml" file from bash/cmd prompt. Is there any way to do that? If so, i will try to add that command line to my gitlab_ci.yml file to pass that argument.

Secondly, i couldn't figure out how to use **_tavern.env_vars_**. I've tried to use `"!include common.yaml"` files and taking variables from that file to use in my tests. But I can't able to use tavern env vars which I really need some help about. Where are they stored , how I can see them or change them ?

I've put my **common** and **test** YAML file. So, basicly if I include my stuff it's working like that. However, since I want to use **"environmental variable"** from Gitlab CI itself, I need to pass that enviromental variable to my testing yaml file.

```
#common.yaml
name: Common test information
description: Login information for test server

variables:
  protocol: https
  host: www.server.com
  port: 1234
  user_id: myemail@gmail.com
  user_password: mypassword
  userdef_url: https/blabla..
```

```
---
test_name: im testing stuff

includes:
    - !include common.yaml

variables:
    user_id: wrong_id
stages:
      - &test_user_anchor
        name: hello
        request:
            url: "{userdef_url:s}"
            method: POST
            json: 
                username: "{user_id:s}"
                password: "{user_password:s}"
            headers:
                content-type: application/json
        response:
            status_code: 200            
            save:
                body:
                    access_token: access
```
P.S: #6  from this issue, it's been said use "--set" to set a variable in YAML file. However im getting this error as well. Maybe i'm doing something wrong ?
![image](https://user-images.githubusercontent.com/36571369/69961687-acbbc880-150c-11ea-837c-d815e5c85349.png)
