### ISSUE TITLE
How do I validate a json response with dynamic data?

### ISSUE THREAD

**Issue by erichonkanen** [taverntesting/tavern#499]
Hello, how can I validate a `POST` request that returns a json response with dynamic data?

For instance the json-api formatted response will have an `id` that is a uuid and unknown ahead of time, while other fields will have similar behavior, in addition to some fields that _will_ be known ahead of time.

Ideally I'd like to test that the fields I know ahead of time are valid, and possibly the type of the dynamic fields e.g. check that it's uuid.

Is this possible?
```
    response:
      status_code: 201
      json:
        data:
          id: <DYNAMIC UUID>
          type: "person"
          attributes:
            name: 'known name'
            assigned_tag: <DYNAMIC ASSIGNED TAG>
          relationships:
            group:
              data:
                type: "groups"
                id: "abc"
```
