### ISSUE TITLE
using run() for running tests for api tavern cannot recognize the pythonpath

### ISSUE THREAD

**Issue by hamedminaee** [taverntesting/tavern#501]
I am using tavern for api testing. Here is my simple test:

  - name: Make sure we have the right ID

```
    # Define the request to be made...
    request:
      url: "{host:s}:{port:d}/{path:s}/{version:s}/searches"
      json:
        "query": "xxxx"
        "configuration_ids": ["xxxx"]
        "type": "xxx"
      method: POST

    # ...and the expected response code and body
    response:
      status_code: 201
      save:
        $ext:
          function: utils:get_search_id
  - name: delete the created search

    # Define the request to be made...
    request:
      url: "{host:s}:{port:d}/{path:s}/{version:s}/searches/{searchId}"
      method: DELETE

    # ...and the expected response code and body
    response:
      status_code: 204

```

When I run the above like:

` PYTHONPATH=$PYTHONPATH:path to my python folder including external functions pytest .`

All works but when I run it like python3 baft.py -e local in which baft.py includes run() as follows:

`run(in_file = "", tavern_global_cfg = {"variables": tavern_cfg_variables}, pytest_args = pytest_parameters)`

I get

`E   ModuleNotFoundError: No module named 'utils'`

How can I tell python to add the path of my external functions to pythonpath then I can run my tests using the run command?
