### ISSUE TITLE
question: how to express that ordering doesn't matter?

### ISSUE THREAD

**Issue by tommyjcarpenter** [taverntesting/tavern#504]
I have a test:

```
  - name: instance list
    request:
      url: http://localhost:10000/a1-p/policytypes/1006001/policies
      method: GET
    response:
      status_code: 200
      body: [qt1, qt2]
```

how do I express that `[qt1, qt2]` OR `[qt2,qt1]` is OK? Is there an "unordered_ok" or some equivalent flag?
