### ISSUE TITLE
How to use int type in array

### ISSUE THREAD

**Issue by vit-goncharov** [taverntesting/tavern#51]
if send
```
json:
        settings: []
        agentslist:
          - '{agent_id:d}'
```
Server define agent_in type of string. for example '2'

**Comment by michaelboulton** [comment]
If you use the `!int` tag (one exclamation mark) in front of it it should work, ie:
```
json:
        settings: []
        agentslist:
          - !int '{agent_id:d}'
```
The documentation was updated a short while ago with some more information on this: https://taverntesting.github.io/documentation#type-conversions
