### ISSUE TITLE
Can't save headers for chained requests

### ISSUE THREAD

**Issue by oshabal** [taverntesting/tavern#510]
Hi there,
I am trying to do simple sign_in/sign_out test.
After sign_in I need to save few headers to use them in sign_out.
Like that:
```
    save:
      headers:
        access-token: access-token
        client: client
        uid: uid
```
But it doesn't work, I'm keep getting unclear purest warnings about wrong saving of nested data. 
When trying to do a sign_out 'm getting an errors about that variable (e.g {access-token:s} is None.
What is wrong with that?
