### ISSUE TITLE
request header

### ISSUE THREAD

**Issue by ParthVividSeats** [taverntesting/tavern#511]
Hey,

I have tests which are for same url(endpoint) , The url is valid only if there is a particular header passed with the request. 

Problem statement: Define header once and pass the value/url to requests for multiple tests/stages across a test.

Ex:
```
test_name: Test status codes

stages:
  - name: Test success /200 code

    request:
      headers:
        HEADER_ID: "10"
      url: "{tavern.env_vars.URL}/api/v1/"
      method: GET

    response:
      status_code: 200

---
test_name: Test 234

stages:
  - name: Test success/200 code

    request:
      headers:
        HEADER_ID: "10"
      url: "{tavern.env_vars.URL}/api/v1/"      
      method: GET

    response:
      status_code: 200

  - name: Test success/200 

    request:
      headers:
        HEADER_ID: "10"
      url: "{tavern.env_vars.URL}/api/v1/"
      method: GET
    
    response:
      status_code: 200

```

Is there a way I can define HEADER_ID: 10 globally and not explicitly type in for every request I make ?

**Comment by benhowes** [comment]
The best way is probably to use a global configuration file as described here: https://tavern.readthedocs.io/en/latest/basics.html#including-global-configuration-files

Then you can define the header value in that common file

**Comment by ParthVividSeats** [comment]
Hey ,
Thanks for sparing some time on the problem, However I would like to explain further to make the problem statement descriptive.

> common.yaml
> 
> name: Common test information
> 
> variables:
>   header: "Header_Value"

with this common.yaml file my requesting would still look like 

> test_name: Test status codes
> 
> stages:
>   - name: Test success /200 code
> 
>     request:
>       headers:
>         HEADER_ID: "{header}"
>       url: "{tavern.env_vars.URL}/api/v1/"
>       method: GET
> 
>     response:
>       status_code: 200


and I have to do this for all the requests that I make, what I am trying to achieve is "Not pass the header ID for every request separately and create a url once (with header) and reuse that url for all tests.

**Comment by michaelboulton** [comment]
You can do this by using a yaml anchor https://tavern.readthedocs.io/en/latest/basics.html#reusing-requests-and-yaml-fragments :

```yaml
test_name: Test status codes

stages:
  - name: Test success /200 code

    request:
      headers: &headers
        HEADER_ID: "10"
      url: "{tavern.env_vars.URL}/api/v1/"
      method: GET

    response:
      status_code: 200

---
test_name: Test 234

stages:
  - name: Test success/200 code

    request:
      headers:
        <<: *headers
      url: "{tavern.env_vars.URL}/api/v1/"      
      method: GET

    response:
      status_code: 200

  - name: Test success/200 

    request:
      headers:
        <<: *headers
      url: "{tavern.env_vars.URL}/api/v1/"
      method: GET
    
    response:
      status_code: 200
```

You can use this to reuse just the headers, or the whole request, etc.
