### ISSUE TITLE
Shared stage file can't pick-up values from a fixture

### ISSUE THREAD

**Issue by oshabal** [taverntesting/tavern#513]
When I'm trying to use a fixture in "shared stage" YAML file, it doesn't work the same way as in regular test. E.g I want to return login/pass data into shared "login_get_tokens" shared stage.
Variables are just invisible for this shared file.

```yaml
name: Authentication stage
description: Reusable test stage for authentication

marks:
  - usefixtures:
      - get_login
      - get_password

stages:
  - id: sign_in
    name: Sign in and aquire tokens
    request:
      url: "{base_url:s}{api_path:s}auth/sign_in"
      data:
        login: "{get_login:s}"
        password: "{get_password:s}"
      method: POST
    response:
      status_code: 200
      save:
        headers:
          access-token: access-token
          client: client
          uid: uid
```

ERROR    tavern.util.dict_util:dict_util.py:48 Key(s) not found in format: get_login
