### ISSUE TITLE
[Feature request]: Make parameterize tests more flexible

### ISSUE THREAD

**Issue by methsib** [taverntesting/tavern#516]
I recently started using tavern tests and i realized that it's really useful to have more flexibility to run parameterize tests.

Rather than limiting the vals to have strings or include values from an external file, it's good to allow,
`variables`, `external function` and `json data`

calling variables for values work only if they are defined. variables we save from previous tests can't be used.
Eg 1:
```yaml
---
test_name: get users
stages:
  ....
  save:
    body:
      user1_id:  users[0].id
      user2_id:  users[1].id
---
test_name: get user details
marks:
- parametrize:
    key: test_user
    vals:
    - '{user1_id}'
    - '{user1_id}'
```

Eg 2:
```yaml
marks:
- parametrize:
    key: user_id
    vals:
    - $ext:
        function: get_id_by_user_name
        extra_kwargs:
          name: 'user1'
    - $ext:
        function: get_id_by_user_name
        extra_kwargs:
          name: 'user2'
```

Eg3:
```yaml
marks:
- parametrize:
    key:
    - username
    - body
    vals:
    - - user1
      - users:
          id: 1
          name: 'user1'
          age: 25
    - - user2
      - users:
          id: 2
          name: 'user2'
          age: 30
```
