### ISSUE TITLE
Question - DRYing out my code by including parts of stage, request, or response?

### ISSUE THREAD

**Issue by yamlCase** [taverntesting/tavern#518]
my stage blocks seem to be 95% the same with just the request: url: different. Some questions:

Can I include part of a stage block?  i.e. these that are mostly always the same under `request:`

```
$ cat request_settings.yaml

verify: false
follow_redirects: true
method: GET
auth:
   - "{users.admin.login}"
   - "{users.admin.token_perm}"
```

If not, what about default values for those?

If I'm going about this the wrong way and there's some other approach I should be taking, please hit me over the head.

**Comment by michaelboulton** [comment]
You can globally set following redirects with the `--tavern-always-follow-redirects` flag, but you can also use yaml anchors to repeat more blocks of code across tests (https://tavern.readthedocs.io/en/latest/basics.html#reusing-requests-and-yaml-fragments) like this example

```yaml
---
test_name: Make sure giving premium works

stages:
  # Use the same block to log in across documents
  - *test_user_login_anchor

  - name: Assert user does not have premium
    request: &has_premium_request_anchor
      url: http://test.server.com/user_info
      method: GET
      headers:
        Authorization: "Bearer {test_user_login_token}"
    response:
      status_code: 200
      body:
        has_premium: false

  - name: Give user premium
    request:
      url: http://test.server.com/premium
      method: POST
      headers:
        Authorization: "Bearer {test_user_login_token}"
    response:
      status_code: 200

  - name: Assert user now has premium
    request:
      # Use the same block within one document
      <<: *has_premium_request_anchor
    response:
      status_code: 200
      body:
        has_premium: true
```
But this does only work within the same file.
