### ISSUE TITLE
variable's value used in another variable's value

### ISSUE THREAD

**Issue by yamlCase** [taverntesting/tavern#519]
Is there some way to have a variable's value used in another variable's value?

i.e.:

```
variables:
  hostname: www.example.com
  address: https://{hostname}
  api_url: {address}/api
```
