### ISSUE TITLE
Nested file field

### ISSUE THREAD

**Issue by ionik-dev** [taverntesting/tavern#521]
It seems unavailable to set nested field for file.
```
...
data:
    product:
        name: "Test product"
        price: 300
files:
     product:
         image: "placeholder.png"
...
```
I need to send file via product['image'] field not just image. It works for data section.
