### ISSUE TITLE
Problem with mqtt plugin, "Key 'aws-mqtt' was not defined".

### ISSUE THREAD

**Issue by burritoIand** [taverntesting/tavern#525]
Hello,

I'm trying to write a replacement mqtt plugin to use a different mqtt client instead of paho-mqtt.

I followed the documentation for plugins and have spent time reading through the existing paho-mqtt plugin etc. My plugin is structured exactly the same as the paho-mqtt package except the schema is trimmed down.

Currently I am getting the error: `Key 'aws-mqtt' was not defined`, which comes from line [L107](https://github.com/taverntesting/tavern/blob/master/tavern/schemas/files.py#L107)

After doing some inspection, I discovered that I have to run pytest with the following extra argument for it to pick up the new mqtt backend:
```
pytest --tavern-mqtt-backend aws-mqtt -k test_mqtt_health_check
```
However, it makes no difference and I receive the pykwalify error.

Here is the configuration for my project:

# setup.cfg
```
[options]
packages = find:
include_package_data = True

[options.packages.find]
exclude =
    tests

[options.entry_points]
tavern_mqtt =
    aws-mqtt = tavern_awsmqtt.plugins.mqtt.tavernhook
```

# plugins/mqtt/schema.yml
```
name: aws mqtt schema

initialisation:
  aws-mqtt:
    required: false
    type: map
    mapping:

      client:
        required: false
        type: map
        mapping:
          client_id:
            type: str
            required: false
          clean_session:
            type: bool
            required: false

      connect:
        required: true
        type: map
        mapping:
          host:
            required: true
            type: str
          keepalive:
            required: false
            type: float
          timeout:
            required: false
            type: float
```

# tests/test_mqtt_health.tavern.yml
```
---
test_name: test basic mqtt health.

aws-mqtt:
  client:
    client_id: 'test-user'
  connect:
    host: my.mqtt.endpoint
    timeout: 3

stages:
  - name: step 1 - ping/pong
    mqtt_publish:
      topic: health
      payload: ping
    mqtt_response:
      topic: health
      payload: pong
      timeout: 5
```
