### ISSUE TITLE
Invalid fixture spec causes confusing error

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#529]
example
```yaml
marks:
  usefixtures:
    thing
```
causes
```
    if isinstance(pm.mark.args[0], (list, tuple)):
E   IndexError: tuple index out of range
```
in pytesthook/item
