### ISSUE TITLE
inline json formatting causes traceback error

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#532]
example
```
Format variables:
   "id": 0  = '???'

Source test stage (line 33):
- name: do something
  request:
    method: DELETE
    url: http://example.com/thing
    json:
      { "id": 0 }

Unable to get formatted stage
```
