### ISSUE TITLE
Key(s) not found in format: <var_name> = '???' Error After upgrading to 1.0.

### ISSUE THREAD

**Issue by imkaka** [taverntesting/tavern#538]
I have recently upgraded the tavern to 1.0 but after upgrading and changing all tests compatible to 1.0.
Eg - ```body: -> json:``` in response.

Almost tests are failing with format error.

One scenerio:

1. data.yaml

```yaml
---

# Each file should have a name and description
name: User Variables
description: Varibales used for all tests for User

# Variables should just be a mapping of key: value pairs
variables:
  host: "{tavern.env_vars.TEST_API_HOST}"
  invalid_otp: 10000
  app_version: 50
  app_version_msg: "Please update to new version."
```
2. test_user.tavern.yaml
```yaml
includes:
  - !include data.yaml

test_name: "User Initialization: environment setup (/api/v1/testing/integration/)"

marks:
  - integration

stages:
  - name: Initial data setup for accounts
    request:
        url: "{host}/api/v1/testing/integration/"
        method: POST
        json:
            setup: "accounts"
        headers:
            Content-Type: application/json
    response:
        status_code: 200
        json:
            success: true
            mobile: !anyint
            otp: !anystr
        save:
            json:
                mobile: mobile
                valid_otp: otp
---

test_name: "Test User Login and Verify"

marks:
  - integration

stages:
  - name: Test for APP version check
    request:
        url: "{host}/api/v1/accounts/login/"
        method: POST
        json:
            mobile: "{mobile}"
    response:
        status_code: 400
        json:
            detail: "{app_version_msg}"
``` 
In above test first test is passing, but second test is failing with below error. 

```': 'tests/accounts/test_user.tavern.yaml::Test User Login and Verify (call)'}}}]
Key(s) not found in format: app_version_msg
  app_version_msg = '???'

Source test stage (line 35):
  - name: Test for APP version check
    request:
        url: "{host}/api/v1/accounts/login/"
        method: POST
        json:
            mobile: "{mobile}"
    response:
        status_code: 400
        json:
            detail: "{app_version_msg}"


Unable to get formatted stage

Errors:
E   tavern.util.exceptions.MissingFormatError: host
```

And all my tests follow the same conventions, I save common variables in `data.yaml`, env_vars are loaded as well.

I could not find any breaking changes regarding format in 1.0. Please address this if anyone know this error.
