### ISSUE TITLE
Fixture variable in upload_files not replaced

### ISSUE THREAD

**Issue by tblakers** [taverntesting/tavern#551]
Encountered this when upgrading from 0.30.3 to 1.0.0.

```
---
marks:
  - usefixtures:
      - generate_unique_filename

test_name: Upload a file

stages:
  - type: ref
    id: do_login

  - name: Upload a file
    request:
      url: https://{comp2_subhost}.{base_domain}/upload
      method: POST
      files:
        upload_files: 'tmp/{generate_unique_filename}'
    response:
      status_code: 200
```

The generate_unique_filename fixture returns the filename, and previously it would be replaced and upload successfully. In Tavern 1.0.0, I get this error:

```
            if not os.path.exists(file_path):
                raise BadSchemaError(
>                   "Path to file to upload '{}' was not found".format(file_path)
                )
E               tavern.util.exceptions.BadSchemaError: Path to file to upload 'tmp/{generate_unique_filename}' was not found
```

Can confirm the generate_unique_filename fixture is generating the file correctly, and that variable substitution is occurring correctly elsewhere in the request definition. Just doesn't seem to work for upload_files...
