### ISSUE TITLE
Is there a way to validate the response url?

### ISSUE THREAD

**Issue by greyarch** [taverntesting/tavern#552]
I want to check that the the response url (after redirection) is correct. Is this at all possible?

**Comment by benhowes** [comment]
The redirect is in a `Location` header, so you can test the `headers.location` for the URL you want to redirect to.

e.g.

```yaml
stages:
  - name: test a redirect
    request:
      url: "{host}/userinfo"
      method: GET
    response:
      status_code: 302
      headers:
        location: http://example.com/new_location
```
