### ISSUE TITLE
[Feature Request] define a property to enable/disable each test

### ISSUE THREAD

**Issue by skylmoro** [taverntesting/tavern#554]
It would be nice to have, for each stage, to set a field (i.e. disabled) for enabling or disabling a test:

```
stages:
  - name: test name
    disabled: true
    request:
      url: "{protocol:s}://{host:s}:{port:d}/etc/etc
      method: POST
      cookies:
```
It's useful when an API has not been fully implemented yes or a mock environment lacks of some configuration and will be added later.
