### ISSUE TITLE
Test execution exit when one of the stage in a file is failed

### ISSUE THREAD

**Issue by sbcp1993** [taverntesting/tavern#556]
Doing HTTP Integration testing using tavern, creating one test file for each endpoints. Each file have multiple stages for testing different status codes. But when one of the stage is failed the test execution will not go further. 

```
---
 test_name: test POST method

 includes:
 - !include login_stage.yaml

 stages:
  - type: ref
    id: user_login

  - name: 201
    request:
      something
    response:
      status_code: 201
     
  - name: Unauthorized 401
    request:
      something
    response:
      status_code: 401

  - name: 400 Bad request
    request:
      something
    response:
      status_code: 400

```
if 401 stage failed, 400 Bad request stage will not run. And the result will show that the entire test as failed.

 FAILED test_file.yaml: test POST method

It will be really good if the test result can show fail/pass for each stages in a test.
