### ISSUE TITLE
Setup test environment before running all tests

### ISSUE THREAD

**Issue by sbcp1993** [taverntesting/tavern#558]
I am new to tavern and python, doing integration testing for my api. I have more than 15 test files to test each endpoints. I need to create a user before running all the 15 files, so that i can use the jwt token of that user in all other files. the user creation should be done only once. If i create user in each file i get 'user already exist' error.

 Is there any method that i can use to do this?

**Comment by michaelboulton** [comment]
You should be able to do this with a pytest fixture https://docs.pytest.org/en/stable/fixture.html

If you create a file called `conftest.py` alongside your tavern tests with something like this in it

```python
import pytest

@pytest.fixture(scope="session")
def create_user():
	user = create_a_user(...)
	return user
```

Then you can use the 'user' object like this

```yaml
---

test_name: Test usefixtures

marks:
  - usefixtures:
      - create_user

stages:
  - name: Do something with user info
    request:
      url: "{host}/info"
      method: POST
      json:
        value: "{user.token}"
    ...
```

Note that you can't use a tavern test as a fixture, it has to be Python. This is a bit awkward at the moment, probably going to add support for 'autouse' fixtures

You can also just use anchors https://tavern.readthedocs.io/en/latest/basics.html#reusing-requests-and-yaml-fragments or a shared stage https://tavern.readthedocs.io/en/latest/basics.html#sharing-stages-in-configuration-files if you want to use Tavern/YAML to create the user.
