### ISSUE TITLE
`null` is not working properly on nested keys

### ISSUE THREAD

**Issue by jayrepo** [taverntesting/tavern#56]
```yml
test_name: Get some fake data from the JSON placeholder API

stages:
  - name: Verify only id
    request:
      url: https://reqres.in/api/users/1
      method: GET
    response:
      status_code: 200
      body:
        data:
          id: 1
          first_name: null
          last_name: null
          avatar: null
```
The above test failed with error:
 Value mismatch: got '{'id': 1, 'first_name': 'George', 'last_name': 'Bluth', 'avatar': 'https://s3.amazonaws.com/uifaces/faces/twitter/calebogden/128.jpg'}' (type: <class 'dict'>), expected '{'id': 1, 'first_name': None,
'last_name': None, 'avatar': None}' (type: <class 'dict'>)
