### ISSUE TITLE
Variables inside a **list** are being sent as literals. 

### ISSUE THREAD

**Issue by pco-gh** [taverntesting/tavern#563]
Variables inside a **list** are being sent as literals. 

```
stages:
  - name: Test case name
    request:
      url: http://localhost:5000/api/v1/
      json:
        - some_id: 123
          gender: Female
          $ext:
            function: tests.folder.module:generate_building_id #returns building:01
```

In the above example my json payload looks like:
```
[{
some_id:123,
gender:Female,
function: tests.folder.module:generate_building_id }]
```

Instead of
```
[{
some_id:123,
gender:Female,
building:01 }]
```
