### ISSUE TITLE
Support using custom function in request.auth

### ISSUE THREAD

**Issue by sohoffice** [taverntesting/tavern#564]
As stated in the [requests document](https://requests.readthedocs.io/en/master/user/advanced/#custom-authentication), user may pass a sub class of AuthBase as the auth parameter. This is very useful when the authentication is a little bit more complicated than passing the session token or basic auth.

I guess this can be worked around by allowing user to pass a custom function which return AuthBase subclass? Something similar to the below.

```
    request:
      auth:
        $ext:
          function: security:prepare_auth
          extra_kwargs:
            username: "{username_variable}"
```

In the `security.py`, the caller can do the below

```
from requests.auth import AuthBase

class PizzaAuth(AuthBase):
    """Attaches HTTP Pizza Authentication to the given Request object."""
    def __init__(self, username):
        # setup any auth-related data here
        self.username = username

    def __call__(self, r):
        # modify and return the request
        r.headers['X-Pizza'] = self.username
        return r

def prepare_api_auth(**kwargs):
    username = kwargs['username']
    return PizzaAuth(username)
```

I hope this makes sense ?

I do have a fix which can be submitted shortly. Let me know what you think.
