### ISSUE TITLE
cannot define an empty value in test

### ISSUE THREAD

**Issue by AlbertoBarcessat** [taverntesting/tavern#565]
Hi, I get tavern.util.exceptions.BadSchemaError: Error at yaml:28 - column 41 - cannot define an empty value in test - either give it a value or explicitly set it to None.
This is the test:
 
```yaml
  - name: test context was created
    request:
      url: "http://localhost:81/api/context?name={test_context_exists_name:s}"
      method: GET
    response:
      strict: False
      status_code: 200
      json:
        apis: 
          - name: {test_api_exists_name:s}
            version: {test_api_exists_version:s}
```

line 28 if for "apis:". It is a dictionary with a list as a value, containing dictionaries.
I use tavern 1.2.2
