### ISSUE TITLE
{n}, {m,n} not working when verify with validate_pykwalify using regexp pattern

### ISSUE THREAD

**Issue by jayrepo** [taverntesting/tavern#57]
```yml
test_name: Validating schema and data binding

stages:
  - name: Get car info
    request:
      url: https://reqres.in/api/cars/1
      method: GET
    response:
      status_code: 200
      body:
        # {  
        #   "data":{  
        #     "id":1,
        #     "name":"cerulean",
        #     "year":2000,
        #     "color":"#98B2D1",
        #     "pantone_value":"15-4020"
        #   }
        # }
        $ext:
          # http://pykwalify.readthedocs.io/en/master/
          function: tavern.testutils.helpers:validate_pykwalify
          extra_kwargs:
            schema:
              type: map
              required: True
              mapping:
                data:
                  type: map
                  required: True
                  mapping:
                    id:
                      type: int
                    name:
                      type: str
                    year:
                      type: int
                    color:
                      type: str
                      # using regexp to match hex color code, {6} not working
                      pattern: '#[A-Fa-f0-9]{6}'
                    pantone_value:
                      type: str
                      # {n} not working
                      pattern: '\d\d-\d\d\d\d'
```

error:
Traceback (most recent call last):
  File "C:\Python36\Scripts\tavern-ci-script.py", line 11, in <module>
    load_entry_point('tavern==0.6.0', 'console_scripts', 'tavern-ci')()
  File "c:\python36\lib\site-packages\tavern\entry.py", line 102, in main
    exit(not run(**vargs))
  File "c:\python36\lib\site-packages\tavern\core.py", line 167, in run
    run_test(in_file, test_spec, global_cfg)
  File "c:\python36\lib\site-packages\tavern\core.py", line 92, in run_test
    expected = get_expected(stage, test_block_config, sessions)
  File "c:\python36\lib\site-packages\tavern\plugins.py", line 125, in get_expected
    f_expected = format_keys(r_expected, test_block_config["variables"])
  File "c:\python36\lib\site-packages\tavern\util\dict_util.py", line 28, in format_keys
    formatted[key] = format_keys(val[key], variables)
  File "c:\python36\lib\site-packages\tavern\util\dict_util.py", line 28, in format_keys
    formatted[key] = format_keys(val[key], variables)
  File "c:\python36\lib\site-packages\tavern\util\dict_util.py", line 28, in format_keys
    formatted[key] = format_keys(val[key], variables)
  [Previous line repeated 5 more times]
  File "c:\python36\lib\site-packages\tavern\util\dict_util.py", line 31, in format_keys
    formatted = val.format(**variables)
IndexError: tuple index out of range
