### ISSUE TITLE
yaml.composer.ComposerError: found duplicate anchor [SOLVED]

### ISSUE THREAD

**Issue by yamlCase** [taverntesting/tavern#571]
(Dropping here in case someone else stumbles upon this)

attempting to use duplicate anchors feature will result in a `yaml.composer.ComposerError: found duplicate anchor` error.  While this is a YAML 1.2 feature, pyyaml does not yet support parsing duplicate anchors.

override-anchor branch of yaml/pyyaml has a PR that supports the duplicate anchors parsing feature.  This can be installed by simply installing the pip from git:

```
pip install --upgrade git+https://github.com/yaml/pyyaml.git@override-anchor
```

diff from master branch only contains the PR, so it should be save everywhere else.

## References:

Debian Bug Report:
python-yaml: YAML loader complains about non-unique anchors
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=515634

pyyaml PR:
Support overriding anchors #394
https://github.com/yaml/pyyaml/pull/394

pyyaml diff with master:
https://github.com/yaml/pyyaml/compare/override-anchor

**Comment by yamlCase** [comment]
FAQ: "why would you want to use duplicate anchors?"

In my use case, I'm utilizing stage includes.  This requires a new field "id:" on the stage that I'd really like it to be the same as "name:" without having to repeat myself.

```
---
test_name: do_some_things
stages:
  - {id: ping_api_endpoint, type: ref}
  - {id: get_token, type: ref}
  - {id: do_something, type: ref}
  - {id: revoke_token, type: ref}


---
stages:
  - id: &id ping_api_endpoint
    name: *id
    ...

  - id: &id get_token
    name: *id
    ...

  - id: &id do_something
    name: *id
    ...

  - id: &id revoke_token
    name: *id
    ...

```
