### ISSUE TITLE
Enhancement: stage includes reference by `id:` requires repeating code if using `name:` for stages

### ISSUE THREAD

**Issue by yamlCase** [taverntesting/tavern#572]
It would be convenient if we could find a way to avoid repeating the `id:` and `name:` keys if a) using stage includes and b) using the same name for both keys.

My observations:
- `id:` is only required to reference an external stage in our test stages and isn't prominent in test output.
- `name:` is used for interpreting output.
- there seems to be a 1:1 relationship between id's and names in a stage... i.e. why would the `name:` *need* to be different from `id:`?  (I can think of plenty of reasons why some could *want* it, maybe for longer name with spaces and other non-id friendly characters.)

Some ideas:
1. make `name:` optional if `id:` is present, and then alias `name:` to `id:`
2. make `id:` an alias of `name:` if a)`id:` not defined, and b) only id valid characters present in `name:` key.  throw an error only if being referenced, 
3. allow reference by `name:` as an alternative to `id:`.  i.e. `stages: [{name: ping_api_endpoint, type: ref}]`
4. use YAML anchors.  This already works with a pyyaml fix (see #571 ), but this is less than ideal

Example stage includes, similar to what I'm doing:
```
---
test_name: do_some_things
stages:
  - {id: ping_api_endpoint, type: ref}
  - {id: get_token, type: ref}
  - {id: do_something, type: ref}
  - {id: revoke_token, type: ref}


---
name: stage includes
stages:
  - id: ping_api_endpoint
    name: ping_api_endpoint
    ...

  - id: get_token
    name: get_token
    ...

  - id: do_something
    name: do_something
    ...

  - id: revoke_token
    name: revoke_token
    ...
```
