### ISSUE TITLE
Unable to set custom user agent through headers

### ISSUE THREAD

**Issue by nicoinn** [taverntesting/tavern#574]
I'm trying to set custom user agents as part of my requests, and I think Tavern might have a bug there/

Example: 

```
stages:
    - name: request
      request:
         url: "http://foo.bar/endpoint"
         method: POST
         headers:
            user-agent: "my/useragent"
         json: {}          
```

The resulting user-agent received by my endpoint is 

`python-requests/2.23.0,my/useragent`

while I'd really expect it to be just`my/useragent`

Am I doing something wrong (the doc does not really contain anything about user agent) or is that a bug ?
