### ISSUE TITLE
Unable to load the UTF8 string in the include file

### ISSUE THREAD

**Issue by dongfangtianyu** [taverntesting/tavern#586]
First of all, praise this excellent tool.

In the process of using, we encountered unexpected errors.

I have a file, a.yaml, which contains utf8 strings， it works
```yaml
# a.yaml
test_name: 断言响应任意内容

includes:
  - !include common.yaml
stages:
  - name: hello
    request:
      url: "http://127.0.0.1:8001/get_user"
      method: GET
    response:
      strict: False
      status_code: 200
      json:
        name: !anything
```

but when the include file contains the UTF8 string,  errors
```yaml
# common.yaml
name: 我的测试
description: 本文件记录被不同测试用例使用的内容


variables:
  hosst: http://127.0.0.1:8001/

```

the error info 
```bash
env\lib\site-packages\tavern\util\loader.py:141: in construct_include
    return load_single_document_yaml(filename)
env\lib\site-packages\tavern\util\loader.py:409: in load_single_document_yaml
    contents = yaml.load(fileobj, Loader=IncludeLoader)
env\lib\site-packages\yaml\__init__.py:112: in load
    loader = Loader(stream)
env\lib\site-packages\tavern\util\loader.py:116: in __init__
    Reader.__init__(self, stream)
env\lib\site-packages\yaml\reader.py:85: in __init__
    self.determine_encoding()
env\lib\site-packages\yaml\reader.py:124: in determine_encoding
    self.update_raw()
env\lib\site-packages\yaml\reader.py:178: in update_raw
    data = self.stream.read(size)
E   UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 35: illegal multibyte sequence
````
we modified `load_single_document_yaml` function, the operation is resumed
