### ISSUE TITLE
Verify response JSON key:variable list of strings with parametrize

### ISSUE THREAD

**Issue by safurrier** [taverntesting/tavern#588]
I'm testing an endpoint which returns a JSON with a key and an arbitrary list of strings. I would like to verify some test cases with expected responses and ideally through parametrization. This may just be a matter of not inputting properly to get python string formatting to work correctly. 

I have the following test structure:

```
test_name: Test a few example requests
marks:
  - parametrize:
      key:
        - input_key_1
        - n_return_items
        - list_of_returned_items
      vals:
        - [foo, 1, '["bar"]']
        - [spam, 2, '["ham", "eggs"]']
stages:
  - name: Post a valid input and get 200 response
    request:
      url: https://api.com/endpoint
      method: POST
      auth:
        - "{user}"
        - "{pass}"
      json:
        name: "{input_key_1}"
        n: "{n_return_items}"
    response:
      status_code: 200
      json:
        "{input_key_1}": "{list_of_returned_items}"
```

Is something like this possible? Or would I need to create an individual test for each example instead of parametrizing it?
