### ISSUE TITLE
Help needed: content-type; request body elements order, printing the response

### ISSUE THREAD

**Issue by api-girl** [taverntesting/tavern#596]
I am trying out Tavern with RestfullBooker API. One of the test cases is for [creating a booking](https://restful-booker.herokuapp.com/apidoc/index.html#api-Booking-CreateBooking). For some reason, I keep getting content-type text/html in response instead of application/json, although that is the content-type I am sending through the request headers. Can anybody spot the issue here?
It also seems that the request body key-value pairs are not being sent in the order I wrote them - can I somehow assure the order? I am also unable to print the actual response and see what I actually get. **EDIT**: I actually did manage to print the response, it is "<Response [200]>", but there is nothing else in the body. I expect to get a booking id and a booking object in a json format.

```
---
test_name: Create a booking
includes:
  - !include ..\utils.yaml

stages:
  - name: Post a new booking
    request:
      url: "{environment.url}/booking"
      headers:
        content-type: application/json
        accept: application/json
      method: POST
      json:
        firstname: "{data.user_name}"
        lastname: "{data.user_surname}"
        totalprice: "{data.booking_price}"
        depositpaid: "{data.dep_paid}"
        bookingdates:
          checkin: "{data.date_checkin}"
          checkout: "{data.date_checkout}"
        additionalneeds: "{data.add_needs}"
    response:
      status_code: 200
      headers:
        content-type: application/json
      save:
        json:
          booking_id: bookingid`
```

This is the error summary I get when running this test with tox (tox -e tavern):

`Errors:
E   tavern.util.exceptions.TestFailError: Test 'Post a new booking' failed:
    - Key mismatch: (expected["content-type"] = 'application/json' (type = <class 'tavern.util.dict_util._FormattedString'>), actual["content-type"] = 'text/html; charset=utf-8' (type = <class 'str'>))
    - No json in response (wanted to save {'booking_id': 'bookingid'})
`
