### ISSUE TITLE
Reusing 'parametrize' values?

### ISSUE THREAD

**Issue by MaximumQuiet** [taverntesting/tavern#598]
Hi, is there any way to reuse parameterize values?

For example, I have the following test configuration:

```yaml
---
test_name: Successfully returns the auto registration history
includes:
  - !include stage.async-result.yaml

marks:
  - parametrize:
      key: vin
      vals:
        -  > A lot of values here <

stages:
  - name: Trigger the task
    request:
      url: "http://localhost:8000/auto/history/{vin}"
      method: GET
    response:
      status_code: 202
      save:
        $ext:
          function: utils:url_from_refresh_header
  - type: ref
    id: async_result

---
test_name: Successfully returns auto accidents
includes:
  - !include stage.async-result.yaml

marks:
  - parametrize:
      key: vin
      vals:
       -  > A lot of values here <

stages:
  - name: Trigger the task
    request:
      url: "http://localhost:8000/auto/accidents/{vin}"
      method: GET
    response:
      status_code: 202
      save:
        $ext:
          function: utils:url_from_refresh_header
  - type: ref
    id: async_result
```

How can I define the parametrize values in one place and reuse them?

**Comment by KenStorey** [comment]
I have done this by putting the data in a separate file "params.yaml".
```
  - parametrize:
      key: [ongoing_call_type, ongoing_call_pri, new_call_type, new_call_pri]
      vals:
       - 1
       - 2
       - etc

```
Then, in the test:

`marks: !include params.yaml`

You cannot use any other marks (e.g. 'skip') with this method.

**Comment by MaximumQuiet** [comment]
@KenStorey thanks!

However, would be great to have the functionality to use external sources for 'parametrize' values and keep using other marks as well.

**Comment by michaelboulton** [comment]
A YAML anchor would do this if you only want to do it in one file, but if you want to share in multiple files you can do something more like

```yaml
# parametrize_vals.yaml
key: input
vals:
- 123
- 456
- 789
```
```yaml
# test_input.tavern.yaml
---
test_name: test an input

marks:
  - parametrize:
      !include parametrize_vals.yaml

stages:
  ...
```
