### ISSUE TITLE
Reusing !included data with anchors raises ConstructorError

### ISSUE THREAD

**Issue by tomconte** [taverntesting/tavern#599]
I am trying to include an external data file that contains a fairly large JSON payload, and then I would like to re-use this payload in a following stage using anchors. (ultimately I would then like to override some of the parameters in the second stage)

I have tried the YAML syntax below, and got this error:

```
E   yaml.constructor.ConstructorError: while constructing a mapping
E     in "/Users/tconte/src/HM/tests/test_dataset_entity.tavern.yaml", line 23, column 9
E   expected a mapping or list of mappings for merging, but found scalar
E     in "/Users/tconte/src/HM/tests/test_dataset_entity.tavern.yaml", line 12, column 9
```

YAML configuration:

```yaml
stages:
  - name: Create dataset
    request:
      url: https://api.azurewebsites.net/api/v1/ds/write
      method: POST
      headers:
        Authorization: "Bearer {tavern.env_vars.AUTH_TOKEN}"
      json:
        &body !include dataset_body.json
    response:
      status_code: 200

  - name: Create entity date - full
    request:
      url: https://api.azurewebsites.net/api/v1/entity/write
      method: POST
      headers:
        Authorization: "Bearer {tavern.env_vars.AUTH_TOKEN}"
      json:
        <<: *body
    response:
      status_code: 200
```
