### ISSUE TITLE
Option to define base URL from command line.

### ISSUE THREAD

**Issue by WhileLoop** [taverntesting/tavern#6]
Would be nice to be able to define a base URL from the command line.

**Comment by michaelboulton** [comment]
I think something planned for some future release is something similar to helm where as well as a global configuration file, you can pass in single fields with a flag like `--set`, eg:

```yaml
# includes.ymal
variables:
    baseurl: https://example.com
    accesstoken: faketoken
```
Overridden with
```
tavern-ci --set baseurl="https://example.org" accesstoken=abc123
```

**Comment by benhowes** [comment]
Thinking about this, it would probably have a fair bit of utility to be able to use environment variables for this purpose too, because they're well supported in most CI systems for config.

**Comment by funkyfuture** [comment]
fyi, i started to implement this [here](https://github.com/telota/tavern/tree/issue_6). for the time being i'm waiting for usage feedback from our developers before i add unit tests.

**Comment by benhowes** [comment]
@funkyfuture do you have plans to finish the branch you were working on? I had a quick look and it's looking good so far!

**Comment by funkyfuture** [comment]
phew, so, i'm currently self-assigned to tasks far away from this. afaict my team mates are still evaluating Postman. (the main showstopper to use tavern is that they need to evaluate xml responses as well, iirc they'd also prefer yaml formulated schemas to use in conjunction with Cerberus, so a plugin system for tavern seems desirable - but that's all a very different story. [though, one thought occured to me in this context and may be noted: Docker-Compose is a good example how versioned config files - `version` is a top-level key - allows a tool to introduce breaking features while still working with prior config files.])

having that said, feel free to merge my progress. shall i open a pr for this?
unfortunately i can't amend tests and docs in the foreseeable future.

**Comment by michaelboulton** [comment]
The 'preferred' way of doing this is to use an environment variable and then put it in either a config file or the test, eg:

```yaml
# included.yaml
---
name: test includes

variables:
  base_host: "{tavern.env_vars.BASE_HOST}"
```
```
# test_request.tavern.yaml
---
test_name: run a test

stages:
  - name: run a test
    request:
      url: "{base_host}"
      # or
      url:  "{tavern.env_vars.BASE_HOST}"
```
