### ISSUE TITLE
File upload path on include yaml

### ISSUE THREAD

**Issue by gtq** [taverntesting/tavern#607]
Using a file path specified in an include yaml doesn't resolve properly as one would have expected.
I also tried enclosing the entry in quotes like "{file_path}" but it also doesn't work. Hardcoding the filepath
works though

non-working snippet 
```
stages:
- *login_data
- name: post utils/uploader
  request:
    method: POST
    headers:
      Authorization: Bearer {access_token}
    files:
      file_data: {file_path}
    url: http://spectro.ai:3000/api/v1/utils/
  response:
    status_code: 200
    strict: false
test_name: post utils/uploader
```

working snippet
```
stages:
- *login_data
- name: post utils/uploader
  request:
    method: POST
    headers:
      Authorization: Bearer {access_token}
    files:
      file_data: /Users/myuser/my_file
    url: http://spectro.ai:3000/api/v1/utils/
  response:
    status_code: 200
    strict: false
test_name: post utils/uploader
```
