### ISSUE TITLE
Tavern 1.7.0 "Hanging"

### ISSUE THREAD

**Issue by KenStorey** [taverntesting/tavern#610]
Tavern intermittently, but frequently, just stops working.

![Tavern1](https://user-images.githubusercontent.com/46034453/97029320-2f021080-1555-11eb-8b00-0d890a0653c0.PNG)
![Tavern 2](https://user-images.githubusercontent.com/46034453/97029453-5f49af00-1555-11eb-87e0-1b8f5fab9f91.PNG)

In the first example it stopped on the first test, in the second it stopped halfway through. Sometimes it even manages to complete the run!

It is running in a Docker container, in this case locally run manually, but the same occurs on our Git pipelines.

The scripts are not very complicated. The first example is

```
paho-mqtt: &mqtt_spec
  client:
    client_id: test_team
  connect:
    host: "{host}"
    port: !int "{port}"
    timeout: 0.5

# test_app_brightness_levels.tavern.yaml

test_name: Brightness, no adjustment

strict:
  - json:off

includes: &includes
  - !include tavern_library/config.yaml
  - !include tavern_library/tdcp_keys.yaml
  - !include tavern_library/hmi_indications.yaml
  - !include tavern_library/mqtt_topics.yaml

paho-mqtt: *mqtt_spec

stages:

  - name: Step 1 - Brightness key press

    mqtt_publish:
      topic: "{dcpsim_keypress_topic}"
      json:
        key_code: !int "{brightnessKey}"

  - name: Step 2 - Brightness key release

    mqtt_publish:
      topic: "{dcpsim_keyrelease_topic}"
      json:
        key_code: !int "{brightnessKey}"

  - name: Step 3 - Brightness indication and level is displayed

    mqtt_publish:
      topic: "{dcpsim_information_request_topic}"
      json:
        request: "current_display"

    mqtt_response:
      topic: "{dcpsim_current_display_text_topic}"
      json:
        line2_text: "{brightness_text}"
        line3_text: "{level4}"
      timeout: 1

  - name: Step 4 - Brightness indication and level are blanked after 3 seconds of inactivity

    delay_before: 3

    mqtt_publish:
      topic: "{dcpsim_information_request_topic}"
      json:
        request: "current_display"

    mqtt_response:
      topic: "{dcpsim_current_display_text_topic}"
      json:
        line2_text: "{blank_line}"
        line3_text: "{blank_line}"
      timeout: 1

```
I attempted to set up logging by reference to [Tavern Documentation](https://tavern.readthedocs.io/en/latest/debugging.html) but I'm afraid I didn't understand it.
