### ISSUE TITLE
Save first item from list response

### ISSUE THREAD

**Issue by mirrorkeydev** [taverntesting/tavern#611]
Hello! Hope you're doing well :)
#### What I'm trying to do
I'm using Tavern to test an endpoint that returns a JSON list, for example:
```bash
$ curl http://host/endpoint
["a", "b", "c"]
```
I want to save the first item of the list to use in another call, but I can't figure out how to reference the root response so that I can access the first item.

#### What I've tried
Based on the doc's explanation that for a response ` { thing: { nested: [ .. ] } }`, `first_val: thing.nested[0]` is equivalent to `json["thing"]["nested"][0]`:
```yaml
response:
      ...
      save:
        json: 
          first_item: [0] # results in first_item being set to the [0] literal
```
I also tried various plays on:
```yaml
# all result in first_item being set to None
first_item: json[0]
first_item: response[0]
first_item: body[0]
```

#### What I got from the docs
According to the docs, accessing information inside a dictionary response is as simple as referencing the key name, but this scenario doesn't have any keys since it's not a dictionary. I would save the whole list and access the first index later, but the docs state "trying to save a ‘block’ of data such as a JSON list or object is currently unsupported". I read about using custom functions to extract data from the response, but I would prefer not to have to write a whole utility function for something this simple.

Is there anything that I'm missing, or is there not a way to currently do this operation?

**Comment by mirrorkeydev** [comment]
I figured it out! It was pretty silly mistake:
```yaml
response:
      ...
      save:
        json: 
          first_item: "[0]" # needs to be a string
```
Hope this helps someone else :)
