### ISSUE TITLE
MQTT publish does it support the use of external function

### ISSUE THREAD

**Issue by Sokkam** [taverntesting/tavern#619]
Hello, I encountered a problem. I want to use an external method like HTTP request in the mqtt_publish configuration of yaml. But when executed locally, it did not resolve and replace my external function.

- tavern yaml
```yaml
stages:
  - name: Success Request
    mqtt_publish:
      topic: xxx
      qos: 1
      json:
        $ext:
          function: testing_request:save_static_data_request
    mqtt_response:
      topic: xxx
      timeout: 5
      json:
         msg: "success"
         code: 0
```
- python external file
```python
def save_static_data_request():
    current_timestamp = int(time.time())
    request = {
        ...
        "time": current_timestamp,
        ...
    }
    return request
```

The above configuration will not parse my external configuration, but it is normal for me to use http request to call the external configuration.

Please help me, thanks!!
