### ISSUE TITLE
How can I verify a response body who's keys are randomly ordered?

### ISSUE THREAD

**Issue by burritoIand** [taverntesting/tavern#622]
My api returns the response body with nested data ordered randomly. For example:
```
    response:
      status_code: 201
      json:
          relationships:
            foo:
              data:
                id: '{foo_id}'
                type: 'foos'
            bar:
              data:
                id: '{bar_id}'
                type: 'bars'
```
or sometimes
```
    response:
      status_code: 201
      json:
          relationships:
            bar:
              data:
                id: '{bar_id}'
                type: 'bars'
            foo:
              data:
                id: '{foo_id}'
                type: 'foos'
```

How can I make the test pass regardless of the ordering? I tried `strict: False` at both the stage and test level but it did not work.

Thanks
