### ISSUE TITLE
Add possibility to change included json

### ISSUE THREAD

**Issue by EduardKuzhir** [taverntesting/tavern#627]
Hello, thank you for this tool. 
Is there any possibility to change included json by !include or !force_format_include tags? It could be very useful for cases where we need to add little change into huge amount of data. For example:

```yaml
  - name: some test
    request:
      headers: *auth_header
      url: "{test_url}"
      method: POST
      json: !force_format_include "{previous_saved_response}" 
        additionalField: lorem ipsum
        existingField: new data # to allow overwrite included json
        someWrapperField:
          nestedFieldForChange: 123
```
One more possible prototype:
```yaml
  - name: some test
    request:
      headers: *auth_header
      url: "{test_url}"
      method: POST
      json:
        <<: !force_format_include "{previous_saved_response}"
        additionalField: lorem ipsum
        existingField: new data # to allow overwrite included json
        someWrapperField:
          nestedFieldForChange: 123
```

Or is there any workaround for it?

P.S. also it would be nice to have possibility to remove some data from (force)included  json.
