### ISSUE TITLE
Feature request: add possibility to use variables whilre resolving !include path

### ISSUE THREAD

**Issue by EduardKuzhir** [taverntesting/tavern#628]
Please, add possibility to resolve variable/parameter value while resolving path to included file
```yaml
 - name: send write
    request:
     ...
      json: !include "request/{test_type}/write.json"
```
