### ISSUE TITLE
Feature request: recursive resolving of variable values (Or parameterized templates in variables)

### ISSUE THREAD

**Issue by EduardKuzhir** [taverntesting/tavern#630]
Let's say I have two microservices with the same endpoints:
```yaml
name: settings
description: common settings for two microservices

variables:
  common_url: "{host}/endpoints/{product_name}/v1/command/write"
```
And I want to reuse this common endpoint twice with different hosts but in single test, is it possible to accomplish it?

**Comment by michaelboulton** [comment]
You should be able to use the parametrize https://tavern.readthedocs.io/en/latest/basics.html#parametrize mark for your use case I think, something like
```yaml
variables:
  host_1: "https://example1.com"
  host_2: "https://example1.com"
```
```yaml
---
test_name: 2 services

marks:
  - parametrize:
      key: host
      vals:
        - "{host_1}"
        - "{host_2}"

stages:
    request:
        url: "{host}/endpoints/{product_name}/v1/command/write"
    ...
```

If you mean you want to have template format placeholders in a variable from a config file like your example, that isn't possible because config files only have the template replacement done to them once (when they are loaded) and they can't be parametrised like that. There is also protection in place to stop any string from being formatted twice so doing something like this won't work either
```yaml
variables:
  common_url: "{{host}}/endpoints/{product_name}/v1/command/write"
```
