### ISSUE TITLE
tavern.testutils.helpers:validate_regex returning a string with quotes mark

### ISSUE THREAD

**Issue by partsalliance** [taverntesting/tavern#644]
Hi,

I am using tavern validate_regex to extract a code from a http response from the logs it is successful. I want to use this variable as a param in the next step of the test. I am able to access the variable but the logs show that the output saved earlier is being return with quote marks around it. 

Below are the snippets of tavern yaml:

    response:
      status_code: 200
      save:
        $ext:
          function: tavern.testutils.helpers:validate_regex
          extra_kwargs:
            expression: "code=(?P<code_token>.*)&state"

code_token for example is 2345-2456

I then try to use it in the next part of the test:

method: GET
      params:
        code: "{regex.code_token}"

The next http call fails due to the param says the code_token = '2345-2456' when I need it to be 2345-2456

Is there a way to strip the quote marks in the yaml or do I need a custom function to ensure that the regex doesnt return the quote marks?  or does anyone have any suggestions?

Using tavern 1.13.1

**Comment by partsalliance** [comment]
Work around was found.

Rather than adding the param in the params section just add to the url ie "url?code={regex.code_token}"

**Comment by michaelboulton** [comment]
I can't reproduce this with this test

```yaml
test_name: Test saving data does not add quotes

stages:
  - name: simple match
    request:
      url: "{global_host}/echo"
      method: POST
      json:
        fake: code=abc123&state=f
    response:
      status_code: 200
      save:
        $ext:
          function: tavern.testutils.helpers:validate_regex
          extra_kwargs:
            expression: "code=(?P<code_token>.*)&state"

  - name: Reuse thing specified in first request
    request:
      url: "{global_host}/echo"
      method: POST
      json:
        fake: "{regex.code_token}"
    response:
      status_code: 200
      json:
        fake: abc123

  - name: Reuse as param
    request:
      url: "{global_host}/echo_params"
      method: GET
      params:
        top_level:
          fake: "{regex.code_token}"
        code: "{regex.code_token}"
    response:
      status_code: 200
      json:
        top_level:
          fake: abc123
        code: "{regex.code_token}"
```

ie, I'm saving the code and reusing it in the body or as a param and I'm not getting the quotes added.

Is there something else you are doing in your test that might be doing something to the values?

**Comment by partsalliance** [comment]
Hi,

I copied your test above and added in the globalhost: 

For the last test this is the output of the formatted stage:

```
Source test stage (line 28):
  - name: Reuse as param
    request:
      url: "http://0.0.0.0:5000/echo_params"
      method: GET
      params:
        top_level:
          fake: "{regex.code_token}"
        code: "{regex.code_token}"
    response:
      status_code: 300
      json:
        top_level:
          fake: abc123

Formatted stage:
  name: Reuse as param
  request:
    method: GET
    params:
#Here the code has the quote marks around it so in a url it would be url:port/path?code='abc123' is not correct and the endpoint will not understand this param as the quote marks shouldnt exist. it should be url:port/path?code=abc123 or is this expected functionality? 
      code: 'abc123'
      top_level:
        fake: 'abc123'
    url: http://0.0.0.0:5000/echo_params
  response:
    json:
      code: 'abc123'
      top_level:
        fake: abc123
    status_code: 200
```
I agree the response checking part works. It is the sending of the params. I also find this is the same for when sending the value of a header. I will work on providing an example for the issue with the header.

This was with tavern 1.13.1 let me update to the latest.

**Comment by partsalliance** [comment]
Another example if you set a header with a variable compared to setting it manuall, you can see the addition of quotes:
```
Source test stage (line 28):
  - name: Reuse as param
    request:
      url: "http://0.0.0.0:5000/echo_params"
      method: GET
      headers:
        referer: "{regex.code_token}"
        content-type: test
      params:
        top_level:
          fake: "{regex.code_token}"
        code: "{regex.code_token}"
        another: test
    response:
      status_code: 300
      json:
        top_level:
          fake: abc123

Formatted stage:
  name: Reuse as param
  request:
    headers:
      content-type: test
      referer: 'abc123'
    method: GET
    params:
      another: test
      code: 'abc123'
      top_level:
        fake: 'abc123'
    url: http://0.0.0.0:5000/echo_params
  response:
    json:
      code: abc123
      top_level:
        fake: abc123
    status_code: 300
```

**Comment by partsalliance** [comment]
I found the quote issue is also the same for when saving a variable from a response and wanting to send in the next stage as a header like so:

```
test_name: Test saving data does not add quotes

stages:
  - name: simple match
    request:
      url: "http://0.0.0.0:5000/echo"
      method: POST
      json:
        fake: code=abc123&state=f
    response:
      status_code: 200
      save:
        json:
          saving_url: fake

  - name: Reuse thing specified in first request
    request:
      url: "http://0.0.0.0:5000/echo"
      method: POST
      headers:
        normal: application
        testfake: "{saving_url}"
    response:
      status_code: 200
      json:
        fake: abc123
```

Executing:
```
Format variables:
  saving_url = 'code=abc123&state=f'

Source test stage (line 15):
  - name: Reuse thing specified in first request
    request:
      url: "http://0.0.0.0:5000/echo"
      method: POST
      headers:
        normal: application
        testfake: "{saving_url}"
    response:
      status_code: 200
      json:
        fake: abc123


Formatted stage:
  name: Reuse thing specified in first request
  request:
    headers:
      normal: application
      testfake: 'code=abc123&state=f'
    method: POST
    url: http://0.0.0.0:5000/echo
  response:
    json:
      fake: abc123
    status_code: 200
```
