### ISSUE TITLE
Move 'clear cookies' to a top-level request item

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#651]
Move out of 'meta' which only has one item and into top level

ie

```yaml
request:
  name: "thing"
  url: "http://example.com"
  clear_cookies_before_request: true
```
