### ISSUE TITLE
Help: Any way to save plain string response to variable?

### ISSUE THREAD

**Issue by itsmichaelk** [taverntesting/tavern#667]
Hello everyone,

We just started to use Tavern for our API testing, but we've come to a point where we got no solution.

This is in the .yaml-file:
```
- name: generate password for user
    request:
      url: "https://API.com/user/{newUserDn:s}/pwgen"
      method: GET
      headers:
        content-type: application/json
        Authorization: "Bearer {auth_jwt:s}"
    response:
      status_code: 200
      save:
        genPW: response
```

Is it somehow possible (maybe with external functions) to store the plain string reponse into a variable to use it in different tests on the same stage level?

Thanks in advance!

**Comment by itsmichaelk** [comment]
Ok, I think I found a way..

```
save:
        $ext:
          function: testing_utils:convertToJson
```

and in my **testing_utils.py**:

```
from box import Box

def convertToJson(response):
    return Box({"pwGen": response.text})
```

**Comment by itsmichaelk** [comment]
Yup, this resolved my issue. 
I can then use this variable like this:

```
json:
        current: "{pwGen:s}"
```

Closing this now.

**Comment by mbfr** [comment]
It's not very obvious but you can also do 

```yaml
save:
  json:
    current: "@"
```

The 'save' semantics are based on JMESpath and `"@"` just means "everything"
