### ISSUE TITLE
Tavern won't use a 'nulled key'

### ISSUE THREAD

**Issue by itsmichaelk** [taverntesting/tavern#668]
Hey everyone,

I have a problem. I create something with **POST**, then I use **PUT** to add _"extraData"_ to the created instance - everything fine so far.
Now I want to remove the extraData from the instance. In our SwaggerUI I can easily leave the extraData out or set it as `"extraData": null ` and it is getting removed from the instance.

In Tavern it won't accept this `"extraData": null` - I don't get an error, but it doesn't get removed in the instance.

This is my yaml:

```
---
test_name: authenticate user and get token

stages:
  - &get_token
    name: authenticate user
    request:
      url: https://API.com/core/nos-api/v5/authenticate
      json:
        user: "USER"
        password: "PASSWORD"
      method: POST
    response:
      status_code: 200
      save:
        json:
          auth_jwt: jwt
        $ext:
          function: testing_utils:pickUpTime

---
test_name: create nosdbis

stages:

  - *get_token
  - name: update existing instance (remove extraData)
    request:
      url: "https:/API.com/extended/nos-api/v5/nosdbi/14420"
      headers:
        content-type: application/json
        Authorization: "Bearer {auth_jwt:s}"
      json:
        status: "used"
        diagnosticBundleId: 3
        owner: "OWNER"
        userChanged: "USERCHANGED"
        extraData: null
      method: PUT
    response:
      status_code: 200
```

This is only the "remove the extraData" part and the needed authentication for it.
Anyone has an idea? If I just leave "extraData: null" out, it doesn't get deleted either.

**Comment by michaelboulton** [comment]
Can you verify that the server is not receiving what you're specifying in the test? If I define a test like
```yaml
---

test_name: Send null value

stages:
  - name: Match a uuid v4
    request:
      url: "{global_host}/err_non_null"
      method: PUT
      json:
        var: null
    response:
      status_code: 200
      json:
        result: good
```

With the server being

```python

@app.route("/err_non_null", methods=["PUT"])
def err_non_null():
    if request.get_json() != {"var": None}:
        return jsonify({"result": "bad"}), 400
    else:
        return jsonify({"result": "good"}), 200

```

Then this works fine for me.
