### ISSUE TITLE
Using imported json file property also as response variable

### ISSUE THREAD

**Issue by agentpurp** [taverntesting/tavern#669]
Hello together, 

first of all i really like tavern!

Actual I'm trying to import a test file (https://tavern.readthedocs.io/en/latest/basics.html#directly-including-test-data) and use one the imported properties also as a variable for the response check. I don't know if this is possible or is there any other solution not to define requesting and check variables twice. 

Example:

```yaml
---

test_name: Post a lot of data

stages:
  - name: Create new user
    request:
      url: "{service:s}/new_user"
      method: POST
      json: !include test_data.json
    response:
      status_code: 201
      json:
        age: 26<- value from the json file

```
