### ISSUE TITLE
How to configure timeout of tests at runtime without modifying the test file itself?

### ISSUE THREAD

**Issue by gc-ss** [taverntesting/tavern#670]
We can define a `timeout` in a test like this:

```
test_name: A helpful name

stages:
  - name: Make request
    request:
      url: "{endpoint}"
      json:
        query: "<query>"
      method: POST
      timeout: 5
      headers:
        content-type: application/json
```

Above hardcodes `timeout` to 5s.

How do I turn timeout into a value that can be configured at runtime without modifying the test file itself?

For example, use `env_vars` or something else?

I tried `env_vars`:

```
test_name: A helpful name

stages:
  - name: Make request
    request:
      url: "{endpoint}"
      json:
        query: "<query>"
      method: POST
      timeout: "{tavern.env_vars.TIMEOUT_SECONDS}"
      headers:
        content-type: application/json
```

and got error:

`tavern.util.exceptions.BadSchemaError: 'timeout' must be either a float/int or a 2-tuple of floats/ints - got '{tavern.env_vars.TIMEOUT_SECONDS}' (type <class 'str'>)`

**Comment by michaelboulton** [comment]
You can use a [type conversion token](https://tavern.readthedocs.io/en/latest/basics.html#type-conversions) for this, eg
```yaml
timeout: !int "{timeout}"
```

**Comment by gc-ss** [comment]
> You can use a [type conversion token](https://tavern.readthedocs.io/en/latest/basics.html#type-conversions) for this, eg
> 
> ```yaml
> timeout: !int "{timeout}"
> ```

YES! That works!. For anyone else reading this I was missing the type conversion token for "{tavern.env_vars.TIMEOUT_SECONDS}". The correct test is:

```
test_name: A helpful name

stages:
  - name: Make request
    request:
      url: "{endpoint}"
      json:
        query: "<query>"
      method: POST
      timeout: !int "{tavern.env_vars.TIMEOUT_SECONDS}"
      headers:
        content-type: application/json
```
Thank You Michael!

Since I have you here: I wanted to set the `url` variable in the above test to something like:

`"{service.proto:s}://{tavern.env_vars.TEST_HOST:s}:{service.port:d}/{graphql_endpoint:s}"`

i.e., the above test would look like:

```
test_name: A helpful name

stages:
  - name: Make request
    request:
      url: "{service.proto:s}://{tavern.env_vars.TEST_HOST:s}:{tavern.env_vars.TEST_PORT:d}/{endpoint:s}"
      json:
        query: "<query>"
      method: POST
      timeout: !int "{tavern.env_vars.TIMEOUT_SECONDS}"
      headers:
        content-type: application/json
```

Of course, this does not work - for example, an error I get is `tavern.env_vars.TEST_PORT` is a string and cannot be case to a number although it's an env var set to `80`.

How do I:

1.  set `service.proto`? Will `proto` be an attribute under a YAML entity named `service`? How will that YAML look like?
2. Fix the issue with `tavern.env_vars.TEST_PORT`?

Again, thank you for the help.

**Comment by michaelboulton** [comment]
For 1. you need to define your [configuration file](https://tavern.readthedocs.io/en/latest/basics.html#including-global-configuration-files) like
```yaml
...

variables:
  service:
    proto: grpc
```


For 2. you should just use `{tavern.env_vars.TEST_PORT}` or `{tavern.env_vars.TEST_PORT:s}` to format the port, as all environment variables are actually just strings.
