### ISSUE TITLE
How to pass fixtures to function in verify_response_with?

### ISSUE THREAD

**Issue by gc-ss** [taverntesting/tavern#671]
In my test, I have 2 fixtures:

- `fixture1` contains the query to use for the test
- `fixture2` contains the expected response for that query to use in the test

```
test_name: A helpful name

marks:
  - some_mark
  - usefixtures:
      - fixture1
      - fixture2

stages:
  - name: Make request
    request:
      url: "{endpoint}"
      json:
        query: "{fixture1}"
      method: POST
      headers:
        content-type: application/json
    response:
      verify_response_with:
        function: path.to.verification.function:function_name
        extra_kwargs:
          expected: fixture2
```

The `query: "{fixture1}"` works as expected, but `path.to.verification.function:function_name` recieves `fixture2` literally instead of the fixture.

Is there a way for me to pass either the fixture or the result of running the fixture to the verification function itself?
