### ISSUE TITLE
How to inject random UUID in url?

### ISSUE THREAD

**Issue by Robin-Ding-Bose** [taverntesting/tavern#682]
We have a service with the URL, https://www.domain.com/discover/applications/UUID/
I would like to run the test with a random UUID each time.

Currently I use a stage as following, and save response.text (via the external function) into a var and use it in the next step.

```stages:
  - name: get uuid
    request:
      url: "https://www.uuidgenerator.net/api/version4"
      method: GET
    response:
      status_code: 200
      verify_response_with:
        function: tavern-utils:validate_response
      save:
        $ext:
         function: tavern-utils:transform_response
```

The transform_response function is as following:
```
def transform_response(response):
    return Box({"uuid": response.text})
```

Then I use the var in next step as:
```
- name: trigger new client event through sd service
    request:
      url: "https://www.domain.com/discover/applications/{uuid}"
      method: GET
    response:
      status_code: 200
```

I want to know if there is some easy way without access a external api  to inject the random UUID in the url?

Thanks.

**Comment by michaelboulton** [comment]
If you define a variable in [global configuration](https://tavern.readthedocs.io/en/latest/basics.html#including-global-configuration-files) like this:
```yaml
---
name: test includes
description: test

variables:
  uuid: !uuid
```
This will create a random uuid format variable that you can use in your step in the same way as you're currently doing.
