### ISSUE TITLE
cannot verify an integer value in response

### ISSUE THREAD

**Issue by p4misc** [taverntesting/tavern#686]
Hi, I get tavern.util.exceptions.BadSchemaError: Error at yaml:22 - column 24 - cannot define an empty value in test - either give it a value or explicitly set it to None.

```
test_name: Sample Get Test

includes:
  - !include common.yaml

marks:
  - parametrize:
      key: target_id
      vals:
        - 1
        - 2
        - 3

stages:
  - name: sample
    request:
      url: "{target_url}/posts/{target_id}"
      method: GET
    response:
      strict: False
      status_code: 200
      json:
        id: {target_id:d}
```

If a value of the key "id" is a string (e.g. { "id" : "1" }), I can change the line 22 from id: {target_id:d} to id: "{target_id}".
However, I cannot surround the variable in quotes because a value of the key "id" is integer (e.g. { "id" : 1 }).

How can I use an integer variable to verify an integer value in response?
