### ISSUE TITLE
Question - overwrite imported stage

### ISSUE THREAD

**Issue by Draeggon** [taverntesting/tavern#687]
I have a stage in a global file which i import
```yaml
stages:
  - id: PostRoom
    name: Creating a room
    request:
      url: "{url}/room"
      json:
        title: my title
        description: my description
      method: POST
    response:
      json:
        id: !re_fullmatch "[0-9a-f]{24}"  # the regex check if id is an objectId
        title: my title
        description: my description
        users: []
      save:
        json:
          roomId: id  # saving the id for the other function
```
and when i use it in another file
```yaml
stages:
  - type: ref
    id: PostRoom
```
i need to overwrite it but i haven't find any way to do that
how can it be done ?
