### ISSUE TITLE
Question: Use a saved value in a subsequent yaml document

### ISSUE THREAD

**Issue by p4misc** [taverntesting/tavern#688]
Hi, 
I would like to use a saved value returned_id in a subsequent yaml document in the same file.
However, this doesn't work. Does anyone have a solution to achieve this?

```
---
test_name: test1

stages:
  - name: stage1 for the test1
    request:
      url: https://jsonplaceholder.typicode.com/posts/1
      method: GET
    response:
      status_code: 200
      json:
        id: 1
      save:
        json:
          returned_id: id

---
test_name: test2

stages:
  - name: stage1 for the test2
    request:
      url: "https://jsonplaceholder.typicode.com/posts/{returned_id}"
      method: GET
    response:
      status_code: 200
      json:
        id: !int "{returned_id}"
```
