### ISSUE TITLE
error when using the magic !anything

### ISSUE THREAD

**Issue by cetanu** [taverntesting/tavern#69]
yaml.constructor.ConstructorError: 
        could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:builtins.object'

Running Tavern 0.7.1
PyYAML 3.12

Trying to match some things which should be in the response, but they are totally random

The test code to replicate:

    test_name: '#69'

    stages:
      - name: test the error
        request:
          url: https://jsonplaceholder.typicode.com/posts?title=qui%20est%20esse
          method: GET
        response:
          status_code: 200
          body:
            - userId: 1
              id: 2
              title: qui est esse
              body: !anything  

Any ideas?

**Comment by michaelboulton** [comment]
The code you've posted is missing the required "test_name" and "stages" for it to work:

```yaml
test_name: "abc"

stages:
  - name: test the error
    request:
      url: https://jsonplaceholder.typicode.com/posts?title=qui%20est%20esse
      method: GET
    response:
      status_code: 200
      body:
        - userId: 1
          id: 2
          title: qui est esse
          body: !anything
```
The error it's giving is a bit cryptic though, I'll look at that now
