### ISSUE TITLE
Use parametrize for HTTP method

### ISSUE THREAD

**Issue by GitifyMe** [taverntesting/tavern#699]
As a tester, I want to assure that certain verbs like POST,PUT,DELETE,PATCH are causing a fixed behavior for a set of urls.
I can parametrize the url, but using this approach for the method is not possible yet.

```yaml
marks:
  - parametrize:
      key: verb
      vals:
        - POST
        - PUT
        - DELETE
        - PATCH
  - parametrize:
      key: path
      vals:
        - /odata/TestDataSet
        - /doc
        - /

stages:
  - name: "Verb {verb} on {path} returns whatever"
    request:
      url: "{service}{path}"
      method: "{verb}"
```

Currently this yields an error:
```
Enum '{verb}' does not exist. Path: '/stages/0/request/method' Enum: ['GET', 'PUT', 'POST', 'DELETE', 'PATCH', 'OPTIONS', 'HEAD'].
```
I would need this for easy regression testing...
