### ISSUE TITLE
Quickstart example not working

### ISSUE THREAD

**Issue by albamig** [taverntesting/tavern#700]
Hi! At @Clariteia we have decided to start using Tavern to test the [Minos Framework](https://github.com/Clariteia/minos_microservice_common). We have just noticed the quickstart example does not work, though.

The problem is that version `1.15.0` seems to have JSON strictness enabled by default.

IMO, the cleanest fix is to set the whole JSON so it works out of the box:

```yaml
---
# Every test file has one or more tests...
test_name: Get some fake data from the JSON placeholder API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: Make sure we have the right ID

    # Define the request to be made...
    request:
      url: https://jsonplaceholder.typicode.com/posts/1
      method: GET

    # ...and the expected response code and body
    response:
      status_code: 200
      json:
        id: 1
        userId: 1
        title: "sunt aut facere repellat provident occaecati excepturi optio reprehenderit"
        body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
```

Solutions such as adding the `strict` property to the YAML or the command line `-tavern-strict json:off` option work as well, but add unnecessary noise from my point of view.

If you agree I can make the change myself.
