### ISSUE TITLE
Continue execution after failed stage

### ISSUE THREAD

**Issue by KenStorey** [taverntesting/tavern#711]
Is it possible to instruct Tavern _not_ to stop executing a test when it encounters a failure?

Most of our tests are of the form

- Set up
- Perform test
- Tear down

If a failure is encountered the tear down does not happen and, consequently, subsequent tests all fail.

**Comment by michaelboulton** [comment]
I don't think there's any particular reason why there couldn't be something like

```yaml
setup:
	- name: ...

stages:
	- name: step 1
	- name: step 2

teardown:
	- name: ...
```

Where the teardown would act like a 'finally' block in Python and would always run as long as the setup stages all finished
