### ISSUE TITLE
Environment variables in included files are not loaded when running with pytest --collect-only

### ISSUE THREAD

**Issue by moisesbenzan** [taverntesting/tavern#720]
If we have a common file as:
```yaml
# common.yaml
---
name: General test includes
description: Used for configuring target API

variables:
  host: "{tavern.env_vars.API_HOST}"
```

and a simple testcase as:
```yaml
# test/test_health.tavern.yaml
test_name: Verify that the server is running and healthy
stages:
  - name: Probe the /health endpoint and verify that the server is running.
    request:
      url: "{host:s}/health"
      method: GET

    # ...and the expected response code and body
    response:
      status_code: 200
      json:
        status: ok
```

When we run `pytest --collect-only` the test will error out as environment variable substitution did not happen.

One would expect the tests to be collected correctly and no error popping out or at least for tavern to do a dummy substitution for the env var.
