### ISSUE TITLE
How to save a list

### ISSUE THREAD

**Issue by ncarrier** [taverntesting/tavern#721]
Hello,
I'm testing a REST API which controls the network configuration of a product.
In the first test stage, I want to backup the current configuration, so that after my actual test stages, I can have one more stage which will restore it.
The problem is that part of this network configuration is stored in lists of unknown length (namely, the IP addresses).
I tried the naive approach:
```yaml
---
test_name: PUT:api/net/:ifname

strict:
  - json:off

stages:
  - name: Save the configuration of eth0 for further restoration
    request:
      url: http://{tavern.env_vars.OFORA_HOST}:8080/api/net/eth0
      method: GET
    response:
      status_code: 200
      save:
        json:
          ipv4_method: ipv4.method
          ipv6_method: ipv6.method
          ipv6_addresses: ipv6.addresses

/* some test stages */

  - name: Restore the original configuration
    request:
      url: http://{tavern.env_vars.OFORA_HOST}:8080/api/net/eth0
      json:
        autoconnect: False
        ipv4:
          method: "{ipv4_method:s}"
        ipv6:
          method: "{ipv6_method:s}"
          addresses: "{ipv6_addresses}"
        mtu: 0
      method: PUT
    response:
      status_code: 200
```

Which generates the `WARNING  tavern.util.dict_util:dict_util.py:46 Formatting 'ipv6_addresses' will result in it being coerced to a string (it is a <class 'box.box_list.BoxList'>)` warning and of course, the API complains that tipe tipe of the value is string when it is expecting an array.
That was apparently to be expected according to the documentation:
> only ‘simple’ values like integers, strings, or float values can be saved. Trying to save a ‘block’ of data such as a JSON list or object is currently unsupported and will cause the test to fail.

I also tried with `$ext` blocks but got the same warning.

Is there a way to save a list and then, retrieve it in order to pass it as a request argument?

Thank you by advance :)

**Comment by ncarrier** [comment]
Hello,
First of all, my apologies for not answering earlier, nearly 3 months is way too much :/

And then, thank you for your answer, it works like a charm, I changed my code for what follows with success.

```yaml
---
test_name: PUT:api/net/:ifname

strict:
  - json:off

stages:
  - name: Save the configuration of eth0 for further restoration
    request:
      url: http://{tavern.env_vars.OFORA_HOST}:8080/api/net/eth0
      method: GET
    response:
      status_code: 200
      json:
        ipv6:
          addresses: !anylist
      save:
        json:
          ipv4_method: ipv4.method
          ipv6_method: ipv6.method
          ipv6_addresses: ipv6.addresses

/* some test stages */

  - name: Restore the original configuration
    request:
      url: http://{tavern.env_vars.OFORA_HOST}:8080/api/net/eth0
      json:
        autoconnect: False
        ipv4:
          method: "{ipv4_method:s}"
        ipv6:
          method: "auto"
          addresses: !force_format_include "{ipv6_addresses}"
        mtu: 0
      method: PUT
    response:
      status_code: 200
```
