### ISSUE TITLE
Checking text responses

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#732]
eg

```yaml
stages:
  - name: check table is returned
    request:
      url: "{host}/example_table"
    response:
      status_code: 200
      text: |-
        +---+---+
        | A | B |
        +---+---+
        | 1 | 2 |
        | 3 | 4 |
        +---+---+
```
Should be able to check the result as if it was text.

It would be nice if you could also do something like

```yaml
  response:
    file_body_response: expected.txt
```

to check against the content of a file.
