### ISSUE TITLE
Unable to use bools in parameterized vals

### ISSUE THREAD

**Issue by hamx0r** [taverntesting/tavern#742]
Here's  a PR for this issue: https://github.com/taverntesting/tavern/pull/741

Here's a description of the problem:
The following `marks` entity cause an error because `vals` can't contain Bools (or lists with Bools in them)

```
  - parametrize:
      key:
        - use_this
      vals:
        - True
        - False
```
This doesn't work either

```
  - parametrize:
      key:
        - use_this
        - use_that
      vals:
        - [True, True]
        - [True, False]
        - [False, False]
        - [False, True]      
```
