### ISSUE TITLE
Json Payload Corruption

### ISSUE THREAD

**Issue by KenStorey** [taverntesting/tavern#743]
I'm experiencing test failures similar to this

```
========================================== test session starts ===========================================platform linux -- Python 3.9.0, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /usr/local/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.9.0', 'Platform': 'Linux-4.19.128-microsoft-standard-x86_64-with', 'Packages': {'pytest': '6.2.5', 'py': '1.11.0', 'pluggy': '1.0.0'}, 'Plugins': {'metadata': '1.11.0', 'tavern': '1.17.0', 'html': '3.1.1'}}
rootdir: /tavern_tests
plugins: metadata-1.11.0, tavern-1.17.0, html-3.1.1
collected 3 items

tavern_tests/test_gdcp_display_list.tavern.yaml::List display with selection FAILED                [ 33%]
tavern_tests/test_gdcp_display_list.tavern.yaml::List display cancelled FAILED                     [ 66%]
tavern_tests/test_gdcp_display_list.tavern.yaml::List display with timeout FAILED                  [100%]

================================================ FAILURES ================================================
_____________ /tavern_tests/test_gdcp_display_list.tavern.yaml::List display with selection ______________Format variables:
  hmi_display_list_topic = 'hmi/display_list'
  test_app = 'TestApp'
  left = '0'
  gdcp_ui_display_list_topic = 'gdcp/frmcs/user-interaction/displayList'

Source test stage (line 53):
  - name: Step 2 - Display a list

    mqtt_publish:
      topic: "{hmi_display_list_topic}"
      json:
        application: "{test_app}"
        application_ref: 4000
        list_title: English Rivers
        list_items:
          - Avon
          - Severn
          - Stour
          - Thames
          - Tyne
        text_justification: !int "{left}"

    mqtt_response:
      topic: "{gdcp_ui_display_list_topic}"
      json:
        timestamp: !anystr
        user-interaction:
          display-list:
            name: "English Rivers     "
            title: "English Rivers     "
            return-object:
              interaction-id: LIST
            item-list:
              - simple-selection:
                  name: "Avon                "
                  return-object:
                    interaction-id: LIST.1
              - simple-selection:
                  name: "Severn              "
                  return-object:
                    interaction-id: LIST.2
              - simple-selection:
                  name: "Stour               "
                  return-object:
                    interaction-id: LIST.3
              - simple-selection:
                  name: "Thames              "
                  return-object:
                    interaction-id: LIST.4
              - simple-selection:
                  name: "Tyne                "
                  return-object:
                    interaction-id: LIST.5


Formatted stage:
  mqtt_publish:
    json:
      application: 'TestApp'
      application_ref: 4000
      list_items:
      - Avon
      - Severn
      - Stour
      - Thames
      - Tyne
      list_title: English Rivers
      text_justification: !int '0'
    topic: 'hmi/display_list'
  mqtt_response:
    json:
      timestamp: !anystr ''
      user-interaction:
        display-list:
          item-list:
          - simple-selection:
              name: 'Avon                '
              return-object:
                interaction-id: LIST.1
          - simple-selection:
              name: 'Severn              '
              return-object:
                interaction-id: LIST.2
          - simple-selection:
              name: 'Stour               '
              return-object:
                interaction-id: LIST.3
          - simple-selection:
              name: 'Thames              '
              return-object:
                interaction-id: LIST.4
          - simple-selection:
              name: 'Tyne                '
              return-object:
                interaction-id: LIST.5
          name: 'English Rivers     '
          return-object:
            interaction-id: LIST
          title: 'English Rivers     '
    topic: 'gdcp/frmcs/user-interaction/displayList'
  name: Step 2 - Display a list

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Step 2 - Display a list' failed:
    - Expected '{'timestamp': <tavern.util.loader.StrSentinel object at 0x7f5e61773130>, 'user-interaction': {'display-list': {'name': 'English Rivers     ', 'title': 'English Rivers     ', 'return-object': {'interaction-id': 'LIST'}, 'item-list': [{'simple-selection': {'name': 'Avon                ', 'return-object': {'interaction-id': 'LIST.1'}}}, {'simple-selection': {'name': 'Severn              ', 'return-object': {'interaction-id': 'LIST.2'}}}, {'simple-selection': {'name': 'Stour               ', 'return-object': {'interaction-id': 'LIST.3'}}}, {'simple-selection': {'name': 'Thames              ', 'return-object': {'interaction-id': 'LIST.4'}}}, {'simple-selection': {'name': 'Tyne                ', 'return-object': {'interaction-id': 'LIST.5'}}}]}}}' on topic 'gdcp/frmcs/user-interaction/displayList' but no such message received 
    - Got unexpected payload on topic 'gdcp/frmcs/user-interaction/displayList': '{'timestamp': '2021-12-02 11:56:32.850', 'user-interaction': {'display-list': {'name': 'English Rivers      ', 'title': 'English Rivers      ', 'return-object': {'interaction-id': 'LIST'}, 'item-list': [{'simple-selection': {'name': 'Avon                ', 'return-object': {'interaction-id': 'LIST.1'}}}, {'simple-selection': {'name': 'Severn              ', 'return-object': {'interaction-id': 'LIST.2'}}}, {'simple-selection': {'name': 'Stour   
            ', 'return-object': {'interaction-id': 'LIST.3'}}}, {'simple-selection': {'name': 'Thames     
         ', 'return-object': {'interaction-id': 'LIST.4'}}}, {'simple-selection': {'name': 'Tyne
      ', 'return-object': {'interaction-id': 'LIST.5'}}}]}}}' (expected '{'timestamp': <tavern.util.loader.StrSentinel object at 0x7f5e61773130>, 'user-interaction': {'display-list': {'name': 'English Rivers     
', 'title': 'English Rivers     ', 'return-object': {'interaction-id': 'LIST'}, 'item-list': [{'simple-selection': {'name': 'Avon                ', 'return-object': {'interaction-id': 'LIST.1'}}}, {'simple-selection': {'name': 'Severn              ', 'return-object': {'interaction-id': 'LIST.2'}}}, {'simple-selection': {'name': 'Stour               ', 'return-object': {'interaction-id': 'LIST.3'}}}, {'simple-selection': 
{'name': 'Thames              ', 'return-object': {'interaction-id': 'LIST.4'}}}, {'simple-selection': {'name': 'Tyne                ', 'return-object': {'interaction-id': 'LIST.5'}}}]}}}')

```
At first glance the received data appears to match the expected but, on closer inspection, something in the process has inserted a newline characters after "Stour", Thames" and "Tyne".

```
{
  "timestamp": "2021-12-02 11:56:32.850",
  "user-interaction": {
    "display-list": {
      "name": "English Rivers      ",
      "title": "English Rivers      ",
      "return-object": {
        "interaction-id": "LIST"
      },
      "item-list": [
        {
          "simple-selection": {
            "name": "Avon                ",
            "return-object": {
              "interaction-id": "LIST.1"
            }
          }
        },
        {
          "simple-selection": {
            "name": "Severn              ",
            "return-object": {
              "interaction-id": "LIST.2"
            }
          }
        },
        {
          "simple-selection": {
            "name": "Stour   \n            ",
            "return-object": {
              "interaction-id": "LIST.3"
            }
          }
        },
        {
          "simple-selection": {
            "name": "Thames     \n         ",
            "return-object": {
              "interaction-id": "LIST.4"
            }
          }
        },
        {
          "simple-selection": {
            "name": "Tyne\n      ",
            "return-object": {
              "interaction-id": "LIST.5"
            }
          }
        }
      ]
    }
  }
}
```
