### ISSUE TITLE
tavern.util.exceptions.MQTTError - tavern not connecting to broker

### ISSUE THREAD

**Issue by tking16** [taverntesting/tavern#749]
I'm trying to test one of our organisations websockets, using a [simple websocket client](https://chrome.google.com/webstore/detail/simple-websocket-client/pfdhoblngboilpfeibdedpjgfnlcodoo?hl=en) I can connect fine, but running in tavern I get the following output:

```
Format variables:

Source test stages:

stages:
  - name: Verify Now Playing tracks are returned
    mqtt_publish:
      topic: /now-playing

    response:
      status_code: 200



Stage not found

Errors:
E   tavern.util.exceptions.MQTTError
---------------------------------------------------------------------------------------------------------------------------- Captured log call ----------------------------------------------------------------------------------------------------------------------------
ERROR    tavern._plugins.mqtt.client:client.py:341 Could not connect to broker after 3 seconds
```

My actual test looks like this:
```
test_name: Radio Websocket - Now Playing
paho-mqtt:
  client:
    transport: websockets
  connect:
    host: ws://radio-websocket.com
    timeout: 3
  tls:
    enable: false

stages:
  - name: Verify Now Playing tracks are returned
    mqtt_publish:
      topic: /now-playing
      # json:
      #   actions:
      #     - type: subscribe
      #       service: 128
    response:
      status_code: 200
    #   topic: /device/123/ping
    #   json:
    #     thing_1: abc
    #     thing_2: 123

```

I've commented out most of just so I can actually it to connect first. Apologies I don't have much experience with MQTT testing but thanks for your help
