### ISSUE TITLE
!anything doesn't work in dict body matches

### ISSUE THREAD

**Issue by Alan-R** [taverntesting/tavern#75]
This snippet works:
```yaml
- name: info
  request:
    url: https://symphonywest.naas.aws.charterlab.com:443/api/net/v1/info/
    method: GET
    headers:
      content-type: application/json
      Cache-Control: no-cache
  response:
    status_code: 200
    body:
      data:
        base_url: "/net"
        description: "NaaS REST API for Network Services"
        name: "naas-api-net"
        package: "naas.api.net"
        version: "1.4.38"
```
But this snippet does not:
```yaml
- name: info
  request:
    url: https://symphonywest.naas.aws.charterlab.com:443/api/net/v1/info/
    method: GET
    headers:
      content-type: application/json
      Cache-Control: no-cache
  response:
    status_code: 200
    body:
      data:
        base_url: "/net"
        description: "NaaS REST API for Network Services"
        name: "naas-api-net"
        package: "naas.api.net"
        version: !anything
```
Of course, I'd love to find out if I'm just doing something wrong too ;-). I assume the difference is that the !anything is under data in the JSON, not directly under the top level. I have an additional issue (#76) concerning that ;-).

**Comment by michaelboulton** [comment]
Which version of tavern were you using for this?

**Comment by Alan-R** [comment]
The latest as of yesterday - 0.7.7.

**Comment by michaelboulton** [comment]
I actually made an update just before lunch which should have fixed this issue - can you try it with 0.8.0?

**Comment by Alan-R** [comment]
My partner in this isn't at work yet (it's 0730 here). I'll have him try it as soon as he gets in.

Tavern is incredibly useful! It's exactly what we need at work (Charter Communications). It's also something the [Assimilation project](https://github.com/assimilation) could make good use of too ;-)

**Comment by Alan-R** [comment]
Sure. My partner in this isn't at work yet (here in the Mountain time zone in the US). I'll ping him.

By the way, this is really cool stuff! Exactly what we needed. And for that matter, the OWASP Assimilation project that I work on could make good use of it too ;-).

**Comment by michaelboulton** [comment]
good to hear!

**Comment by Alan-R** [comment]
Here's the example that I used to verify the fix:
```yaml
test_name: Check viewer for JSON output
stages:
    - name: Send not-very-specific request and check output
      request:
        method: GET
        url: http://db.itbestpractices.info:5000/itbp/v1.0/showjson?tipname=nist_V-38600
      response:
        status_code: 200
        body:
          severity: medium
          tags:
            nist:
              - V-38600
              - C-46157r2_chk
              - F-43547r1_fix
          text:
            en:
              check: !anything
              fix: !anything
              long_description: !anything
              short_description: !anything
```
