### ISSUE TITLE
Exception raise by tavern: structure-of-returned-data-was-different-than-expected

### ISSUE THREAD

**Issue by andrea-mucci** [taverntesting/tavern#760]
Hi all, this is my tavern test file, is a quite easy test that send a POST to add a product and send a GET to retrieve the information.

```yaml
test_name: Add products for tests

stages:
  - name: Add product one
    request:
      url: http://localhost:5566/product
      json:
        title: Product One
        description: Product One in our catalog
        picture: images/product.jpeg
        categories:
          - title: tshirt
          - title: casual
        price:
            currency: EUR
            units: 59
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 200
      headers:
        content-type: application/json
      save:
        json:
          product_id: uuid
    delay_after: 1

  - name: Get product one
    request:
      url: http://localhost:5566/product/{product_id}
      method: GET
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        picture: images/product.jpeg
        title: Product One
      headers:
        content-type: application/json
```

So, in the GET the returned structure is large and i want to check only one or two json keys, but i get the following error.

`ERROR    tavern.response.base:base.py:41 Structure of returned data was different than expected  - Extra keys in response: {'uuid', 'id', 'price_id', 'description'} (expected = '{'picture': 'images/product.jpeg', 'title': 'Product One'}' (type = <class 'dict'>), actual = '{'id': '1', 'uuid': '62c8c26d-c2c8-42a2-9111-2fd3186b08de', 'title': 'Product One', 'description': 'Product One in our catalog', 'picture': 'images/product.jpeg', 'price_id': '1'}' (type = <class 'dict'>))`

Seems quite strange that i have to replicate in the response the entire structure of the json object, so i don't know if I do something wrong or this is a tavern requirement, in that case would be interesting to be less strict and permit to test the partial json response.

Thanks in advance for your help
