### ISSUE TITLE
Intermittent test failure with `!re_fullmatch`

### ISSUE THREAD

**Issue by cciotti** [taverntesting/tavern#769]
Tavern: 1.20.0
Python: 3.9.4
Pytest: 6.2.5

I'm matching a UUID in my response using the example from the doc [here](https://tavern.readthedocs.io/en/latest/basics.html#matching-via-a-regular-expression). However, every few test runs, it fails.

The relevant block from the `response` looks like this:

```
    json:
        job_id: !re_fullmatch "[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89AB][0-9a-f]{3}-[0-9a-f]{12}"
        links:
        - rel: self
          href: !anystr
```

And this is the error I get:

```
Missing format vars for stage

Errors:
E   tavern.util.exceptions.TestFailError: Test 'POST to foo endpoint and do stuff' failed:
    - Regex mismatch: (expected["job_id"] = '<Tavern Regex sentinel for [0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89AB][0-9a-f]{3}-[0-9a-f]{12}>' (type = <class 'tavern.util.loader._RegexFullMatchSentinel'>), actual["job_id"] = '13957db5-089c-40e8-a087-43957a836b94' (type = <class 'str'>))
```

Any ideas?
