### ISSUE TITLE
Expand a map with fields passed through !force_format_include

### ISSUE THREAD

**Issue by thejuliakors** [taverntesting/tavern#775]
Hello,

Is there a way to expand a map with fields passed through `!force_format_include`? (Or any other way, in order the values wouldn't lose their type and be converted to the string). 

For example, I would like to test negative cases - by sending invalid values for multiple fields in the response body. The whole stage is literally the same for each such field, except for its value, i.e.:
```
- id: create_smth_with_invalid_field
    name: create a new smth with invalid field
    request:
      url: "{tavern.env_vars.API_URL}/v1/admin/smth"
      method: POST
      json:
        <<: *smth_test_data
        field: "{invalid_field_value}"
      headers: *headers
      ...
    response:
      status_code: 422
```
Here `field: "{invalid_field_value}"` is a field we want to test and `smth_test_data` - all other request body fields, which do not change. So, it would be cool to do parametrization like:
```
marks:
  - parametrize:
      key: invalid_field
      vals:
        - field_1: "invalid_value_1"
        - field_1: null
        - field_1: []
        - field_2: "invalid_value_2"
        - field_2: "invalid_value_3"
```
And then use it in the stage like that:
```
- id: create_smth_with_invalid_field
    name: create a new smth with invalid field
    request:
      url: "{tavern.env_vars.API_URL}/v1/admin/smth"
      method: POST
      json:
        <<: *smth_test_data
        <<: !force_format_include "{invalid_field}"
      headers: *headers
      ...
    response:
      status_code: 422
```
Otherwise, I need to copy-paste the same stage for each field field_1, field_2, ..., field_n.

Maybe, there are some other ways of doing this?
If not, it would be a nice enhancement.
