### ISSUE TITLE
The data saved in the previous stage is not the value saved when the next stage is used

### ISSUE THREAD

**Issue by iakirago** [taverntesting/tavern#792]
Here is the example
```
  - name: Create testcase for use
    request:
      url: "{HOST:s}/parallel/tests/"
      method: POST
      json:
        name: 'cov-test'
    response:
      strict:
        - json:off
      status_code: 200
      save:
        json:
          new_run_id: "testcase.run_id"
          newtest_uuid: "testcase.uuid"
          newtest_id: "testcase.id"

  - name: Verify uievents API
    request:
      url: "{HOST}/parallel/{newtest_id}/{new_run_id}"
      method: GET
    response:
      strict:
        - json:off
      status_code: 200
```
The first stage saved `new_run_id` is 1，and when used in the second stage it changed to '0'.
I would like to know where is the problem and how to solve this problem.

Thanks!
