### ISSUE TITLE
Possible enhancement: Top document in yaml file contains 'defaults' for whole file

### ISSUE THREAD

**Issue by michaelboulton** [taverntesting/tavern#803]
eg
```yaml
# test_thing.tavern.yaml
---
# the top document in a tavern file

includes:
- my-include.yaml

variables:
  a: b
  c: d

stages:
  - id: typetoken-anything-match
    name: match top level

paho-mqtt: 
  connect:
    host: localhost
    port: 9001
    timeout: 3
  client:
    transport: websockets
    client_id: tavern-tester

# etc.
---
test_name: my test

# everything from the top document is deep_dict_merge d into this document
```
