### ISSUE TITLE
Is there a way to have the stage repeated multiple times, like in a loop

### ISSUE THREAD

**Issue by bharatid** [taverntesting/tavern#814]

**Comment by bharatid** [comment]
Want to call the same stage multiple times. Is there a way to do that?

**Comment by bharatid** [comment]
Sorry, closed it inadvertently

**Comment by michaelboulton** [comment]
There isn't a way to do that, you can either use a YAML anchor to repeat the stage in the test like this

```yaml

stages:
  - &to_repeat
    name: stage to repeat
    request:
     ...

  - <<: *to_repeat

  - <<: *to_repeat
```
Or use the [retry mechanism](https://tavern.readthedocs.io/en/latest/basics.html#retrying-tests) if you want a stage repeated 'until it passes'
