### ISSUE TITLE
How to pass parameters to function in verify_response_with

### ISSUE THREAD

**Issue by SabreenKaur** [taverntesting/tavern#831]
I have a test which is using an external function I wrote in a separate python file called test_utils.py. I would like to be able to pass other parameters to this function so that I can use it in the function body. For example I would like to pass a file directory as a parameter to the function `my-function` in the below test

test_verify_results.tavern.yaml
```
  - name: verify result
    request:
      method: POST
      url: 'http://test:8080
      headers:
        Content-type: application/json
    response:
      status_code: 200
      verify_response_with:
        - function: test_utils:my-function
```

test_utils.yaml
```
def my_function(response, file_dir):
    <code using file_dir>
```

Is possible to pass parameters to own defined functions in this way?
