### ISSUE TITLE
saved value which is in Integer converting to String while Reading it 

### ISSUE THREAD

**Issue by raghavakora** [taverntesting/tavern#85]
saving the response like 
```yaml
   owner:
              **owner-id: !anyint**
              owner-name: "test zyx"
              email-distribution-list: ["datalakeemail@two.com"]
      save:
        body:
          **owner-id: owner.owner-id**
```

trying to read in the subsequent test like
```yaml
        owner:
            owner-id: "{owner-id:d}"
            owner-name: "test zyx"
```

Getting difference in the Expected and actual
Expected : showing owner-id in string instead of in Int/nuber

If some one could help me out that would be really great

**Comment by michaelboulton** [comment]
If you try to use the value in a subsequent test, you need to convert the type again using `!int`, for example:


```yaml
        owner:
            owner-id: !int "{owner-id:d}"
            owner-name: "test zyx"
```

This is because it is currently impossible to save values as anything other than strings.
