### ISSUE TITLE
No handlers could be found for logger "root" 

### ISSUE THREAD

**Issue by ppr-A320** [taverntesting/tavern#86]
I am getting this error  after including external function. 

Tavern Version: 0.9.0
Docker ubuntu image
Python 2.7.12

```python
# utils.py
def test_function(response):
    return {"test_user_id": "test"}
```

```yaml
#main.yaml
  - name: Get location list
    request:
      url: "{protocol:s}://{host:s}:{port:d}/{base_url:s}/{location_list:s}/{requestId:s}&search=%7Btype%3AREGION%7D"
      method: GET
      headers:
        Authorization: "{test_login_token:s}"
    response:
      status_code: 200
      body:
        {}
      headers:
        content-type: application/json
      save:
        $ext:
          function: utils:test_function
        body:
          test_user_id: test_user_id
```

Command
 tavern-ci  main.yaml  --stdout

If some one could help me out that would be really great
