### ISSUE TITLE
2FA Log In

### ISSUE THREAD

**Issue by MorganFujimaka** [taverntesting/tavern#868]
What would be the best strategy to test API having a 2FA login (e.g. Okta via Authlib)?

Is it possible to log in using [`django.test.Client`](https://docs.djangoproject.com/en/4.2/topics/testing/tools/#django.test.Client.login) rather than API and have the logged-in user in the following stages?:
```python
from django.test import Client

client.login(username, password)
```

**Comment by michaelboulton** [comment]
I haven't used Django for a while but I think there's 2 options to do this: Either write a fixture that logs in using the django client and get the cookies:

```python
import http.cookies
from django.test import Client


def django_cookies(client: Client) -> http.cookies.SimpleCookie:
    client.login("username", "password")

    return client.cookies
```

```yaml
---
test_name: Use Django client to create cookies

marks:
  - usefixtures: django_login

stages:
  - name: Do a request with cookies
    request:
      url: "{host}/thing"
      method: GET
    cookies:
      - my_cookie_name: "{django_cookies.my_cookie_name}"
```

If that doesn't work, you'd probably have to write a [plugin](https://tavern.readthedocs.io/en/latest/plugins.html) that
logged in via the Django authentication system and then used the client to do all future http requests
