### ISSUE TITLE
Try to use the external function in the URL

### ISSUE THREAD

**Issue by IrisBlume-dot** [taverntesting/tavern#875]
Hi
I want to get an `ID` value from another program and splice it into the URL.
Similar to: http://localhost:7200/api/manager/system/organizations/{id}
so I try to use external function,

- Tavern `2.2.0`

```
  - name: Delete a user
    request:
      method: DELETE
      url:
        $ext:
          function: web.common:id_query
    response:
      status_code: 200
```
But there seems to be an anomaly.
Is this usage supported?
