### ISSUE TITLE
Variable in skip when on test

### ISSUE THREAD

**Issue by lvijnck** [taverntesting/tavern#881]
I was trying to do something along the lines of the following code snippet, i.e., conditionally disable a step of my test. This seems to not interpolate the vars.

```
test_name: Dummy

stages:
  - name: Model call without authentication header
    skip: !bool "{tavern.env_vars.SKIP}
    request:
       ...
```
