### ISSUE TITLE
BadSchemaError trying to use redirect_query_params key in response

### ISSUE THREAD

**Issue by Kijuoye** [taverntesting/tavern#925]
As the documentation says, I tried to use the redirect_query_params key in response to test the implementation of an OpenID connect provider. However, I get a BadSchemaError as the key is unexpected.

```
test_name: Test /login endpoint

strict:
    - json:off

stages:
   - name: Get from /login redirect response
     request:
         ...
     response:
         status_code: 302
         redirect_query_params:      # Here, it says: Additional porperties are not allowed ('redirect_query_params' was unexpected)
             ....

```

This is esentially the yaml I'm using
