### ISSUE TITLE
Problem sending file

### ISSUE THREAD

**Issue by luishens01** [taverntesting/tavern#93]
Hi, 
we are currently learning Tavern for Rest testing and I have a problem creating a test.

This is an example of the working curl that I need to create in Tavern:

`curl -f -v -i -X POST -H "Authorization:Bearer XXX...XXXX" -F package=@/dir1/dir2/MY_FILE http://url`

and this is the way we are trying to recreate it:

```yaml
  _- name: upload_package
    request:
      url: http://url
      method: POST
      headers:
        authorization: "Bearer {test_login_token:s}"
        Content-Type: "multipart/form-data;
      files: 
        package: "/dir1/dir2/MY_FILE"
    response:
      status_code: 201_
```

This is not working for us and have been trying a lot of combinations with the content-types in headers.

Could you guide us in how we can achieve this ?

Thanks in advance
Luis
