### ISSUE TITLE
Python function not callable from tavern script for saving 

### ISSUE THREAD

**Issue by ShreyanshAyanger-Nykaa** [taverntesting/tavern#946]
Hi, I am calling a save function after getting response from my api, now in the response received i need to format string and save only few elements present,
```
       response:
            status_code: 200
            save:
                headers:
                    res_key:
                        $ext:
                            function: testing_utils:extract_sessid
                            extra_kwargs:
                                head: headers
```
 however, my tavern yaml is unable to call extract_string method in testing_utils file,
 But other functions written in testing_utils are working fine with following syntax
 ```
            verify_response_with:
                -   function: testing_utils:check_jsonpath_value
```

Please help, basically in above way mentioned, the testing_utils file is not accessible ( inside save function) but in same tavern script existing test cases are able to access the same ( with verify_response_with).

**Comment by michaelboulton** [comment]
Can you try with
```yaml
       response:
            status_code: 200
            save:
                headers:
                    $ext:
                        function: testing_utils:extract_sessid
                        extra_kwargs:
                            head: headers
```
and make the `extract_sessid` function return a dictionary, something like 
```python
def extract_sessid(response):
    return {"res_key": "..."}
```
The `$ext` functions are only looked for in the top level of a block
