### ISSUE TITLE
Skip at stage level doesn't evaluate a tavern binary variable, instead it evaluates always as True

### ISSUE THREAD

**Issue by RiGor66** [taverntesting/tavern#948]
Hello Tavern Team!!

As you know we can skip a stage become executed by using code like these
```
stages:
  - name: Test_stage name abc
     skip: !bool "yes"
```
In the same way I can tell tavern to don't skip a stage using something like this:
```
stages:
  - name: Test_stage name abc
     skip: !bool "NO"
```

However if I want to skip a stage based on a variable, someway like this:
```
...
stages:
  - name: Get a binary status
     request:
       url: "{test_url}/legal-acceptance"
       method: GET
     response:
       status_code: 200
      json:
        accept: !anybool
      save:
        json:
          skipStep: accept

  - name: Test_stage name abc
     skip: !bool "{skipStep}"
...
``` 
Tavern evaluates this skip always as True, independetly of the binary value stored in such variable {skipStep}. Why Tavern deal's this case in this way? 
It will be strongly useful if Tavern could evaluate the binary content of a variable in the stage's skip, since in this way we could execute or not some stages depending on some logic variable states previous defined/stored among the test.
