### ISSUE TITLE
BadSchemaError while overriding variables in subsequent test file

### ISSUE THREAD

**Issue by m-u-h-a-m-m-a-d** [taverntesting/tavern#959]
I have a `common.yml` file that defines a set of global variables intended to be shared across multiple test files. In one of the test files where I include `common.yml`, I want to override the value of a specific variable (uuid) using a new dynamically generated value.

However, when I add a `variables` section in the test file to override uuid, I encounter a `BadSchemaError`. The error disappears if I remove the variables section from the test file, which indicates that the conflict arises from redefining the same variable.

### common.yml
```
---
name: Basic request variables
description: Used for test requests

variables:
  uuid: !uuid
```
### test_sample.yml
```
---
test_name: Test Sample

includes:
  - !include common.yml

variables:
  uuid: !uuid

strict:
  json: false

stages:
  # defined tests
```

I expect to be able to override uuid in the test file without causing a schema error
