### ISSUE TITLE
Execute arbitrary external Python code as a test

### ISSUE THREAD

**Issue by alexdlaird** [taverntesting/tavern#98]
Tavern's flexibility could be improved immensely if you allowed for the execution of external code as a test case rather than only as a save. There is a workaround that currently allows this, I just think it would be clearer (and more helpful) if this were treated as a first-class citizen—Tavern can do a ton, but sometimes there's just one extra assert or custom prep step that you need to leveral pure Python for.

Here is what I currently do as a workaround to achieve the above:

```
- name: Get verification code from email
    request:
      url: "{tavern.env_vars.ENV_API_HOST}/info/"
    response:
      save:
        $ext:
          function: utils.emailhelper:get_verification_code
          extra_kwargs:
            username: "{test_username:s}"
```

As you can see, the call to /info/ is completely unnecessary—what I'm actually trying to do is get the verification code (which is stored in S3), so I leverage a Python function to do this. This seems a pretty common use case, so just leaving it here for a future improvement.

P.S. LOVE what you guys are doing here!
